### ISSUE TITLE
Non generic functions accept generic specialization syntax in some cases

### ISSUE THREAD

**Issue by TeamPuzel** [swiftlang/swift#73749] opened 2024-05-20 14:16 UTC
### Description

Swift is allowing a syntax mistake.

### Reproduction

It seems that a function can "accept" explicit generic parameters in this situation:
```swift
func z() -> Int { 1 }                 // Non generic function
func z<T: FloatingPoint>() -> T { 1 } // Generic overload of that function
let y: Int = z<Float>()               // Nonsense syntax compiles (the parameter is ignored but there is no error)
```
It does not seem to happen when either of the overloads is commented out, catching the invalid syntax.

### Expected behavior

An error message detecting the misleading syntax.

### Environment
```
Apple Swift version 6.0-dev (LLVM 3417addab6ff197, Swift d677b7c23fd6355)
Target: arm64-apple-macosx14.0
```

**Comment by xedin** [comment] 2024-08-02 20:20
I think @gregomni fixed this recently via https://github.com/swiftlang/swift/pull/75526

**Comment by xedin** [comment] 2024-08-02 20:22
Main compiler produces:

```
3 | let y: Int = z<Float>()
  |              `- error: cannot specialize non-generic type '() -> Int'
```

**Comment by AnthonyLatsis** [comment] 2024-08-02 20:32
Almost certainly. Bug still there in my June 4th checkout.

**Comment by AnthonyLatsis** [comment] 2024-08-02 20:32
Duplicate of #74857

**Closed by AnthonyLatsis** 2024-08-02 20:32 UTC
Labels: bug, duplicate, compiler, type checker, accepts invalid, generics, expressions, swift 6.0
