### ISSUE TITLE
Compiler crash building swiftpm with Windows ARM toolchain

### ISSUE THREAD

**Issue by dschaefer2** [swiftlang/swift#75809] opened 2024-08-09 17:47 UTC
### Description

Compiler crash using the Aug 7 Windows ARM 6.0 toolchain, building swiftpm main.

[build.txt](https://github.com/user-attachments/files/16565085/build.txt)

### Reproduction

Building the main branch of swiftpm.

### Expected behavior

No crash :).

### Environment

Swift version 6.0-dev (LLVM 73a346c9caf32cc, Swift 3e21fc6610cc917)
Target: aarch64-unknown-windows-msvc

**Comment by dschaefer2** [comment] 2024-08-09 18:24
The crash does not happen with the x86_64 Windows toolchain. Only ARM.

**Comment by compnerd** [comment] 2024-08-09 22:05
Interesting! This should be a pretty generic thing, I think that we are silently failing the verifier on Darwin.

**Comment by hjyamauchi** [comment] 2024-08-16 23:29
A slightly simpler reproduction:

```
git clone https://github.com/jpsim/Yams -b 5.0.6
cd Yams
swift build
```

**Comment by hjyamauchi** [comment] 2024-08-19 18:33
I was able to reproduce this error with a local Windows **X64** build with `SwiftCompilerSources` disabled.

@eeckstein, is the `SwiftCompilerSources`-disabled compiler no longer CI-tested or supported outside of Windows ARM64? CC @compnerd

**Comment by eeckstein** [comment] 2024-08-20 05:42
> @eeckstein, is the SwiftCompilerSources-disabled compiler no longer CI-tested (or supported?) outside of Windows ARM64? 

Correct.
Unfortunately SwiftCompilerSources are disabled on Windows arm64 because of a miscompile which let the compiler crash immediately (https://github.com/swiftlang/swift/issues/74866). I hope that someone with low-level debugging experience can take a look and fix this problem.

**Comment by hjyamauchi** [comment] 2024-08-20 16:54
Ok, will see what I can do :)

**Comment by atrick** [comment] 2024-09-13 22:22
This looks like a duplicate of https://github.com/swiftlang/swift/issues/74866
SwiftCompilerSources doesn't work on Windows ARM64

**Closed by atrick** 2024-09-13 22:22 UTC
Labels: bug, SIL, triage needed
