### ISSUE TITLE
Circular definition through existential compiles without error

### ISSUE THREAD

**Issue by glbrntt** [swiftlang/swift#74986] opened 2024-07-05 08:20 UTC
### Description

The compiler compiles a circular definition through an existential without an error.

### Reproduction

This compiles without warnings/errors:

```swift
let foo: any Error = foo
```

The following program runs and exits cleanly:

```swift
let foo: any Error = foo

func itThrows() throws {
  throw foo
}

try itThrows()
```

### Expected behavior

The code should fail to compile and should emit a diagnostic about a circular reference.

### Environment

Swift version 6.0-dev (LLVM 5b37bd4c1c578e9, Swift 54898ce105c7185)
Target: aarch64-unknown-linux-gnu

Also reproduces on 5.10, 5.9, and 5.8.

**Comment by AnthonyLatsis** [comment] 2024-07-05 12:07
Duplicate of #70323

**Closed** 2024-07-05 12:08 UTC
Labels: bug, duplicate, compiler, definite initialization, accepts invalid, SIL, memory safety, global let & var, swift 6.0
