### ISSUE TITLE
Wrong initializer called for stored property initialization

### ISSUE THREAD

**Issue by hamishknight** [swiftlang/swift#70931] opened 2024-01-16 15:39 UTC
### Description

For the following code, we somehow ending up calling into `y`'s initializer for `z`

### Reproduction

```swift
struct S {
  let y = { 1 }(), z = { 2 }()
}
let x = S()
print(x.z) // 1
```

### Expected behavior

`z` should be 2

### Environment

Swift version 5.11-dev (LLVM e2b71339d3295a4, Swift f79dea228e269b5)
Target: x86_64-apple-macosx14.0

**Comment by AnthonyLatsis** [comment] 2024-01-17 13:16
Duplicate of #62940

**Closed by AnthonyLatsis** 2024-01-17 13:16 UTC
Labels: bug, duplicate, compiler, mangling, closures, expressions, unexpected behavior, let & var, swift 6.0
