### ISSUE TITLE
Error reported nowhere

### ISSUE THREAD

**Issue by dabrahams** [swiftlang/swift#62912] opened 2023-01-08 20:04 UTC
Check out the swift-bug-error-reported-nowhere tag of [val-lang/val](https://github.com/val-lang/val).  Then `swift test` with:

swift-driver version: 1.62.15 Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)
Target: arm64-apple-macosx13.0

the first error is:
```
[1/5] Compiling FrontEnd AST+Extensions.swift
<unknown>:0: error: cannot convert return expression of type '()' to return type 'Bool'
```

Which is not very helpful!

**Comment by AnthonyLatsis** [comment] 2023-01-08 20:20
Could be #61623. Have you tried a trunk snapshot?

**Comment by dabrahams** [comment] 2023-01-08 21:17
I have not, and it's probably not worth the effort.  But your guess is a good one!

**Comment by LucianoPAlmeida** [comment] 2023-01-09 01:50
This was likelly fixed by https://github.com/apple/swift/pull/59982

**Comment by AnthonyLatsis** [comment] 2023-01-09 22:56
Fix confirmed with the latest trunk snapshot:

```
/Users/mac/Desktop/val/Sources/FrontEnd/AST+Extensions.swift:30:11: error: cannot convert value of type '()' to closure result type 'Bool'
          return
          ^~~~~~
```

**Closed by AnthonyLatsis** 2023-01-09 22:56 UTC
Labels: bug, duplicate, compiler, diagnostics QoI, type checker, closures

**Comment by AnthonyLatsis** [comment] 2023-01-09 22:59
Duplicate of #59716
