### ISSUE TITLE
Cannot use protocol with primary associated type requirement in protocol composition

### ISSUE THREAD

**Issue by ahoppen** [swiftlang/swift#75602] opened 2024-07-31 21:53 UTC
The following doesn’t compile. I would expect it to. Otherwise I don’t see any way of specifying any kind of `String` collection that’s sendable.

```swift
let x: any Collection<String> & Sendable = [] // error: Non-protocol, non-class type 'Collection<String>' cannot be used within a protocol-constrained type
```

rdar://132374933

**Comment by slavapestov** [comment] 2024-08-03 18:23
Yeah, this is a known limitation.

**Comment by slavapestov** [comment] 2024-08-03 19:16
Dupe of https://github.com/swiftlang/swift/issues/63877

**Closed by slavapestov** 2024-08-03 19:16 UTC
Labels: bug, duplicate, compiler, type checker, parameterized protocols, existentials, protocol compositions, unexpected error, types, swift 6.0
