### ISSUE TITLE
Unable to form key path to main actor-isolated properties

### ISSUE THREAD

**Issue by NachoSoto** [swiftlang/swift#74636] opened 2024-06-21 21:39 UTC
### Description

The following code used to compile with Swift 5.x, but there is no way to do this with Swift 6 currently.

### Reproduction

```swift
import SwiftUI

struct Content: View {
   // Cannot form key path to main actor-isolated property 'value'
  @Environment(\.value) private var value

  var body: some View {
    Text("")
  }
}

extension EnvironmentValues {
  @MainActor public var value: Int { 0 }
}
```

### Expected behavior

Code compiles. Specifically, this makes it impossible to use `EnvironmentValues.requestReview` as defined in `StoreKit`:

```swift
extension EnvironmentValues {
    @available(iOS 16.0, macOS 13.0, visionOS 1.0, *)
    @available(tvOS, unavailable)
    @available(watchOS, unavailable)
    @MainActor public var requestReview: RequestReviewAction { get }
}
```

### Environment

Apple Swift version 6.0 (swiftlang-6.0.0.3.300 clang-1600.0.20.10)
Target: arm64-apple-macosx14.0

**Comment by xedin** [comment] 2024-07-12 17:13
Is this a dupe of https://github.com/swiftlang/swift/issues/72181?

**Comment by hborla** [comment] 2024-07-14 02:05
Duplicate of https://github.com/swiftlang/swift/issues/72181

**Closed by hborla** 2024-07-14 02:05 UTC
Labels: bug, triage needed
