### ISSUE TITLE
Call site for `==` variadic tuple comparison crashes compiler

### ISSUE THREAD

**Issue by xwu** [swiftlang/swift#75311] opened 2024-07-17 21:39 UTC
### Description

Take the pack iteration example given in [our blog post](https://www.swift.org/blog/pack-iteration/#introducing-pack-iteration)—I've used slightly different variable names, but it's the same code:

```swift
func == <each T: Equatable>(_ lhs: (repeat each T), _ rhs: (repeat each T)) -> Bool {
    for (l, r) in repeat (each lhs, each rhs) {
        guard l == r else { return false }
    }
    return true
}
```

On its own, the code above now compiles in Swift 6.0. But now, let's try to actually use it—for example, in an implementation of `!=`:

```swift
func != <each T: Equatable>(_ lhs: (repeat each T), _ rhs: (repeat each T)) -> Bool {
    !(lhs == rhs)
}
```

Sadly, we cannot: the compiler crashes.

### Reproduction

```swift
func == <each T: Equatable>(_ lhs: (repeat each T), _ rhs: (repeat each T)) -> Bool {
    for (l, r) in repeat (each lhs, each rhs) {
        guard l == r else { return false }
    }
    return true
}

func != <each T: Equatable>(_ lhs: (repeat each T), _ rhs: (repeat each T)) -> Bool {
    !(lhs == rhs)
}
```

### Stack dump

```text
swift-frontend: /home/build-user/swift/lib/SILGen/RValue.cpp:715: void swift::Lowering::RValue::extractElements(SmallVectorImpl<swift::Lowering::RValue> &) &&: Assertion `!tupleTy.containsPackExpansionType() && "can't extract elements from tuples containing pack expansions " "right now"' failed.
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the crash backtrace.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/swift-nightly/usr/bin/swift-frontend -frontend -S -primary-file <source> -target x86_64-unknown-linux-gnu -disable-objc-interop -g -debug-info-format=dwarf -dwarf-version=4 -empty-abi-descriptor -Xcc -working-directory -Xcc /app -resource-dir /opt/compiler-explorer/swift-nightly/usr/lib/swift -enable-anonymous-context-mangled-names -file-compilation-dir /app -Xllvm --x86-asm-syntax=intel -module-name output -in-process-plugin-server-path /opt/compiler-explorer/swift-nightly/usr/lib/swift/host/libSwiftInProcPluginServer.so -plugin-path /opt/compiler-explorer/swift-nightly/usr/lib/swift/host/plugins -plugin-path /opt/compiler-explorer/swift-nightly/usr/local/lib/swift/host/plugins -o /app/output.s
1.	Swift version 6.0-dev (LLVM 0ad8ad0245d47b4, Swift 01bd2b4f8c84d45)
2.	Compiling with effective version 5.10
3.	While evaluating request ASTLoweringRequest(Lowering AST to SIL for file "<source>")
4.	While silgen emitFunction SIL function "@$s6output2neoiySbxxQp_t_xxQp_ttRvzSQRzlF".
 for '!=(_:_:)' (at <source>:8:1)
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  swift-frontend 0x00005b21f2f216b7
1  swift-frontend 0x00005b21f2f1f3be
2  swift-frontend 0x00005b21f2f21d2f
3  libc.so.6      0x00007ba22b642520
4  libc.so.6      0x00007ba22b6969fc pthread_kill + 300
5  libc.so.6      0x00007ba22b642476 raise + 22
6  libc.so.6      0x00007ba22b6287f3 abort + 211
7  libc.so.6      0x00007ba22b62871b
8  libc.so.6      0x00007ba22b639e96
9  swift-frontend 0x00005b21ec98fc24
10 swift-frontend 0x00005b21ec9cb54e
11 swift-frontend 0x00005b21ec9b096f
12 swift-frontend 0x00005b21ec99c3f9
13 swift-frontend 0x00005b21ec9afb05
14 swift-frontend 0x00005b21ec9be94b
15 swift-frontend 0x00005b21ec9bdec0
16 swift-frontend 0x00005b21ec9a18a1
17 swift-frontend 0x00005b21ec99f47d
18 swift-frontend 0x00005b21eca2d034
19 swift-frontend 0x00005b21eca2124c
20 swift-frontend 0x00005b21ec9b19a9
21 swift-frontend 0x00005b21ec99c3f9
22 swift-frontend 0x00005b21ec9afb05
23 swift-frontend 0x00005b21ec9be94b
24 swift-frontend 0x00005b21ec9bdec0
25 swift-frontend 0x00005b21ec9a18a1
26 swift-frontend 0x00005b21ec99f47d
27 swift-frontend 0x00005b21eca2d034
28 swift-frontend 0x00005b21eca1df46
29 swift-frontend 0x00005b21ecad6f19
30 swift-frontend 0x00005b21ecad4fe8
31 swift-frontend 0x00005b21ecad38a4
32 swift-frontend 0x00005b21ecad230d
33 swift-frontend 0x00005b21eca5013f
34 swift-frontend 0x00005b21ec979b22
35 swift-frontend 0x00005b21ec97aee2
36 swift-frontend 0x00005b21ec977f6c
37 swift-frontend 0x00005b21ec97e190
38 swift-frontend 0x00005b21ecad1c34
39 swift-frontend 0x00005b21ec983b15
40 swift-frontend 0x00005b21ec97f02c
41 swift-frontend 0x00005b21ec1c5e1f
42 swift-frontend 0x00005b21ec1d7009
43 swift-frontend 0x00005b21ec1c91e1
44 swift-frontend 0x00005b21ec1c7f01
45 swift-frontend 0x00005b21ebfec754
46 libc.so.6      0x00007ba22b629d90
47 libc.so.6      0x00007ba22b629e40 __libc_start_main + 128
48 swift-frontend 0x00005b21ebfeb7ee

*** Signal 11: Backtracing from 0x7ba22b628898... done ***

*** Program crashed: Bad pointer dereference at 0x0000000000000000 ***

Thread 0 "swift-frontend" crashed:

0  0x00007ba22b628898 <unknown> in libc.so.6


Registers:

rax 0x0000000000000000  0
rdx 0x00007ba22bc8d880  80 d8 c8 2b a2 7b 00 00 a0 e2 c8 2b a2 7b 00 00  ·ØÈ+¢{·· âÈ+¢{··
rcx 0x00007ba22b6969fc  41 89 c5 41 f7 dd 3d 00 f0 ff ff b8 00 00 00 00  A·ÅA÷Ý=·ðÿÿ¸····
rbx 0x0000000000000006  6
rsi 0x0000000000000001  1
rdi 0x0000000000000001  1
rbp 0x00007ba22b81be90  01 00 00 00 01 00 00 00 80 d8 c8 2b a2 7b 00 00  ·········ØÈ+¢{··
rsp 0x00007ffc12e49160  20 00 00 00 00 00 00 00 a0 b6 81 2b a2 7b 00 00   ······· ¶·+¢{··
 r8 0x0000000000000000  0
 r9 0x0000000000000000  0
r10 0x0000000000000008  8
r11 0x0000000000000246  582
r12 0x00005b21f4d53a94  2f 68 6f 6d 65 2f 62 75 69 6c 64 2d 75 73 65 72  /home/build-user
r13 0x00000000000002cb  715
r14 0x00005b21f433b424  21 74 75 70 6c 65 54 79 2e 63 6f 6e 74 61 69 6e  !tupleTy.contain
r15 0x00007ffc12e493a0  40 e2 11 f8 21 5b 00 00 50 e2 11 f8 21 5b 00 00  @â·ø![··Pâ·ø![··
rip 0x00007ba22b628898  f4 83 3d 00 36 1f 00 05 75 14 c7 05 f4 35 1f 00  ô·=·6···u·Ç·ô5··

rflags 0x0000000000010246  ZF PF

cs 0x0033  fs 0x0000  gs 0x0000


Images (27 omitted):

0x00007ba22b600000–0x00007ba22b7bc341 490fef8403240c91833978d494d39e537409b92e libc.so.6 /lib/x86_64-linux-gnu/libc.so.6

Backtrace took 0.03s

Program terminated with signal: SIGSEGV
Compiler returned: 139
```

### Expected behavior

The code should compile, or else the compiler should reject the code with a proper diagnostic.  
The compiler should not crash.

### Environment

Swift version 6.0-dev (LLVM 0ad8ad0245d47b4, Swift 01bd2b4f8c84d45)

**Comment by AnthonyLatsis** [comment] 2024-07-18 02:46
Duplicate of #66392

**Closed by AnthonyLatsis** 2024-07-18 02:46 UTC
Labels: bug, duplicate, compiler, generics, crash, tuples, expressions, parameter packs, assertion failure, swift 6.0
