### ISSUE TITLE
error: failed to produce diagnostic for expression

### ISSUE THREAD

**Issue by TuscanBlue** [swiftlang/swift#63295] opened 2023-01-29 19:59 UTC
I am learning Swift, and was following an online example while developing a solution to a task, but I cannot spot the error:

```swift
func accum(_ s: String) -> String {
    var result : String = ""
    for (n, c) in  s.characters.enumerate() {
        print(c)
        result += c
    }
    return result
}

print(accum("Swift"))
```

**Comment by xedin** [comment] 2023-01-29 21:28
Try it with the latest `main` toolchain, looks like it prints:

```
```

**Comment by AnthonyLatsis** [comment] 2023-01-30 18:07
> looks like it's fixed and compiler produces [...]

Confirmed. I will assume it is a duplicate of #61363.
___

@TuscanBlue Sorry for the trouble! The function you are looking for is `enumerated`. Which Swift version were you running?

**Closed** 2023-01-30 18:37 UTC
Labels: bug, duplicate, compiler, diagnostics QoI, type checker, failed to produce diagnostic, for-in loops, pattern matching
