### ISSUE TITLE
Initializing subclass creates instance of superclass instead of subclass when optimization is enabled

### ISSUE THREAD

**Issue by jayhickey** [swiftlang/swift#61800] opened 2022-10-29 21:17 UTC
**Describe the bug**

I am seeing different behavior for subclass initialization when compiled with swift optimization `-Onone` vs `-O` when the superclass initializer is `private`. For example:

```swift
class MyClass {
  convenience init() {
    self.init(value: "")
  }
  
  private init(value: String) { }
  
  func printType() {
    print("This is MyClass")
  }
}

class MySubclass: MyClass {
  override func printType() {
    print("This is MySubclass")
  }
}

let subclass: MyClass = MySubclass()

// prints "This is MySubclass" when compiled with -Onone ✅
// prints "This is MyClass" when compiled with -O ❌
subclass.printType()

```

**Steps To Reproduce**

1. Download the below sample code or create a project with the above example
2. Run with optimization disabled (`-Onone`), notice that "MySubclass" prints
3. Run with optimization enabled (`-O`), notice that "MyClass" prints

**Expected behavior**

Initializing a subclass always properly initializes an instance of the class instead of the superclass.

**Screenshots**

https://user-images.githubusercontent.com/1676460/198852476-87044dc0-e50a-4a2e-ab8d-c4d103b4fc1b.mov

There are two schemes in the below example project to illustrate this issue.
"Debug Build" scheme -> `-Onone`
"Release Build" scheme -> `-O`

Sample project: [SubclassInitSkipped.zip](https://github.com/apple/swift/files/9894592/SubclassInitSkipped.zip)

**Environment (please fill out the following information)**

OS: macOS 12.5.1 (21G83)
Xcode Version/Tag/Branch: Version 14.0.1 (14A400), Swift 5.7

**Additional context**

Might be a dupe of #43787, but the sample project in that issue is no longer accessible.

**Comment by Chissel** [comment] 2022-11-10 11:51
The problem is, that swift allocating memory for the superclass and not for the subclass. So you can handover parameter to other classes (e.g. internal libraries) which has not the correct type.

This code will crash in the internal library of swift, because _modelB.valueB_ link to a not allocated memory and is nil.

`import Foundation

public class ModelA {
    private init() {}

    public convenience init(foo: String? = nil) {
        self.init()
    }
}

public class ModelB: ModelA {
    let valueB: String = "Foo"
}

let modelB = ModelB()

print(modelB.valueB)`

**Comment by AnthonyLatsis** [comment] 2022-11-10 20:26
Duplicate of #61508 (see https://github.com/apple/swift/issues/61508#issuecomment-1279405812). The convenience initializer should not be inherited in the first place.

**Closed by AnthonyLatsis** 2022-11-10 20:26 UTC
Labels: compiler, type checker, inheritance, swift 5.7, unexpected error, init, class, convenience init
