### ISSUE TITLE
Compiler crash for getter of `any (Protocol1<X> & Protocol2)`

### ISSUE THREAD

**Issue by glbrntt** [swiftlang/swift#75242] opened 2024-07-15 16:21 UTC
### Description

Compiler crashes because it fails to reconstruct a type where the type is a combination of a protocol with a primary associated type and another protocol.

### Reproduction

```swift
protocol P1<E> {
  associatedtype E
}

protocol P2 {}

struct Wrapper<E>: P1 {
  // Need a typealias because of https://github.com/swiftlang/swift/issues/63877
  typealias Wrapped = P1<E> & P2
  let wrapped: any Wrapped

  // Note: doesn't crash when 'private':
  // private let wrapped: any Wrapped

  init<O: P1<E>>(wrapping other: O) where O: P2 {
    self.wrapped = other
  }
}
```

### Stack dump

```text
error: compile command failed due to signal 6 (use -v to see invocation)
Failed to reconstruct type for $s5Repro2P1_AA2P2px1EAaBPRts_XPD
Original type:
(existential_type
  (protocol_composition_type
    (parameterized_protocol_type
      (base=protocol_type decl="Repro.(file).P1@/code/Sources/main.swift:1:10")
      (generic_type_param_type depth=0 index=0))
    (protocol_type decl="Repro.(file).P2@/code/Sources/main.swift:5:10")))
Generic signature: <τ_0_0 where τ_0_0 : Copyable, τ_0_0 : Escapable>
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the crash backtrace.
Pass '-Xfrontend -disable-round-trip-debug-types' to disable this assertion.
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the crash backtrace.
Stack dump:
0.	Program arguments: /usr/bin/swift-frontend -frontend -c -primary-file /code/Sources/main.swift -emit-dependencies-path /code/.build/aarch64-unknown-linux-gnu/debug/Repro.build/main.d -emit-reference-dependencies-path /code/.build/aarch64-unknown-linux-gnu/debug/Repro.build/main.swiftdeps -target aarch64-unknown-linux-gnu -Xllvm -aarch64-use-tbi -disable-objc-interop -I /code/.build/aarch64-unknown-linux-gnu/debug/Modules -color-diagnostics -enable-testing -g -debug-info-format=dwarf -dwarf-version=4 -module-cache-path /code/.build/aarch64-unknown-linux-gnu/debug/ModuleCache -swift-version 6 -Onone -D SWIFT_PACKAGE -D DEBUG -entry-point-function-name Repro_main -empty-abi-descriptor -resource-dir /usr/lib/swift -enable-anonymous-context-mangled-names -file-compilation-dir /code -Xcc -fPIC -Xcc -g -Xcc -fno-omit-frame-pointer -module-name Repro -package-name code -plugin-path /usr/lib/swift/host/plugins -plugin-path /usr/local/lib/swift/host/plugins -o /code/.build/aarch64-unknown-linux-gnu/debug/Repro.build/main.swift.o -index-store-path /code/.build/aarch64-unknown-linux-gnu/debug/index/store -index-system-modules
1.	Swift version 6.0-dev (LLVM a41678ee19c803d, Swift ce381e7b159dfac)
2.	Compiling with the current language version
3.	While evaluating request IRGenRequest(IR Generation for file "/code/Sources/main.swift")
4.	While emitting IR SIL function "@$s5Repro7WrapperV7wrappedAA2P1_AA2P2px1ERts_XPvg".
 for getter for wrapped (at /code/Sources/main.swift:10:7)
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  swift-frontend  0x0000aaaab7ea9e48
1  swift-frontend  0x0000aaaab7ea7e3c
2  swift-frontend  0x0000aaaab7eaa554
3  linux-vdso.so.1 0x0000ffff943307ac __kernel_rt_sigreturn + 0
4  libc.so.6       0x0000ffff9270f200
5  libc.so.6       0x0000ffff926ca67c raise + 28
6  libc.so.6       0x0000ffff926b7130 abort + 228
7  swift-frontend  0x0000aaaab1e0ce3c
8  swift-frontend  0x0000aaaab1e0d060
9  swift-frontend  0x0000aaaab1e04f04
10 swift-frontend  0x0000aaaab1e1f2c0
11 swift-frontend  0x0000aaaab1e1e968
12 swift-frontend  0x0000aaaab1ce5678
13 swift-frontend  0x0000aaaab1ba34e0
14 swift-frontend  0x0000aaaab1bf63b0
15 swift-frontend  0x0000aaaab1baca28
16 swift-frontend  0x0000aaaab1ba56ac
17 swift-frontend  0x0000aaaab17cb5f4
18 swift-frontend  0x0000aaaab17c7b24
19 swift-frontend  0x0000aaaab17c6b14
20 swift-frontend  0x0000aaaab17d3fec
21 swift-frontend  0x0000aaaab17c947c
22 swift-frontend  0x0000aaaab17c8684
23 swift-frontend  0x0000aaaab15b68a0
24 libc.so.6       0x0000ffff926b73fc
25 libc.so.6       0x0000ffff926b74cc __libc_start_main + 152
26 swift-frontend  0x0000aaaab15b5ab0
```
```


### Expected behavior

Shouldn't crash

### Environment

Crashes on Linux:

Swift version 6.0-dev (LLVM a41678ee19c803d, Swift ce381e7b159dfac)
Target: aarch64-unknown-linux-gnu

--

_Doesn't_ crash on macOS:

swift-driver version: 1.111.2 Apple Swift version 6.0 (swiftlang-6.0.0.5.15 clang-1600.0.22.6)
Target: arm64-apple-macosx15.0


### Additional information

When the `let wrapped: Wrapped` is `private` the compilation succeeds.

**Comment by slavapestov** [comment] 2024-07-15 20:44
This is a dupe of #63877 because compositions involving parameterized existentials are not supported.

**Closed by slavapestov** 2024-07-15 20:44 UTC
Labels: bug, crash, triage needed
