### ISSUE TITLE
Unexpected build errors with `guard-case` expressions

### ISSUE THREAD

**Issue by yakovmanshin** [swiftlang/swift#76770] opened 2024-09-28 11:26 UTC
### Description

Consider the following constructions:

```swift
guard case .keyNotFound(let key, _) = error as? DecodingError else { return false }
```

```swift
guard case DecodingError.keyNotFound(let key, _) = error else { return false }
```

In normal Swift, they’re pretty much equivalent in terms of behavior.

But in Swift Testing, the first one compiles just fine, while the second one results in a `Command SwiftCompile failed with a nonzero exit code` error (not really informative).

<details>
<summary>Full snippet</summary>

```swift
@Test func decodingError() async throws {
    await #expect {
        _ = try await someAsyncThrowingFunction()
    } throws: { error in
        // Compiles fine:
        guard case .keyNotFound(let key, _) = error as? DecodingError else { return false }
        
        // OR
        
        // Build error:
        guard case DecodingError.keyNotFound(let key, _) = error else { return false }
        
        return key.stringValue == "expectedKeyName"
    }
}
```
</details>

### Swift & OS version (output of `swift --version ; uname -a`)

* Swift 6 (`swift-driver version: 1.115 Apple Swift version 6.0 (swiftlang-6.0.0.9.10 clang-1600.0.26.2)`)
* macOS 15.0 (24A335)
* Xcode 16.0 (16A242)

**Comment by grynspan** [comment] 2024-09-29 15:07
Duplicate of #76765

**Closed by grynspan** 2024-09-29 15:07 UTC
Labels: bug
