### ISSUE TITLE
Wrong tuple destructuring in property assignment when using autogenerated initalizer

### ISSUE THREAD

**Issue by Losiowaty** [swiftlang/swift#68983] opened 2023-10-05 13:54 UTC
**Description**
When you initialize multiple parameters via tuple destructuring it fails when the enclosing `struct` has other parameters without default values and no dedicated `init`. When any form of `init` is added the issue disappears.
The issue doesn't happen for `class`es since they always need a user-provided initializer.

**Steps to reproduce**
This is the smallest sample that shows the issue : 
```swift
struct Bar {
    let value: Int
    let (a, b) = ("a", "b")
}

Bar(value: 0).a  // "a"
Bar(value: 0).b //  "a" also ❌
```
The same happens for bigger tuples (like : `let (a, b, c,) = ("a", "b", "c")`, etc.) and it will always assign the first value to all properties.

Samples that DO NOT have the issue : 
```swift
// Simple, standalone assignment
let (a, b) = ("a", "b")
a  // "a"
b  // "b"

//--------------------

// `struct` that has only that parameter
struct Foo {
    let (a, b) = ("a", "b")
}
Foo().a  // "a"
Foo().b  // "b"

//--------------------

// Notice this is the same as failing sample, just with manually implemented initializer
struct Foo2 {
  let value: Int
  let (a, b) = ("a", "b")

  init(value: Int) {
    self.value = value
  }
}
Foo2(value: 0).a  // "a"
Foo2(value: 0).b  // "b"

//--------------------

struct Foo3 {
  let value: Int
  let (a, b) = ("a", "b")
}

// When calling the custom `init` the tuple will be destructured properly
// When calling the automatically generated `init` the tuple will be destructured wrongly
extension Foo3 {
  init(customValue: Int) {
    value = customValue
  }
}
Foo3(customValue: 0).a  // "a"
Foo3(customValue: 0).b  // "b"

Foo3(value: 0).a  // "a"
Foo3(value: 0).b  // "a" ❌

//--------------------

// This is almost the same as failing sample, but has default value for `value` property
// When using `Foo4()` initializer (no args) the destructuring works properly
// When using `Foo4(value: 0)` initializer the destructuring works wrongly
struct Foo4 {
  var value: Int = 0
  let (a, b) = ("a", "b")
}
Foo4().a  // "a"
Foo4().b  // "b"

Foo4(value: 0).a  // "a"
Foo4(value: 0).b  // "a" ❌
```

**Expected behavior**
Values from the tuple should be assigned properly to their respective properties in all cases.

**Environment**
- Swift compiler version info 
Fails on both : 
```
swift-driver version: 1.87.1 Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)
Target: arm64-apple-macosx13.0
------
swift-driver version: 1.75.2 Apple Swift version 5.8 (swiftlang-5.8.0.124.2 clang-1403.0.22.11.100)
Target: arm64-apple-macosx13.0
```
- Xcode version info
Fails on both : 
```
Xcode 15.0
Build version 15A240d
------
Xcode 14.3
Build version 14E222b
```
- Deployment target: macOS Ventura 13.6, iOS (not sure which version Xcode playgrounds use)

**Additional context**
For what its worth, I took a look at SIL of the smallest working / non-working structs and it seems that in the failing case the tuple is created twice and then tuple refs are passed to the "actual" initializer.
In the working case, the tuple is created once, but it's also not used - the tuple values are passed directly to the "actual" initializer.

Sorry for screenshots, I can repost as text if needed :

| Working | Failing |
|--------|--------|
|![working](https://github.com/apple/swift/assets/4209155/02ae26b4-dac9-49c2-aeb7-d86be8add178)|![failing](https://github.com/apple/swift/assets/4209155/3be9fbfb-c0fa-4d9f-811e-7bc6d04227c5)|

**Comment by xedin** [comment] 2023-10-05 15:59
Looks like a dupe of https://github.com/apple/swift/issues/68915

**Closed by xedin** 2023-10-05 15:59 UTC
Labels: bug, duplicate, compiler, SILGen, swift 5.9, unexpected behavior, struct, properties, declarations, patterns, type declarations, tuple patterns
