### ISSUE TITLE
@Observable + each T = compiler crash

### ISSUE THREAD

**Issue by mayoff** [swiftlang/swift#68937] opened 2023-10-03 16:52 UTC
**Description**

The compiler crashes if the source code applies the `@Observable` macro to a class with a value pack property.

**Steps to reproduce**

Source code:

```swift
import Observation

@available(macOS 14, iOS 17, *)
@Observable
class BindingStore<each T> {
    var state: (repeat each T)

    init(_ state: repeat each T) {
        self.state = (repeat each state)
    }
}
```

Compiler output:

```
; /Library/Developer/Toolchains/swift-latest.xctoolchain/usr/bin/swiftc -c /tmp/bug.swift
Assertion failed: (!tupleTy.containsPackExpansionType() && "can't extract elements from tuples containing pack expansions " "right now"), function extractElements, file RValue.cpp, line 705.
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the crash backtrace.
Stack dump:
0.	Program arguments: /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2023-10-02-a.xctoolchain/usr/bin/swift-frontend -frontend -c -primary-file /tmp/bug.swift -target arm64-apple-macosx13.0 -Xllvm -aarch64-use-tbi -enable-objc-interop -color-diagnostics -new-driver-path /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2023-10-02-a.xctoolchain/usr/bin/swift-driver -empty-abi-descriptor -resource-dir /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2023-10-02-a.xctoolchain/usr/lib/swift -module-name bug -plugin-path /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2023-10-02-a.xctoolchain/usr/lib/swift/host/plugins -plugin-path /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2023-10-02-a.xctoolchain/usr/local/lib/swift/host/plugins -o bug.o
1.	Apple Swift version 5.11-dev (LLVM 9be5c57af9401d5, Swift 8569c9512bc8693)
2.	Compiling with the current language version
3.	While evaluating request ASTLoweringRequest(Lowering AST to SIL for file "/tmp/bug.swift")
4.	While silgen emitFunction SIL function "@$s3bug12BindingStoreC5statexxQp_tvg".
 for getter for state (at /tmp/bug.swift:6:9)
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  swift-frontend           0x00000001073c6b08 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 56
1  swift-frontend           0x00000001073c5eac llvm::sys::RunSignalHandlers() + 112
2  swift-frontend           0x00000001073c7148 SignalHandler(int) + 304
3  libsystem_platform.dylib 0x0000000184c22a24 _sigtramp + 56
4  libsystem_pthread.dylib  0x0000000184bf3c28 pthread_kill + 288
5  libsystem_c.dylib        0x0000000184b01ae8 abort + 180
6  libsystem_c.dylib        0x0000000184b00e44 err + 0
7  swift-frontend           0x00000001074a079c swift::Lowering::RValue::extractElements(llvm::SmallVectorImpl<swift::Lowering::RValue>&) && (.cold.3) + 0
8  swift-frontend           0x0000000102add80c swift::Lowering::RValue::extractElements(llvm::SmallVectorImpl<swift::Lowering::RValue>&) && + 436
9  swift-frontend           0x0000000102b03360 (anonymous namespace)::ArgEmitter::emitExpanded(swift::Lowering::ArgumentSource&&, swift::Lowering::AbstractionPattern) + 280
10 swift-frontend           0x0000000102b01b80 (anonymous namespace)::ArgEmitter::emit(swift::Lowering::ArgumentSource&&, swift::Lowering::AbstractionPattern, llvm::Optional<swift::AnyFunctionType::Param>) + 164
11 swift-frontend           0x0000000102af464c (anonymous namespace)::ArgEmitter::emitSingleArg(swift::Lowering::ArgumentSource&&, swift::Lowering::AbstractionPattern, llvm::Optional<swift::AnyFunctionType::Param>) + 424
12 swift-frontend           0x0000000102b0142c (anonymous namespace)::ArgEmitter::emitPreparedArgs(swift::Lowering::PreparedArguments&&, swift::Lowering::AbstractionPattern) + 192
13 swift-frontend           0x0000000102b0b944 (anonymous namespace)::CallSite::emit(swift::Lowering::SILGenFunction&, swift::Lowering::AbstractionPattern, swift::CanTypeWrapper<swift::SILFunctionType>, (anonymous namespace)::ParamLowering&, llvm::SmallVectorImpl<swift::Lowering::ManagedValue>&, llvm::SmallVectorImpl<(anonymous namespace)::DelayedArgument>&, swift::ForeignInfo const&) && + 536
14 swift-frontend           0x0000000102b0b2bc (anonymous namespace)::CallEmission::emitArgumentsForNormalApply(swift::Lowering::AbstractionPattern, swift::CanTypeWrapper<swift::SILFunctionType>, swift::ForeignInfo const&, llvm::SmallVectorImpl<swift::Lowering::ManagedValue>&, llvm::Optional<swift::SILLocation>&) + 1120
15 swift-frontend           0x0000000102af7a4c (anonymous namespace)::CallEmission::apply(swift::Lowering::SGFContext) + 1384
16 swift-frontend           0x0000000102afe064 swift::Lowering::SILGenFunction::emitSetAccessor(swift::SILLocation, swift::SILDeclRef, swift::SubstitutionMap, swift::Lowering::ArgumentSource&&, bool, bool, swift::Lowering::PreparedArguments&&, swift::Lowering::ArgumentSource&&, bool) + 924
17 swift-frontend           0x0000000102b7d6c8 swift::Lowering::SILGenFunction::emitAssignToLValue(swift::SILLocation, swift::Lowering::ArgumentSource&&, swift::Lowering::LValue&&) + 1744
18 swift-frontend           0x0000000102b7cf30 swift::Lowering::SILGenFunction::emitAssignToLValue(swift::SILLocation, swift::Lowering::RValue&&, swift::Lowering::LValue&&) + 116
19 swift-frontend           0x0000000102b4a624 getOrCreateKeyPathSetter(swift::Lowering::SILGenModule&, swift::AbstractStorageDecl*, swift::SubstitutionMap, swift::GenericEnvironment*, swift::ResilienceExpansion, llvm::ArrayRef<std::__1::pair<swift::CanType, swift::SILType>>, swift::CanType, swift::CanType) + 3816
20 swift-frontend           0x0000000102b483e8 swift::Lowering::SILGenModule::emitKeyPathComponentForDecl(swift::SILLocation, swift::GenericEnvironment*, swift::ResilienceExpansion, unsigned int&, bool&, swift::SubstitutionMap, swift::AbstractStorageDecl*, llvm::ArrayRef<swift::ProtocolConformanceRef>, swift::CanType, swift::DeclContext*, bool) + 3672
21 swift-frontend           0x0000000102b5ab1c (anonymous namespace)::RValueEmitter::visitKeyPathExpr(swift::KeyPathExpr*, swift::Lowering::SGFContext) + 900
22 swift-frontend           0x0000000102b46ef8 swift::Lowering::SILGenFunction::emitRValueAsSingleValue(swift::Expr*, swift::Lowering::SGFContext) + 72
23 swift-frontend           0x0000000102b025f0 (anonymous namespace)::ArgEmitter::emit(swift::Lowering::ArgumentSource&&, swift::Lowering::AbstractionPattern, llvm::Optional<swift::AnyFunctionType::Param>) + 2836
24 swift-frontend           0x0000000102af464c (anonymous namespace)::ArgEmitter::emitSingleArg(swift::Lowering::ArgumentSource&&, swift::Lowering::AbstractionPattern, llvm::Optional<swift::AnyFunctionType::Param>) + 424
25 swift-frontend           0x0000000102b0142c (anonymous namespace)::ArgEmitter::emitPreparedArgs(swift::Lowering::PreparedArguments&&, swift::Lowering::AbstractionPattern) + 192
26 swift-frontend           0x0000000102b0b944 (anonymous namespace)::CallSite::emit(swift::Lowering::SILGenFunction&, swift::Lowering::AbstractionPattern, swift::CanTypeWrapper<swift::SILFunctionType>, (anonymous namespace)::ParamLowering&, llvm::SmallVectorImpl<swift::Lowering::ManagedValue>&, llvm::SmallVectorImpl<(anonymous namespace)::DelayedArgument>&, swift::ForeignInfo const&) && + 536
27 swift-frontend           0x0000000102b0b2bc (anonymous namespace)::CallEmission::emitArgumentsForNormalApply(swift::Lowering::AbstractionPattern, swift::CanTypeWrapper<swift::SILFunctionType>, swift::ForeignInfo const&, llvm::SmallVectorImpl<swift::Lowering::ManagedValue>&, llvm::Optional<swift::SILLocation>&) + 1120
28 swift-frontend           0x0000000102af7a4c (anonymous namespace)::CallEmission::apply(swift::Lowering::SGFContext) + 1384
29 swift-frontend           0x0000000102af6208 swift::Lowering::SILGenFunction::emitApplyExpr(swift::ApplyExpr*, swift::Lowering::SGFContext) + 1992
30 swift-frontend           0x0000000102b47318 swift::Lowering::SILGenFunction::emitIgnoredExpr(swift::Expr*) + 944
31 swift-frontend           0x0000000102bbc7e8 swift::ASTVisitor<(anonymous namespace)::StmtEmitter, void, void, void, void, void, void>::visit(swift::Stmt*) + 4364
32 swift-frontend           0x0000000102bbb6d0 swift::Lowering::SILGenFunction::emitStmt(swift::Stmt*) + 24
33 swift-frontend           0x0000000102b66a0c swift::Lowering::SILGenFunction::emitFunction(swift::FuncDecl*) + 436
34 swift-frontend           0x0000000102ae7d2c swift::Lowering::SILGenModule::emitFunctionDefinition(swift::SILDeclRef, swift::SILFunction*) + 8848
35 swift-frontend           0x0000000102ae8598 swift::Lowering::SILGenModule::emitOrDelayFunction(swift::SILDeclRef) + 204
36 swift-frontend           0x0000000102ae5a84 swift::Lowering::SILGenModule::emitFunction(swift::FuncDecl*) + 168
37 swift-frontend           0x0000000102bcbb8c (anonymous namespace)::SILGenType::visitFuncDecl(swift::FuncDecl*) + 28
38 swift-frontend           0x00000001039ad7b8 swift::AbstractStorageDecl::visitEmittedAccessors(llvm::function_ref<void (swift::AccessorDecl*)>) const + 104
39 swift-frontend           0x0000000102bcbb50 (anonymous namespace)::SILGenType::visitVarDecl(swift::VarDecl*) + 384
40 swift-frontend           0x0000000102bc8aa4 (anonymous namespace)::SILGenType::emitType() + 236
41 swift-frontend           0x0000000102bc89ac swift::Lowering::SILGenModule::visitNominalTypeDecl(swift::NominalTypeDecl*) + 24
42 swift-frontend           0x0000000102aead70 swift::ASTLoweringRequest::evaluate(swift::Evaluator&, swift::ASTLoweringDescriptor) const + 1016
43 swift-frontend           0x0000000102bbb16c swift::SimpleRequest<swift::ASTLoweringRequest, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule>> (swift::ASTLoweringDescriptor), (swift::RequestFlags)9>::evaluateRequest(swift::ASTLoweringRequest const&, swift::Evaluator&) + 148
44 swift-frontend           0x0000000102aeded4 llvm::Expected<swift::ASTLoweringRequest::OutputType> swift::Evaluator::getResultUncached<swift::ASTLoweringRequest>(swift::ASTLoweringRequest const&) + 396
45 swift-frontend           0x0000000102aeb710 swift::performASTLowering(swift::FileUnit&, swift::Lowering::TypeConverter&, swift::SILOptions const&, swift::IRGenOptions const*) + 96
46 swift-frontend           0x00000001025978dc swift::performCompileStepsPostSema(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 544
47 swift-frontend           0x00000001025a6acc withSemanticAnalysis(swift::CompilerInstance&, swift::FrontendObserver*, llvm::function_ref<bool (swift::CompilerInstance&)>, bool) + 160
48 swift-frontend           0x000000010259a458 performCompile(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 740
49 swift-frontend           0x00000001025993dc swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 2496
50 swift-frontend           0x00000001023bcdfc swift::mainEntry(int, char const**) + 2144
51 dyld                     0x000000018489bf28 start + 2236
zsh: abort      /Library/Developer/Toolchains/swift-latest.xctoolchain/usr/bin/swiftc -c 
```

**Environment**

- Swift compiler version info:
  Apple Swift version 5.11-dev (LLVM 9be5c57af9401d5, Swift 8569c9512bc8693)
  Target: arm64-apple-macosx13.0

- macOS version: 13.6 (22G120)

**Comment by AnthonyLatsis** [comment] 2024-07-18 02:42
Duplicate of #67916

**Closed by AnthonyLatsis** 2024-07-18 02:42 UTC
Labels: bug, duplicate, compiler, SILGen, generics, crash, tuples, expressions, swift macro, parameter packs, assertion failure, swift 6.0
