### ISSUE TITLE
Globally-isolated local functions aren't Sendable?

### ISSUE THREAD

**Issue by mattmassicotte** [swiftlang/swift#75799] opened 2024-08-09 10:50 UTC
### Description

I ran into a little bit of code that I **thought** I understood, but I don't. At first, I had not annotated the local function. But, annotating `localFunction` with `@MainActor` doesn't change anything at all. And that's particularly surprising because of SE-0434.

Annotating the function explicitly with `@Sendable` addresses the issues, even though I think it should not be necessary with a global actor applied.

### Reproduction

```swift
func usesFunction(_ block: @escaping @Sendable () -> Void) {
}

@MainActor
func example() {
    // ERROR: error: concurrently-executed local function 'localFunction()' must be marked as '@Sendable'
    @MainActor
    func localFunction() async {
        usesFunction {
            Task {
                // ERROR: capture of 'localFunction()' with non-sendable type '() async -> ()' in a `@Sendable` closure
                await localFunction()
            }
        }
    }
}
```

### Expected behavior

I think this code should compile error-free.

### Environment

Apple Swift version 6.0-dev (LLVM 31f0cdc6d5ff8a6, Swift aa0786cc7b3190c)
Target: arm64-apple-macosx14.0

**Comment by simanerush** [comment] 2024-08-28 16:26
This looks like a dupe of https://github.com/swiftlang/swift/issues/73562

**Comment by mattmassicotte** [comment] 2024-08-28 20:18
Yup 100%. Thank you @simanerush !

**Closed** 2024-09-04 15:50 UTC
Labels: concurrency
