### ISSUE TITLE
Crash with existential any in function context

### ISSUE THREAD

**Issue by GeorgeElsham** [swiftlang/swift#70988] opened 2024-01-18 18:59 UTC
### Description

I'm unsure what causes this bug, and I would expect it to correctly compile as valid code.

### Reproduction

```swift
protocol A<T> {
    associatedtype T
}
protocol B {}
typealias C<T> = A<T> & B

struct Foo<In, Out> {
    init(fn: (any C<In>) -> Out) {
        //
    }
}

let f = Foo<Int, Void> { _ in }
```

### Stack dump

```text
error: compile command failed due to signal 4 (use -v to see invocation)
error: fatalError
```

### Expected behavior

The given code should compile.

### Environment

swift-driver version: 1.87.3 Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)
Target: arm64-apple-macosx14.0

### Workaround 1

Replace `Out` in function with `Void`. Optionally remove the `Out` generic on `Foo`. Breaks the original intentions.

```swift
protocol A<T> {
    associatedtype T
}
protocol B {}
typealias C<T> = A<T> & B

struct Foo<In, Out> {
    init(fn: (any C<In>) -> Void) { // <- here
        //
    }
}

let f = Foo<Int, Void> { _ in }
```

### Workaround 2

Remove protocol composition. Breaks the original intentions.

```swift
protocol A<T> {
    associatedtype T
}
typealias C<T> = A<T>

struct Foo<In, Out> {
    init(fn: (any C<In>) -> Out) {
        //
    }
}

let f = Foo<Int, Void> { _ in }
```

### Workaround 3

Remove the use of `any` existential. Breaks the original intentions.

```swift
protocol A<T> {
    associatedtype T
}
protocol B {}
typealias C<T> = A<T> & B

struct Foo<In, Out> {
    init<D: C<In>>(fn: (D) -> Out) {
        //
    }
}

struct Bar {}
extension Bar: A {
    typealias T = Int
}
extension Bar: B {}

let f = Foo<Int, Void> { (_: Bar) in }
```

### Workaround 4

Move the function to a new type. Looks like the `init` may be the issue? Although inconvenient, it does _not_ break the original intentions.

```swift
protocol A<T> {
    associatedtype T
}
protocol B {}
typealias C<T> = A<T> & B

struct Bar<In, Out> {
    let fn: (any C<In>) -> Out
}

struct Foo<In, Out> {
    init(fn: Bar<In, Out>) {
        //
    }
}

let f = Foo<Int, Void>(fn: Bar { _ in })
```

**Comment by AnthonyLatsis** [comment] 2024-01-19 03:20
Revision update: 6d66211dea41ca6

**Comment by slavapestov** [comment] 2024-08-03 19:16
Dupe of https://github.com/swiftlang/swift/issues/63877

**Closed by slavapestov** 2024-08-03 19:16 UTC
Labels: bug, duplicate, compiler, SILGen, crash, parameterized protocols, existentials, protocol compositions, function types, types, swift 6.0
