### ISSUE TITLE
Swift interpreter doesn't work on Windows / poor diagnostic

### ISSUE THREAD

**Issue by dabrahams** [swiftlang/swift#70003] opened 2023-11-22 14:08 UTC
You basically [can't use the interpreter on windows](https://forums.swift.org/t/unknown-error-could-not-load-the-swift-standard-library-windows-11/61513/17) but the diagnostic says "can't load the standard library" rather than "the swift interpreter is not (yet) supported on Windows," which leads to hours of wasted effort trying to figure out what I've done wrong or what the workaround might be.  Please, in the short term, at least fix the diagnostic!

**Comment by adrian-prantl** [comment] 2023-11-27 23:05
@compnerd Assuming that @dabrahams is talking about `swift repl`, can you fill me in on what's missing for LLDB to find the standard library? That sounds like it ought to be a straightforward thing to fix, or are there dragons about?

**Comment by dabrahams** [comment] 2023-11-28 00:51
By "the interpreter" I mean what happens when you invoke `swift SomeFile.swift`

**Comment by al45tair** [comment] 2024-08-14 13:03
Yeah, that error was caused by the code that figures out where the Swift runtime is being wrong for Windows (rdar://132598892). There's an LLVM bug (rdar://133473673) that you would have hit after that, but that's fixed too (there's an upstream PR that hasn't yet merged, but it's there waiting…).

**Closed by al45tair** 2024-08-14 13:03 UTC
Labels: bug, Windows, diagnostics QoI, REPL, swift 6.0
