### ISSUE TITLE
Concurrency Compiler Error: Cannot form key path to main actor-isolated property 'xyz'.

### ISSUE THREAD

**Issue by fritzt0** [swiftlang/swift#75616] opened 2024-08-01 13:05 UTC
### Description

Trying to port an App to Swift-6, I believe the following compiler error is wrong. At least I don't see why the compiler is unable to form the requested key path in struct `MyApp `. Everything is isolated to MainActor.

error: cannot form key path to main actor-isolated property 'rebuildDatabase'

### Reproduction

```swift
@MainActor
final class AppSettings {
  var rebuildDatabase: Bool = false

  static let shared = AppSettings()
}

@MainActor
struct MyApp {
  @AppSetting(\.rebuildDatabase) private var rebuildDatabase
}

@MainActor
@propertyWrapper
struct AppSetting<Value> {
  private let keyPath: ReferenceWritableKeyPath<AppSettings, Value>
  private let preferences: AppSettings

  init(_ keyPath: ReferenceWritableKeyPath<AppSettings, Value>) {
    self.keyPath = keyPath
    self.preferences = .shared
  }

  var wrappedValue: Value {
    get { preferences[keyPath: keyPath] }
    nonmutating set { preferences[keyPath: keyPath] = newValue }
  }

  static subscript<T>(
    _enclosingInstance instance: T,
    wrapped wrappedKeyPath: ReferenceWritableKeyPath<T, Value>,
    storage storageKeyPath: ReferenceWritableKeyPath<T, Self>
  ) -> Value {
    get {
      instance[keyPath: storageKeyPath].wrappedValue
    }
    set {
      instance[keyPath: storageKeyPath].wrappedValue = newValue
    }
  }
}
```

### Expected behavior

The code should compile error-free.

### Environment

Xcode 16 beta 4

### Additional information

The example code can be pasted into an Xcode Playground to see the error.

**Comment by hborla** [comment] 2024-08-12 20:13
Duplicate of https://github.com/swiftlang/swift/issues/72181

**Closed by hborla** 2024-08-12 20:13 UTC
Labels: bug, triage needed

**Comment by hborla** [comment] 2024-08-12 20:15
I tested the example with the fix for https://github.com/swiftlang/swift/issues/72181 and it builds successfully under `-swift-version 6`.
