### ISSUE TITLE
Allows top-level variable to be used in its own initial value

### ISSUE THREAD

**Issue by brow** [swiftlang/swift#70380] opened 2023-12-11 18:34 UTC
### Description

In Swift 5.4 and later, a variable can in some cases be used in the initial value of its own declaration. Doing so produces a crash at runtime rather than a compiler error.

### Reproduction

```swift
let x: Any = x
```
Run in a Swift Playground in Xcode 15.0.1. Crashes at runtime with error:
> error: Execution was interrupted, reason: EXC_BAD_ACCESS (code=1, address=0xfffffffffffffff8).

### Expected behavior

Compiler error such as `use of variable 'x' before its declaration` or `variable used within its own initial value`.

The former is the compiler error given for `do { let x: Any = x }`.

The latter is the error [given by Swift 5.3](https://swift.godbolt.org/z/8TEMhxrhq). 

### Environment

The runtime error was produced in a Swift Playground in Xcode 15.0.1.

The lack of compiler error was reproduced in swiftc 5.9 and 5.4, but not in 5.3, using [swift.godbolt.org](https://swift.godbolt.org/).

**Comment by AnthonyLatsis** [comment] 2024-02-29 18:03
Duplicate of #70323

**Closed by AnthonyLatsis** 2024-02-29 18:03 UTC
Labels: bug, duplicate, compiler, definite initialization, accepts invalid, crash, SIL, memory safety, swift 6.0, script mode
