### ISSUE TITLE
swift repl can't work with custom toolchain

### ISSUE THREAD

**Issue by miku1958** [swiftlang/swift#64306] opened 2023-03-12 06:16 UTC
**Description**
Getting error dyld[24013]: Library not loaded: @rpath/libswiftCore.dylib when running swift repl

**Steps to reproduce**
1. Download and install toolchain from swift.org
2. Run swift repl

**Expected behavior**
Enter Swift code interactively mode

**Environment**
- Swift compiler version info
Apple Swift version 5.7.3 (swift-5.7.3-RELEASE)
Target: x86_64-apple-macosx13.0
- Xcode version info
Xcode 14.2
Build version 14C18
- Deployment target: macOS 13.2

**Comment by AnthonyLatsis** [comment] 2023-03-15 02:13
Duplicate of #58750

**Closed by AnthonyLatsis** 2023-03-15 02:13 UTC
Labels: bug, duplicate, toolchain, REPL, swift 5.9, unexpected error
