### ISSUE TITLE
Segfault on wrong top-level variable declaration order

### ISSUE THREAD

**Issue by lukaszdebowski** [swiftlang/swift#70356] opened 2023-12-09 19:42 UTC
### Description

Best to look at a reproduction code. 
Basically the playground app error out with `Terminated by signal 11` depending on the order of declaration of top-level variables. 

I'm new to swift, sorry if this is the expected behaviour (I did not find any information about it in the swift.org docs though)

### Reproduction

Below code fails with `Terminated by signal 11`

```swift
myFunction()
var myMap = ["key": "value"]
func myFunction() {
    print(myMap["key"])
}
```

And the below code works just fine

```swift
var myMap = ["key": "value"]
myFunction()
func myFunction() {
    print(myMap["key"])
}
```

### Stack dump

```text
Terminated by signal 11

In Xcode playground I get 
`error: Execution was interrupted, reason: EXC_BAD_ACCESS (code=1, address=0x10)`
```

### Expected behavior

I would expect that top-level declarations' order does not matter, and both code snippets would work 
OR that the compiler returns an error message along the lines of "myMap is used before declaration" or similar

### Environment

I'm using https://online.swiftplayground.run/ with version 5.7-release or Xcode 15 playground

**Comment by etcwilde** [comment] 2024-03-22 18:01
Thanks for reporting.
It's an unfortunate bug that I've been meaning to get to one of these years. I talked about it a bit on the forums: https://forums.swift.org/t/on-the-behavior-of-variables-in-top-level-code/52230

**Comment by AnthonyLatsis** [comment] 2024-03-23 09:37
Duplicate of #70356

**Comment by atrick** [comment] 2024-04-24 16:07
Not sure why this was closed. It's an ongoing problem with an obvious solution.

**Comment by AnthonyLatsis** [comment] 2024-04-24 18:31
Ah, thanks. I meant to mark this as a dupe of #70323, not itself. Though, if you want this to be standalone, I can gather these "no use before declaration error in top-level code" issues under an umbrella issue instead.

**Comment by atrick** [comment] 2024-04-24 20:51
I think I'll create a separate umbrella for the main feature of fixing the many problems with top-level code as a single language change. These individual bugs don't get enough attention, and the feature doesn't get any attention without linking it to real problems.

**Closed** 2024-04-24 20:51 UTC
Labels: bug, duplicate, compiler, definite initialization, accepts invalid, crash, SIL, memory safety, swift 6.0
