### ISSUE TITLE
Runtime crash casting optional parameterized protocol types to protocol type without parameter

### ISSUE THREAD

**Issue by Ashton-W** [swiftlang/swift#62022] opened 2022-11-10 07:08 UTC
**Describe the bug**
Casting an optional existential parameterized protocol type to the same type but without the parameter crashes at runtime (is this the correct way to describe using `as? any Identifiable` on a value of type `(any Identifiable<String>)?`?)

**Steps To Reproduce**
```swift
struct Thing: Identifiable {
    let id = "thing"
}

let thing: (any Identifiable<String>)? = Thing()

_ = thing
_ = thing as? any Identifiable
```

The last line does generate a warning:
`Conditional downcast from '(any Identifiable<String>)?' to 'any Identifiable' is equivalent to an implicit conversion to an optional 'any Identifiable'`

But crashes at runtime with the error:
```
Thread 1: EXC_BAD_ACCESS (code=1, address=0x0)
#0	0x00000001346f6154 in tryCast(swift::OpaqueValue*, swift::TargetMetadata<swift::InProcess> const*, swift::OpaqueValue*, swift::TargetMetadata<swift::InProcess> const*, swift::TargetMetadata<swift::InProcess> const*&, swift::TargetMetadata<swift::InProcess> const*&, bool, bool) ()
#1	0x00000001346f5fec in swift_dynamicCast ()
```

**Expected behavior**
A compile error along the lines of `Runtime support for parameterized protocol types is only available in iOS 16.0.0 or newer` or the code to run without crashing.

**Environment (please fill out the following information)**
 - OS: macOS 13.0 (22A380), iOS Simulator 14.0.1, iOS Simulator 15.5
 - Xcode Version/Tag/Branch: Xcode Version 14.1 (14B47b)

**Additional context**
*Why would you want to do this?* This is a minimal reproduction from real production code trying to test working code that uses existential any with protocols with primary associated types that have type constraints, consider this expanded example:
```swift
if thing == nil {
    XCTFail()
}
```
This fails to compile with the familiar error: `Runtime support for parameterized protocol types is only available in iOS 16.0.0 or newer`

Instead, this compiles, but crashes
```swift
if (thing as? any Identifiable) == nil {
    XCTFail()
}
```

**Comment by AnthonyLatsis** [comment] 2022-11-10 17:48
Is seems to me we should be diagnosing `let thing: (any Identifiable<String>)?` instead, not `thing == nil`. The reason it gets diagnosed is that `nil` is type-checked into `Optional<any Identifiable<String>>.none` (an implicit expression containing a reference to a parameterized protocol type).

**Comment by AnthonyLatsis** [comment] 2022-11-10 20:40
Duplicate of #60743

**Closed by AnthonyLatsis** 2022-11-10 20:40 UTC
Labels: compiler, type checker, run-time crash, crash, availability, parameterized protocols, casting, existentials, swift 5.7

**Comment by ashton-seek** [comment] 2022-11-10 21:44
> Is seems to me we should be diagnosing `let thing: (any Identifiable<String>)?`, not `thing == nil`. […]

Are you saying there should be an error on
```swift
let thing: (any Identifiable<String>)? = Thing()
```
It appears to work for most things, like assigning a conforming type (if it was var), making it weak, and even calling methods with optional chaining. 

I was also confused that this works as an alternative nil check:
```swift
if let t = thing { }
```

**Comment by Ashton-W** [comment] 2022-11-10 21:46
> Is seems to me we should be diagnosing `let thing: (any Identifiable<String>)?`, not `thing == nil`. […]

Are you saying there should be an error on
```swift
let thing: (any Identifiable<String>)? = Thing()
```
It appears to work for most things, like assigning a conforming type (if it was var), making it weak, and even calling methods with optional chaining. 

I was also confused that this works as an alternative nil check:
```swift
if let t = thing { }
```

**Comment by AnthonyLatsis** [comment] 2022-11-10 22:09
@slavapestov would know more, but basically older runtimes have no idea what a parameterized protocol type is, so using them in code that ships to older OSs without availability checks is generally unsound. Even if there are ways to use them without hitting the runtime, this bug is most likely an oversight rather than a byproduct of such analysis.
