### ISSUE TITLE
Compiler error when using `#expect(try …)` macro inside throwing closure

### ISSUE THREAD

**Issue by hydrixos** [swiftlang/swift#75858] opened 2024-08-13 07:07 UTC
### Description

When using an `#expect` macro within a throwing closure, compilation fails with "Errors thrown from here are not handled".

```swift
import Testing

class Foo {
	init() {
	}
	
	func doSomething() throws -> Bool {
		throw TestError("Error")
	}
}

struct FooTest {
	@Test func throwingClosure() async throws {
		let foo = Foo()
		
		try Self.perform {
			#expect(try foo.doSomething())
		}
	}
	
	static func perform(_ block: () throws -> Void) throws {
		try block()
	}
}
```

The reported error message is:

```
error: errors thrown from here are not handled
Testing.__checkValue(try foo.doSomething(), expression: .__fromSyntaxNode("try foo.doSomething()"), comments: [], isRequired: false, sourceLocation: Testing.SourceLocation.__here()).__expected()
                     ^
note: in expansion of macro 'expect' here
                        #expect(try foo.doSomething())
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
note: in expansion of macro 'expect' here
                        #expect(try foo.doSomething())
```

The expanded macro looks like this:

```
Testing.__checkValue(try foo.doSomething(), expression: .__fromSyntaxNode("try foo.doSomething()"), comments: [], isRequired: false, sourceLocation: Testing.SourceLocation.__here()).__expected()
```

The same happens:

- if `perform` is declared as `rethrows`
- when using a closure variable of type `() throws -> Void` and calling the closure directly.

It doesn't happen, if `#expect` is used within a throwing function body.

### Expected behavior

According to this compiler bug report, it seems to be expected behavior of the Swift compiler:

https://github.com/swiftlang/swift/issues/67102

But it feels quite counter-intuitive, because using an `#expect` macro within a throwing function is no problem. Probably it should either also work within throwing closures. Otherwise the provided error message or at least documentation should clarify it.

Thanks!

### Actual behavior

Compilation fails with an error "Errors thrown from here are not handled".

### swift-testing version/commit hash

Xcode Version 16.0 beta 5 (16A5221g)

### Swift & OS version (output of `swift --version ; uname -a`)

`swiftc --version`
swift-driver version: 1.113 Apple Swift version 6.0 (swiftlang-6.0.0.7.6 clang-1600.0.24.1)
Target: arm64-apple-macosx15.0

`Darwin frieder 24.0.0 Darwin Kernel Version 24.0.0: Wed Jul 31 21:50:55 PDT 2024; root:xnu-11215.0.199.501.2~1/RELEASE_ARM64_T6020 arm64`

**Comment by grynspan** [comment] 2024-08-13 14:35
Duplicate of #75256

**Closed** 2024-08-13 14:35 UTC
Labels: bug
