### ISSUE TITLE
Crash when accessing mutable associatedtype protocol variable

### ISSUE THREAD

**Issue by shivatinker** [swiftlang/swift#77846] opened 2024-11-26 17:48 UTC
### Description

This code crashes the compiler. I have tried to simplify it as I could.

### Reproduction

```swift
protocol A {
    associatedtype F
    
    var f: F { get set }
}

func k(a: inout any A) {
    a.f
}
```

### Stack dump

```text
Unhandled coercion:
(opened_archetype_type address=0x1498a7e80 conforms_to="Swift.(file).Copyable" conforms_to="Swift.(file).Escapable" opened_existential_id="882E3CB0-AC1E-11EF-90FB-C6CA1299A60D"
  (interface_type=dependent_member_type assoc_type="main.(file).A.F@main.swift:9:20"
    (base=generic_type_param_type depth=0 index=0))
  (opened_existential=existential_type
    (protocol_type decl="main.(file).A@main.swift:8:10")))
(lvalue_type
  (existential_type
    (protocol_composition_type)))
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the crash backtrace.
Stack dump:
0.	Program arguments: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-frontend -frontend -c -primary-file main.swift -target arm64-apple-macosx15.0 -Xllvm -aarch64-use-tbi -enable-objc-interop -stack-check -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.1.sdk -color-diagnostics -new-driver-path /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-driver -empty-abi-descriptor -resource-dir /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift -module-name main -disable-clang-spi -target-sdk-version 15.1 -target-sdk-name macosx15.1 -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib/swift/host/plugins#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/local/lib/swift/host/plugins#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin/swift-plugin-server -plugin-path /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/host/plugins -plugin-path /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/local/lib/swift/host/plugins -o /var/folders/0t/0y63z9z90ylfclj7xblp9b7h0000gn/T/TemporaryDirectory.SXsOQC/main-1.o
1.	Apple Swift version 6.0.2 (swiftlang-6.0.2.1.2 clang-1600.0.26.4)
2.	Compiling with effective version 5.10
3.	While evaluating request TypeCheckSourceFileRequest(source_file "main.swift")
4.	While evaluating request TypeCheckFunctionBodyRequest(main.(file).k(a:)@main.swift:14:6)
5.	While type-checking statement at [main.swift:14:24 - line:16:1] RangeText="{
    a.f
"
6.	While type-checking expression at [main.swift:15:5 - line:15:7] RangeText="a."
7.	While type-checking-target starting at main.swift:15:7
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  swift-frontend           0x000000010662a9ac llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 56
1  swift-frontend           0x0000000106628c00 llvm::sys::RunSignalHandlers() + 112
2  swift-frontend           0x000000010662af78 SignalHandler(int) + 292
3  libsystem_platform.dylib 0x000000018d7cae04 _sigtramp + 56
4  libsystem_pthread.dylib  0x000000018d793f70 pthread_kill + 288
5  libsystem_c.dylib        0x000000018d6a0908 abort + 128
6  swift-frontend           0x00000001020966bc (anonymous namespace)::ExprRewriter::coerceToType(swift::Expr*, swift::Type, swift::constraints::ConstraintLocatorBuilder) + 10492
7  swift-frontend           0x000000010209575c (anonymous namespace)::ExprRewriter::coerceToType(swift::Expr*, swift::Type, swift::constraints::ConstraintLocatorBuilder) + 6556
8  swift-frontend           0x00000001020b5a84 (anonymous namespace)::ExprRewriter::closeExistential(swift::Expr*&, swift::constraints::ConstraintLocatorBuilder, bool) + 596
9  swift-frontend           0x00000001020ae6c8 (anonymous namespace)::ExprRewriter::buildMemberRef(swift::Expr*, swift::SourceLoc, swift::constraints::SelectedOverload, swift::DeclNameLoc, swift::constraints::ConstraintLocatorBuilder, swift::constraints::ConstraintLocatorBuilder, bool, swift::AccessSemantics) + 9320
10 swift-frontend           0x00000001020a0468 (anonymous namespace)::ExprRewriter::walkToExprPost(swift::Expr*) + 21120
11 swift-frontend           0x0000000102097c14 (anonymous namespace)::ExprWalker::walkToExprPost(swift::Expr*) + 24
12 swift-frontend           0x00000001020923f0 (anonymous namespace)::ExprWalker::rewriteTarget(swift::constraints::SyntacticElementTarget) + 2748
13 swift-frontend           0x0000000102091470 swift::constraints::ConstraintSystem::applySolution(swift::constraints::Solution&, swift::constraints::SyntacticElementTarget) + 7120
14 swift-frontend           0x0000000102350c58 swift::TypeChecker::typeCheckTarget(swift::constraints::SyntacticElementTarget&, swift::optionset::OptionSet<swift::TypeCheckExprFlags, unsigned int>) + 680
15 swift-frontend           0x000000010235088c swift::TypeChecker::typeCheckExpression(swift::constraints::SyntacticElementTarget&, swift::optionset::OptionSet<swift::TypeCheckExprFlags, unsigned int>) + 416
16 swift-frontend           0x000000010243b960 (anonymous namespace)::StmtChecker::typeCheckASTNode(swift::ASTNode&) + 332
17 swift-frontend           0x0000000102440f2c swift::ASTVisitor<(anonymous namespace)::StmtChecker, void, swift::Stmt*, void, void, void, void>::visit(swift::Stmt*) + 288
18 swift-frontend           0x000000010243e86c bool (anonymous namespace)::StmtChecker::typeCheckStmt<swift::BraceStmt>(swift::BraceStmt*&) + 316
19 swift-frontend           0x000000010243d408 swift::TypeCheckFunctionBodyRequest::evaluate(swift::Evaluator&, swift::AbstractFunctionDecl*) const + 1512
20 swift-frontend           0x000000010284dfd4 swift::TypeCheckFunctionBodyRequest::OutputType swift::Evaluator::getResultUncached<swift::TypeCheckFunctionBodyRequest, swift::TypeCheckFunctionBodyRequest::OutputType swift::evaluateOrDefault<swift::TypeCheckFunctionBodyRequest>(swift::Evaluator&, swift::TypeCheckFunctionBodyRequest, swift::TypeCheckFunctionBodyRequest::OutputType)::'lambda'()>(swift::TypeCheckFunctionBodyRequest const&, swift::TypeCheckFunctionBodyRequest::OutputType swift::evaluateOrDefault<swift::TypeCheckFunctionBodyRequest>(swift::Evaluator&, swift::TypeCheckFunctionBodyRequest, swift::TypeCheckFunctionBodyRequest::OutputType)::'lambda'()) + 636
21 swift-frontend           0x00000001027bcb44 swift::AbstractFunctionDecl::getTypecheckedBody() const + 160
22 swift-frontend           0x000000010248b3dc swift::TypeCheckSourceFileRequest::evaluate(swift::Evaluator&, swift::SourceFile*) const + 868
23 swift-frontend           0x0000000102492970 swift::TypeCheckSourceFileRequest::OutputType swift::Evaluator::getResultUncached<swift::TypeCheckSourceFileRequest, swift::TypeCheckSourceFileRequest::OutputType swift::evaluateOrDefault<swift::TypeCheckSourceFileRequest>(swift::Evaluator&, swift::TypeCheckSourceFileRequest, swift::TypeCheckSourceFileRequest::OutputType)::'lambda'()>(swift::TypeCheckSourceFileRequest const&, swift::TypeCheckSourceFileRequest::OutputType swift::evaluateOrDefault<swift::TypeCheckSourceFileRequest>(swift::Evaluator&, swift::TypeCheckSourceFileRequest, swift::TypeCheckSourceFileRequest::OutputType)::'lambda'()) + 620
24 swift-frontend           0x000000010248b05c swift::performTypeChecking(swift::SourceFile&) + 328
25 swift-frontend           0x00000001013a8ce0 swift::CompilerInstance::performSema() + 260
26 swift-frontend           0x0000000100fd60dc performCompile(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 1532
27 swift-frontend           0x0000000100fd4ea0 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 3572
28 swift-frontend           0x0000000100f5bf64 swift::mainEntry(int, char const**) + 3680
29 dyld                     0x000000018d414274 start + 2840
```

### Expected behavior

This code should compile just fine

### Environment

swift-driver version: 1.115 Apple Swift version 6.0.2 (swiftlang-6.0.2.1.2 clang-1600.0.26.4)
Target: arm64-apple-macosx15.0

**Comment by AnthonyLatsis** [comment] 2024-11-27 10:09
Duplicate of #62219

**Closed by AnthonyLatsis** 2024-11-27 10:09 UTC
Labels: bug, duplicate, compiler, type checker, crash, existentials, expressions, existential member accesses, types, assertion failure, swift 6.1
