### ISSUE TITLE
unexpected exclusivity violation from `withUnsafeBufferPointer` 

### ISSUE THREAD

**Issue by tayloraswift** [swiftlang/swift#75312] opened 2024-07-17 21:52 UTC
### Description

this compiler error self-identifies as a compiler bug. i first encountered it in the `swift-6.0-DEVELOPMENT-SNAPSHOT-2024-07-15-a` toolchain, but it also reproduces on [SwiftFiddle](https://swiftfiddle.com/?c=H4sIAAAAAAAAA0WOwQrCMBBEfyXkVEE9l55EUOhNKD1ZkRiSdiHdwGajSMi%2Fm9KCc5x5M0ySWjYyMEXNohswDSiKTjGolzNX8nOLDtCsNiBwFdnWjfYY4gw4invfIteP3Ups%2FUULd%2FwATz0GZc05Wmvo5gHZkEjiWdZE%2FuNWsXIXIk%2FVtlXCLPfyXQ4ijBO772FWgDL%2FAMSVv0y1AAAA)

```
error: 'utf8' has an unexpected exclusivity violation. This is a compiler bug. Please file a bug with a small example of the bug
```

### Reproduction

```swift
struct S
{
    @usableFromInline
    init(utf8:consuming [UInt8])
    {
        utf8.withUnsafeBufferPointer { _ in }
        fatalError()
    }
}
```

### Expected behavior

?

### Environment

Swift version 6.0-dev (LLVM a41678ee19c803d, Swift 97ef6739c064b9a)
Target: x86_64-unknown-linux-gnu

**Comment by kavon** [comment] 2024-07-18 19:59
Thanks for the report! Looks like it's caused by the `consuming` on the parameter. Ownership is the right category for this issue.

**Comment by nate-chandler** [comment] 2024-07-23 13:56
Fixed by https://github.com/swiftlang/swift/pull/75404 .

**Closed by nate-chandler** 2024-07-23 13:56 UTC
Labels: bug, compiler, SIL, access exclusivity, ownership, unexpected error, swift 6.0, internal error
