### ISSUE TITLE
Calling a function for each element of an array of mixed elements conforming to a same protocol

### ISSUE THREAD

**Issue by LyricApps** [swiftlang/swift#67198] opened 2023-07-10 15:14 UTC
**Description**
I am trying to call a function for each element of an array of mixed elements conforming to a same protocol.

Please consider the following code, the export and exportA compile fine but as soon as I add a requirement that Database inherits from a class then exportB won't compile.

```swift
protocol DatabaseExporter<Database> {
	associatedtype Database
	
	func export(database: Database)
}

func export<Database>(database: Database, usingExporters exporters: [any DatabaseExporter<Database>]) {
	for exporter in exporters {
		exporter.export(database: database)
	}
}

protocol A {}

func exportA<Database: A>(database: Database, usingExporters exporters: [any DatabaseExporter<Database>]) {
	for exporter in exporters {
		exporter.export(database: database)
	}
}

class B {}

func exportB<Database: B>(database: Database, usingExporters exporters: [any DatabaseExporter<Database>]) {
	for exporter in exporters {
		exporter.export(database: database) /// Error : Member 'export' cannot be used on value of type 'any DatabaseExporter<Database>'; consider using a generic constraint instead
		exportB(database: database, usingExporter: exporter) /// Error : Global function 'exportB(database:usingExporter:)' requires that 'Database' inherit from 'B'
	}
}

func exportB<Database: B>(database: Database, usingExporter exporter: some DatabaseExporter<Database>) {
	exporter.export(database: database)
}
```

**Steps to reproduce**
Try to compile the code above. 

**Expected behavior**
It should compile.

**Environment**
- swift-driver version: 1.75.2 Apple Swift version 5.8.1 (swiftlang-5.8.0.124.5 clang-1403.0.22.11.100)
Target: arm64-apple-macosx13.0
- Xcode 14.3.1
Build version 14E300c

**Comment by AnthonyLatsis** [comment] 2023-07-10 23:02
Duplicate of #66794

**Closed** 2023-07-10 23:02 UTC
Labels: bug, duplicate, compiler, type checker, parameterized protocols, existentials, constrained existentials, swift 5.9, implicit existential opening, existential member accesses
