### ISSUE TITLE
Compiler allows to use variable before its declaration

### ISSUE THREAD

**Issue by vojtarylko** [swiftlang/swift#71974] opened 2024-02-29 10:48 UTC
### Description

Compiler allows to use variable before its declaration, and there are no runtime errors – just unspecified behaviour. 

This happens only in top-level source files, not in other scopes (functions, blocks, ...).

### Reproduction

```swift
print(a)  // Outputs "0" or "45" 

let a = 45
```

Program compiles, and outputs "0" or "45" (when compiled with `-O`) when ran.

### Expected behavior

Compiler rejects program with error like `error: use of variable 'a' before its declaration`

### Environment

1.87.3 Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)

Happens also on 5.8, 5.7 and 5.10-nightly

### Additional information

I guess this relates to
- https://github.com/apple/swift/issues/70908
- https://github.com/apple/swift/issues/70380

**Comment by AnthonyLatsis** [comment] 2024-02-29 18:07
Thank you for the refs! I am going to fold these into the oldest duplicate I know of.

Duplicate of #70323

**Closed by AnthonyLatsis** 2024-02-29 18:07 UTC
Labels: bug, duplicate, compiler, definite initialization, accepts invalid, SIL, memory safety, swift 6.0, script mode
