### ISSUE TITLE
Protocol conformance OS availability and synthesised implementation diagnostics

### ISSUE THREAD

**Issue by andrews05** [swiftlang/swift#77821] opened 2024-11-24 05:37 UTC
### Description

The conformance of `NSPoint` to `Hashable` is only available in macOS 15 and later. Compiling in Swift 5 mode with a lower deployment target will emit a warning about this and sure enough the program will crash on an older system.
However, creating a wrapper struct with a synthesised conformance to `Hashable` will happily compile without warning, yet still crash on an older system.

### Reproduction

The following code emits an appropriate warning:
```swift
let pointMap = [NSPoint(): 0] // ⚠️ Conformance of 'CGPoint' to 'Hashable' is only available in macOS 15.0 or newer; this is an error in the Swift 6 language mode
```
The following extension creates a wrapper with synthesised conformance that emits no warning:
```swift
extension NSPoint {
    struct Hash: Hashable {
        let point: NSPoint
    }
    var hashable: Hash { .init(point: self) }
}

let pointMap = [NSPoint().hashable: 0] // 💥 Compiles fine, but crashes on an older system
```
An implementation of the `hash(into:)` function is required to actually work correctly:
```swift
extension NSPoint {
    struct Hash: Hashable {
        let point: NSPoint
        func hash(into hasher: inout Hasher) {
            point.hash(into: &hasher)
        }
    }
    var hashable: Hash { .init(point: self) }
}

let pointMap = [NSPoint().hashable: 0] // ✅
```

### Expected behavior

In the second case, a warning or error should be emitted similar to the first one.

### Environment

swift-driver version: 1.115 Apple Swift version 6.0.2 (swiftlang-6.0.2.1.2 clang-1600.0.26.4)
Target: arm64-apple-macosx15.0

**Comment by tshortli** [comment] 2024-11-26 18:36
Duplicate of https://github.com/swiftlang/swift/issues/77589.

**Closed by tshortli** 2024-11-26 18:36 UTC
Labels: bug, triage needed
