### ISSUE TITLE
`Cannot convert return expression of type '()' to return type '...'` when using guard

### ISSUE THREAD

**Issue by mozeryansky** [swiftlang/swift#63137] opened 2023-01-20 20:20 UTC
**Description**
Compiler failed with an error and didn't provide location information (file, line, column). The error appears 20+ times in the xcode build logs, on many files, but it was only because of 1 file. There was no error in the Issue Navigator, only the build logs.

**Steps to reproduce**
This was while using combine, but the issue I believe is with the swift type system. 

The use was:
```swift
struct Item {}
struct Record {}

myDictionaryPublisher // [Int: Item]
    .compactMap({ $0[itemIndex] })
    .map { [weak self] item -> [Record] in
        guard let self else { return }
        return self.createRecords(with: item)
    }
    .assign(to: &$records)
```
And the error was:
`<unknown>:0: error: cannot convert return expression of type '()' to return type '[Record]'` 
Except it wasn't on any line, and in the build logs showed on 20+ files.

Commenting out `.assign(...` changed the compiler to only show 1 error:
`Unexpected non-void return value in void function`
However, this was on the line `return self.createRecords(with: item)`

But the real issue was the guard needed to return:
`guard let self else { return [] }`

**Expected behavior**
Error appears on the file, line, column in Xcode (and in the build logs)

**Environment**
swift-driver version: 1.62.15 Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)
Target: arm64-apple-macosx13.0

Xcode 14.2
Build version 14C18

Deployment target: iOS 14

**Comment by LucianoPAlmeida** [comment] 2023-01-20 21:41
I think this was fixed by https://github.com/apple/swift/pull/59982 
Can you verify in the latest master snapshot and close? Thanks

**Comment by AnthonyLatsis** [comment] 2023-01-21 03:12
> Can you verify in the latest master snapshot and close? Thanks

Or, we’d be happy to verify it for you if granted a self-contained test case 😉

**Comment by NutsCraker** [comment] 2023-06-01 10:28
Thank you! faced the same problem, and you info helps a lot!

**Comment by AnthonyLatsis** [comment] 2023-06-02 14:32
Duplicate of #59716

**Closed by AnthonyLatsis** 2023-06-02 14:32 UTC
Labels: compiler, diagnostics QoI, type checker, closures, swift 5.7, multi-statement closures
