### ISSUE TITLE
Switch expression results cannot be assigned to `self`.

### ISSUE THREAD

**Issue by JessyCatterwaul** [swiftlang/swift#66489] opened 2023-06-09 09:09 UTC
Compiles:

```swift
func ƒ<Value>(value: Value) -> Value {
  switch value {
  case let value: value
  }
}
```

Does not compile:

```swift
extension Bool { // Type doesn't matter, though `Never` will crash the compiler.
  init(value: Self) {
    self = switch value {
    case let value: value // This will compile with a warning, but assign the argument, not the bound value.
    case let v: v // Cannot find 'v' in scope
    }
  }
}
```

Wrapping in a closure is a solution:

```swift
extension Bool {
  init(value: Self) {
    self = { switch value {
    case let value: value
    } } ()
  }
}
```

**Comment by hamishknight** [comment] 2023-06-09 09:54
Duplicate of #66412, filed #66490 to track the `Never` crash

**Closed by hamishknight** 2023-06-09 09:54 UTC
Labels: bug, duplicate, compiler, type checker, switch, expressions, swift 5.9, unexpected error, assignments
