### ISSUE TITLE
[5.8] build for Xcode has missing llvm_gtest, llvm_gtest_main in llvm build directory.

### ISSUE THREAD

**Issue by oozoofrog** [swiftlang/swift#63260] opened 2023-01-27 11:34 UTC
**Description**
release/5.8 branch has improvement for Xcode generation build. target setting in build script changed to ZERO_CHECK for llvm. as a result, build with the --xcode option, it will not create llvm_gtest and llvm_gtest_main in the llvm build. so, build target *Tests in Xcode swift project linker failed.

**Steps to reproduce**
`$ utils/build-script ... --xcode`

**Expected behavior**
build library result should have like below:
build/Xcode-{Variant}Assert/llvm-{platform}-{architecture}/{Variant}/lib/libllvm_gtest.a
build/Xcode-{Variant}Assert/llvm-{platform}-{architecture}/{Variant}/lib/libllvm_gtest_main.a

but files doesn't exist there.

**Environment**
- Swift 5.7.2
- Xcode 14.2

**Comment by AnthonyLatsis** [comment] 2023-01-27 12:31
I assume this is to *build* a target in Xcode? We no longer support building the project with Xcode because it has proven to be very unstable. The `--xcode` flag is for *generating* Xcode projects for editing only. Please consider integrating with Ninja to build & debug in Xcode. You can find the instructions [here](https://github.com/apple/swift/blob/main/docs/HowToGuides/GettingStarted.md).

**Comment by oozoofrog** [comment] 2023-01-27 13:01
@AnthonyLatsis thank you, i'm already using well. in my case, using test targets in Xcode project for researching purpose. currently i'm beginner for swift compiler. my routine is  switching release, clean projects, debugging test targets with xcode. workspace is cool but little heavy to me.
i think it would be better for me to think about how to organize a project more comfortably and add it later.

**Comment by AnthonyLatsis** [comment] 2023-01-27 14:02
> additionaly, *Test target builds still needs gtest/gtest_main in llvm build run in debug in xcode with ninja.

The Ninja build will have everything you need to build and run these targets, but you will have to create new Xcode targets for them manually if you want to do this in Xcode, and not the command line. We do not rely on the targets that are automatically generated together with the Xcode project to build stuff.

**Comment by oozoofrog** [comment] 2023-01-27 14:12
@AnthonyLatsis i clearly understand it. certainly, ninja has everything for build.

**Comment by oozoofrog** [comment] 2023-01-27 14:29
@AnthonyLatsis can we make some scripts for ninja+xcode workspace to automatically creating? is it possible?

**Comment by AnthonyLatsis** [comment] 2023-01-27 14:29
Just so we’re on the same page: Do I understand correctly that you would like to build and run the C++ unit tests (such as `SwiftASTTests`) in Xcode, but you do not want to manually create Xcode targets for them, as we suggest in the instructions?

**Comment by AnthonyLatsis** [comment] 2023-01-27 14:38
> can we make some scripts for ninja+xcode workspace to automatically creating? is it possible?

This is [among our goals](https://github.com/apple/swift/issues/60746), but it is a stretch goal — from what I’ve heard, automating the workspace creation with targets and all is a deep rabbit hole.

**Comment by oozoofrog** [comment] 2023-01-27 14:39
@AnthonyLatsis my answer was yes at first. but now, i'm not sure of it. xcode project unstable, i understand. xcode project have test targets without gtest/gtest_main, some pain. workspace is cool method, samely. if we can rely on ninja's llvm build for running xcode  test target build, i want researching automate it.

**Comment by oozoofrog** [comment] 2023-01-27 14:50
@AnthonyLatsis i close this #63236. and will focus to using ninja for building test targets.

**Comment by AnthonyLatsis** [comment] 2023-01-27 14:52
You are welcome to ask for guidance if you need help! 
___
Do you mind if I close this issue as a duplicate of #60746?

**Comment by oozoofrog** [comment] 2023-01-27 14:54
@AnthonyLatsis sure~

**Closed** 2023-01-27 14:57 UTC
Labels: build-script, generated Xcode project, utils
