### ISSUE TITLE
Type of a for loop element isn’t captured

### ISSUE THREAD

**Issue by hadiidbouk** [swiftlang/swift#62002] opened 2022-11-09 11:13 UTC
**Describe the bug**

The type of an element isn't captured using `for-in` loop compared to `ForEach`

**Steps To Reproduce**
Available in the screenshot

**Expected behavior**
I am expecting that `stuff` inside the `for-in` loop to be of type `Stuff` instead of `Any`.

**Screenshots**
![7571da82c5c95d28400e33948f539134753839ad_2_690x187](https://user-images.githubusercontent.com/19314956/200815277-3c255978-e3f6-43ed-b09d-f5690c7f979e.png)

**Environment (please fill out the following information)**
 - OS: macOS 12.6
 - Xcode Version 14.0.1 

**Additional context**
https://forums.swift.org/t/type-of-a-for-loop-element-isnt-captured/61235

**Comment by AnthonyLatsis** [comment] 2022-11-10 02:56
Duplicate of #61953

**Closed by AnthonyLatsis** 2022-11-10 02:56 UTC
Labels: compiler, type checker, type inference, existentials, constrained existentials, for-in loops, swift 5.7, unexpected error, statements
