### ISSUE TITLE
Compiler Crash (type checker) while trying to create an object using a parameter of an existential type

### ISSUE THREAD

**Issue by arteem75** [swiftlang/swift#71190] opened 2024-01-26 20:54 UTC
### Description

I try to create an array object by calling a constructor with a parameter of type any Sequence and experience a compiler crash in the type checker.  This is the error code

```
error: compile command failed due to signal 6 (use -v to see invocation)
Unhandled coercion:
(existential_type
  (protocol_composition_type))
(opened_archetype_type address=0x135302c40
  (interface_type=dependent_member_type assoc_type=Swift.(file).Sequence.Element
    (base=generic_type_param_type depth=0 index=0))
  (opened_existential=existential_type
    (protocol_type decl=Swift.(file).Sequence)) opened_existential_id=9081A498-BC8B-11EE-84C8-B2CB4EA04044)
```

### Reproduction

```swift
let oneTwoThree: any Sequence = 1...3 
let arrayInt = Array(oneTwoThree)

```

### Stack dump

```text
0  swift-frontend           0x000000010390dabc llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 56
1  swift-frontend           0x0000000106573cb0 llvm::sys::RunSignalHandlers() + 112
2  swift-frontend           0x00000001062dd054 SignalHandler(int) + 352
3  libsystem_platform.dylib 0x00000001852eba24 _sigtramp + 56
4  libsystem_pthread.dylib  0x00000001852bccc0 pthread_kill + 288
5  libsystem_c.dylib        0x00000001851cca40 abort + 180
6  swift-frontend           0x0000000104fa249c (anonymous namespace)::ExprRewriter::coerceToType(swift::Expr*, swift::Type, swift::constraints::ConstraintLocatorBuilder) + 9076
7  swift-frontend           0x000000010502bab0 buildOpaqueElementConversion((anonymous namespace)::ExprRewriter&, swift::SourceRange, swift::Type, swift::Type, bool, swift::constraints::ConstraintLocatorBuilder, unsigned int) + 608
8  swift-frontend           0x0000000102ed5004 (anonymous namespace)::ExprRewriter::buildCollectionUpcastExpr(swift::Expr*, swift::Type, bool, swift::constraints::ConstraintLocatorBuilder) + 540
9  swift-frontend           0x0000000104fa1af0 (anonymous namespace)::ExprRewriter::coerceToType(swift::Expr*, swift::Type, swift::constraints::ConstraintLocatorBuilder) + 6600
10 swift-frontend           0x0000000101e31724 swift::constraints::Solution::coerceToType(swift::Expr*, swift::Type, swift::constraints::ConstraintLocator*) + 176
11 swift-frontend           0x0000000102ed6a14 applySolutionToInitialization(swift::constraints::Solution&, swift::constraints::SyntacticElementTarget, swift::Expr*, std::__1::function<llvm::Optional<swift::constraints::SyntacticElementTarget> (swift::constraints::SyntacticElementTarget)>) + 764
12 swift-frontend           0x0000000104f9b198 (anonymous namespace)::ExprWalker::rewriteTarget(swift::constraints::SyntacticElementTarget) + 5004
13 swift-frontend           0x0000000102e9579c swift::constraints::ConstraintSystem::applySolution(swift::constraints::Solution&, swift::constraints::SyntacticElementTarget) + 6956
14 swift-frontend           0x00000001034d9b1c swift::TypeChecker::typeCheckTarget(swift::constraints::SyntacticElementTarget&, swift::OptionSet<swift::TypeCheckExprFlags, unsigned int>) + 756
15 swift-frontend           0x0000000105c72e4c swift::TypeChecker::typeCheckExpression(swift::constraints::SyntacticElementTarget&, swift::OptionSet<swift::TypeCheckExprFlags, unsigned int>) + 436
16 swift-frontend           0x0000000105c74ba8 swift::TypeChecker::typeCheckBinding(swift::Pattern*&, swift::Expr*&, swift::DeclContext*, swift::Type, swift::PatternBindingDecl*, unsigned int, swift::OptionSet<swift::TypeCheckExprFlags, unsigned int>) + 368
17 swift-frontend           0x00000001034dc720 swift::TypeChecker::typeCheckPatternBinding(swift::PatternBindingDecl*, unsigned int, swift::Type, swift::OptionSet<swift::TypeCheckExprFlags, unsigned int>) + 256
18 swift-frontend           0x00000001037b5724 swift::PatternBindingEntryRequest::evaluate(swift::Evaluator&, swift::PatternBindingDecl*, unsigned int, bool) const + 3868
19 swift-frontend           0x0000000103580b44 llvm::Expected<swift::PatternBindingEntryRequest::OutputType> swift::Evaluator::getResultUncached<swift::PatternBindingEntryRequest>(swift::PatternBindingEntryRequest const&) + 648
20 swift-frontend           0x0000000105cc085c swift::PatternBindingEntryRequest::OutputType swift::evaluateOrDefault<swift::PatternBindingEntryRequest>(swift::Evaluator&, swift::PatternBindingEntryRequest, swift::PatternBindingEntryRequest::OutputType) + 56
21 swift-frontend           0x00000001035d6a2c (anonymous namespace)::DeclChecker::visit(swift::Decl*) (.llvm.13906395601279508432) + 6420
22 swift-frontend           0x00000001035d4d64 swift::TypeChecker::typeCheckDecl(swift::Decl*, bool) + 220
23 swift-frontend           0x0000000103790840 swift::ASTVisitor<(anonymous namespace)::StmtChecker, void, swift::Stmt*, void, void, void, void>::visit(swift::Stmt*) (.llvm.3900483966656927864) + 296
24 swift-frontend           0x00000001062a49d8 bool (anonymous namespace)::StmtChecker::typeCheckStmt<swift::BraceStmt>(swift::BraceStmt*&) (.llvm.3900483966656927864) + 316
25 swift-frontend           0x000000010378a750 swift::TypeChecker::typeCheckTopLevelCodeDecl(swift::TopLevelCodeDecl*) + 140
26 swift-frontend           0x000000010383a920 swift::TypeCheckSourceFileRequest::evaluate(swift::Evaluator&, swift::SourceFile*) const + 472
27 swift-frontend           0x0000000103840658 llvm::Expected<swift::TypeCheckSourceFileRequest::OutputType> swift::Evaluator::getResultUncached<swift::TypeCheckSourceFileRequest>(swift::TypeCheckSourceFileRequest const&) + 664
28 swift-frontend           0x000000010381ea4c swift::TypeCheckSourceFileRequest::OutputType swift::evaluateOrDefault<swift::TypeCheckSourceFileRequest>(swift::Evaluator&, swift::TypeCheckSourceFileRequest, swift::TypeCheckSourceFileRequest::OutputType) + 228
29 swift-frontend           0x0000000103ef5a8c swift::CompilerInstance::performSema() + 160
30 swift-frontend           0x0000000105e50504 performCompile(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 464
31 swift-frontend           0x0000000105e54854 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 4568
32 swift-frontend           0x0000000105ebbd44 swift::mainEntry(int, char const**) + 4408
33 dyld                     0x0000000184f410e0 start + 2360
error: fatalError
```

### Expected behavior

The expected behaviour is either no crash or a compiler error "any Sequence" cannot conform to Sequence

### Environment

swift-driver version: 1.87.3 Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)
Target: arm64-apple-macosx14.0

**Comment by AnthonyLatsis** [comment] 2024-11-29 15:37
Self-contained:
```swift
protocol P {
  associatedtype Element
}
struct Test<Element> {
  public init<T: P>(_: T) where T.Element == Element {}
}
let p: any P
let _ = Test.init(p)

```

**Comment by AnthonyLatsis** [comment] 2024-11-29 16:23
Duplicate of #61934

**Closed by AnthonyLatsis** 2024-11-29 16:23 UTC
Labels: bug, duplicate, compiler, type checker, generics, crash, existentials, generic constraints, expressions, implicit existential opening, types, assertion failure, swift 6.1
