### ISSUE TITLE
Syntax error from property wrapper type inference

### ISSUE THREAD

**Issue by mbrandonw** [swiftlang/swift#61822] opened 2022-10-31 19:02 UTC
**Describe the bug**

Property wrappers allow us to sometimes elide types, but that doesn't seem to play nicely with the next line in the code:

```import SwiftUI
func foo() {
  @Environment(\.colorScheme) var colorScheme
  print(colorScheme)
}
```

This causes the following syntax error:

> 🛑 Consecutive statements on a line must be separated by ';'
> 🛑 Found an unexpected second identifier in variable declaration; is there an accidental break?
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Join the identifiers together
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Join the identifiers together with camel-case

To workaround you must put a semi-colon at the end of the line:

```import SwiftUI
func foo() {
  @Environment(\.colorScheme) var colorScheme; // ⬅️ semi-colon
  print(colorScheme)
}
```

**Steps To Reproduce**

Run the above code in Swift.

**Expected behavior**

I would expect the code to compile without the semi-colon.

**Environment (please fill out the following information)**
 - OS: 13.0 (22A380)
 - Xcode Version/Tag/Branch: Xcode 14.1, Swift 5.7

**Comment by AnthonyLatsis** [comment] 2022-11-01 03:15
Duplicate of #57542

**Closed** 2022-11-03 13:07 UTC
Labels: parser, compiler, property wrappers
