### ISSUE TITLE
Generic parameter 'τ_0_0' could not be inferred

### ISSUE THREAD

**Issue by ios-blacksmith** [swiftlang/swift#63150] opened 2023-01-21 16:06 UTC
**Description**
Generic parameter 'τ_0_0' could not be inferred.

**Steps to reproduce**
Open playgrounds and paste the following code:
```swift
import SwiftUI
enum Fruit {

    case apple
    case orange

    var icon: (some View)? {
        switch self {
        case .apple: return Image(systemName: "applelogo")
        case .orange: return nil
        }
    }

}
```

**Expected behavior**
No error. The "(some View)?" type should be acceptable since either of the return types are in line with it.
 

**Environment**
- Swift compiler version info swift-driver version: 1.62.15 Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)
Target: arm64-apple-macosx13.0

- Xcode version info Xcode 14.2
Build version 14C18
- Deployment target: N/A - swift playgrounds

Opening the issues here as per: https://github.com/apple/swift/issues/53242#issuecomment-1398756788

**Comment by LucianoPAlmeida** [comment] 2023-01-22 01:29
I think this is a duplicate from https://github.com/apple/swift/issues/62787. The diagnostics part we improved on main recently.

**Comment by xedin** [comment] 2023-01-22 08:51
@LucianoPAlmeida is right, the diagnostic should be improved and this situation is indeed an error because `nil` does not provide a value for opaque type.

**Comment by AnthonyLatsis** [comment] 2023-01-23 12:13
>  this situation is indeed an error because nil does not provide a value for opaque type.

In time, though, could we not do a type join or something to infer the `nil`’s wrapped type from the other return statement?

**Comment by AnthonyLatsis** [comment] 2023-01-23 12:16
Closing as duplicate of #62787

**Closed by AnthonyLatsis** 2023-01-23 12:16 UTC
Labels: bug, duplicate, compiler, diagnostics QoI, type checker, generics, opaque types, type inference, literals, swift 5.7

**Comment by xedin** [comment] 2023-01-23 16:38
Maybe, the performance implications are yet to be determined though.

**Comment by xedin** [comment] 2023-01-23 19:04
`Image?.none` is probably better.

**Comment by ios-blacksmith** [comment] 2023-01-23 19:57
> @ios-blacksmith In case we did a poor job at conveying this, the workaround is `nil as Image?`. It doesn’t have to be this exact expression, just make sure you explicitly return an `Image?`.

Fantastic! Thank you for the follow up and the workaround 🎖️

**Comment by ios-blacksmith** [comment] 2023-01-23 19:59
> @LucianoPAlmeida is right, the diagnostic should be improved and this situation is indeed an error because `nil` does not provide a value for opaque type.

Thank you for the clarification!
