### ISSUE TITLE
Storing variadic function in variadic types

### ISSUE THREAD

**Issue by CrystDragon** [swiftlang/swift#69413] opened 2023-10-25 19:02 UTC
**Description**

```swift
struct Var<each T> {
  let foo: (repeat each T) -> Void
  init(_ foo: @escaping (repeat each T) -> Void) {
    self.foo = foo   // < - Error
  }
}

struct Bar<First, each T, Result> {
  let foo: (First, repeat each T) -> Result
  init(_ foo: @escaping (First, repeat each T) -> Result) {
    self.foo = foo  // < - Error
  }
}
```
The 2 examples above should both compile, but neither does.

Error message for the 1st one:
```
type of expression is ambiguous without a type annotation
```

Error message for the 2nd one:
```
Cannot assign value of type '(First, repeat each T) -> Result' to type '(First, repeat each T) -> Result'
Pack expansion requires that 'each T' and 'repeat each T' have the same shape
```

Both error messages confuse me.

**Environment**
* 1.87.1 Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)
* Xcode 15.0
* Build version 15A240d

**Comment by AnthonyLatsis** [comment] 2023-10-25 21:06
Duplicate of #68369

**Closed by AnthonyLatsis** 2023-10-25 21:06 UTC
Labels: bug, duplicate, compiler, type checker, generics, expressions, unexpected error, function types, properties, assignments, parameter packs, types, swift 6.0
