### ISSUE TITLE
swiftc crashes with "Unhandled coercion:" 

### ISSUE THREAD

**Issue by al45tair** [swiftlang/swift#76400] opened 2024-09-11 10:24 UTC
### Description

See https://forums.swift.org/t/xcode-16-type-cast-to-protocol-with-constrained-associated-type/74511

### Reproduction

```swift
import Foundation

let row:Any = TestRow()

if let row = row as? (any EntityRow) {
    print(row.entity.guid)
}

class TestEntity:Entity{
    var guid: UUID = UUID()
}

class Row{
    var height:CGFloat = 0;
}

protocol Entity{
    var guid:UUID{get}
}

protocol EntityRow:AnyObject {
    associatedtype E:Entity;
    var entity:E {get set}
}

class TestRow:Row,EntityRow{
    var entity:TestEntity = .init()
}
```

then

```terminal
$ swiftc tst.swift -c -o tst.o
```

is sufficient to get a crash.

### Stack dump

```text
Unhandled coercion:
(opened_archetype_type address=0x1137289a0 conforms_to="tst.(file).Entity@tst.swift:17:10" opened_existential_id="94B0C8BE-7027-11EF-AC72-32DC35ABE8E7"
  (interface_type=dependent_member_type assoc_type="tst.(file).EntityRow.E@tst.swift:22:20"
    (base=generic_type_param_type depth=0 index=0))
  (opened_existential=existential_type
    (protocol_type decl="tst.(file).EntityRow@tst.swift:21:10")))
(lvalue_type
  (existential_type
    (protocol_type decl="tst.(file).Entity@tst.swift:17:10")))
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the crash backtrace.
Stack dump:
0.	Program arguments: /Applications/Xcode-Geode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-frontend -frontend -c -primary-file tst.swift -target arm64-apple-macosx15.0 -Xllvm -aarch64-use-tbi -enable-objc-interop -stack-check -sdk /Applications/Xcode-Geode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.0.sdk -color-diagnostics -new-driver-path /Applications/Xcode-Geode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-driver -empty-abi-descriptor -blocklist-file /Applications/Xcode-Geode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/local/lib/swift/blocklists/Optimizations.yaml -blocklist-file /Applications/Xcode-Geode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/local/lib/swift/blocklists/modules.yml -resource-dir /Applications/Xcode-Geode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift -module-name tst -disable-clang-spi -target-sdk-version 15.0 -target-sdk-name macosx15.0 -external-plugin-path /Applications/Xcode-Geode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib/swift/host/plugins#/Applications/Xcode-Geode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode-Geode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/local/lib/swift/host/plugins#/Applications/Xcode-Geode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin/swift-plugin-server -plugin-path /Applications/Xcode-Geode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/host/plugins -plugin-path /Applications/Xcode-Geode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/local/lib/swift/host/plugins -o tst.o
1.	Apple Swift version 6.0 (swiftlang-6.0.0.9.10 clang-1600.0.26.2)
2.	Compiling with effective version 5.10
3.	While evaluating request TypeCheckSourceFileRequest(source_file "tst.swift")
4.	While type-checking statement at [tst.swift:5:1 - line:7:1] RangeText="if let row = row as? (any EntityRow) {
    print(row.entity.guid)
"
5.	While type-checking statement at [tst.swift:5:1 - line:7:1] RangeText="if let row = row as? (any EntityRow) {
    print(row.entity.guid)
"
6.	While type-checking statement at [tst.swift:5:38 - line:7:1] RangeText="{
    print(row.entity.guid)
"
7.	While type-checking expression at [tst.swift:6:5 - line:6:26] RangeText="print(row.entity.guid"
8.	While type-checking-target starting at tst.swift:6:5
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  swift-frontend           0x0000000109ec70fc llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 56
1  swift-frontend           0x0000000109ec5350 llvm::sys::RunSignalHandlers() + 112
2  swift-frontend           0x0000000109ec76c8 SignalHandler(int) + 292
3  libsystem_platform.dylib 0x000000018f660b64 _sigtramp + 56
4  libsystem_pthread.dylib  0x000000018f62bf50 pthread_kill + 288
5  libsystem_c.dylib        0x000000018f538908 abort + 128
6  swift-frontend           0x000000010593310c (anonymous namespace)::ExprRewriter::coerceToType(swift::Expr*, swift::Type, swift::constraints::ConstraintLocatorBuilder) + 10492
7  swift-frontend           0x00000001059321ac (anonymous namespace)::ExprRewriter::coerceToType(swift::Expr*, swift::Type, swift::constraints::ConstraintLocatorBuilder) + 6556
8  swift-frontend           0x00000001059524d4 (anonymous namespace)::ExprRewriter::closeExistential(swift::Expr*&, swift::constraints::ConstraintLocatorBuilder, bool) + 596
9  swift-frontend           0x000000010594b118 (anonymous namespace)::ExprRewriter::buildMemberRef(swift::Expr*, swift::SourceLoc, swift::constraints::SelectedOverload, swift::DeclNameLoc, swift::constraints::ConstraintLocatorBuilder, swift::constraints::ConstraintLocatorBuilder, bool, swift::AccessSemantics) + 9320
10 swift-frontend           0x000000010593ceb8 (anonymous namespace)::ExprRewriter::walkToExprPost(swift::Expr*) + 21120
11 swift-frontend           0x0000000105934664 (anonymous namespace)::ExprWalker::walkToExprPost(swift::Expr*) + 24
12 swift-frontend           0x0000000105fcb864 (anonymous namespace)::Traversal::visitExtractFunctionIsolationExpr(swift::ExtractFunctionIsolationExpr*) + 116
13 swift-frontend           0x0000000105fcaeac (anonymous namespace)::Traversal::visit(swift::Expr*) + 260
14 swift-frontend           0x0000000105fd0d44 (anonymous namespace)::Traversal::visit(swift::ArgumentList*) + 288
15 swift-frontend           0x0000000105fcd8dc (anonymous namespace)::Traversal::visitApplyExpr(swift::ApplyExpr*) + 196
16 swift-frontend           0x0000000105fcae00 (anonymous namespace)::Traversal::visit(swift::Expr*) + 88
17 swift-frontend           0x000000010592e4dc (anonymous namespace)::ExprWalker::rewriteTarget(swift::constraints::SyntacticElementTarget) + 344
18 swift-frontend           0x000000010592dec0 swift::constraints::ConstraintSystem::applySolution(swift::constraints::Solution&, swift::constraints::SyntacticElementTarget) + 7120
19 swift-frontend           0x0000000105bed6a8 swift::TypeChecker::typeCheckTarget(swift::constraints::SyntacticElementTarget&, swift::optionset::OptionSet<swift::TypeCheckExprFlags, unsigned int>) + 680
20 swift-frontend           0x0000000105bed2dc swift::TypeChecker::typeCheckExpression(swift::constraints::SyntacticElementTarget&, swift::optionset::OptionSet<swift::TypeCheckExprFlags, unsigned int>) + 416
21 swift-frontend           0x0000000105cd83b0 (anonymous namespace)::StmtChecker::typeCheckASTNode(swift::ASTNode&) + 332
22 swift-frontend           0x0000000105cdd97c swift::ASTVisitor<(anonymous namespace)::StmtChecker, void, swift::Stmt*, void, void, void, void>::visit(swift::Stmt*) + 288
23 swift-frontend           0x0000000105cdb2bc bool (anonymous namespace)::StmtChecker::typeCheckStmt<swift::BraceStmt>(swift::BraceStmt*&) + 316
24 swift-frontend           0x0000000105cddd1c swift::ASTVisitor<(anonymous namespace)::StmtChecker, void, swift::Stmt*, void, void, void, void>::visit(swift::Stmt*) + 1216
25 swift-frontend           0x0000000105cdd724 bool (anonymous namespace)::StmtChecker::typeCheckStmt<swift::Stmt>(swift::Stmt*&) + 316
26 swift-frontend           0x0000000105cd82bc (anonymous namespace)::StmtChecker::typeCheckASTNode(swift::ASTNode&) + 88
27 swift-frontend           0x0000000105cdd97c swift::ASTVisitor<(anonymous namespace)::StmtChecker, void, swift::Stmt*, void, void, void, void>::visit(swift::Stmt*) + 288
28 swift-frontend           0x0000000105cdb2bc bool (anonymous namespace)::StmtChecker::typeCheckStmt<swift::BraceStmt>(swift::BraceStmt*&) + 316
29 swift-frontend           0x0000000105cdb498 swift::TypeChecker::typeCheckTopLevelCodeDecl(swift::TopLevelCodeDecl*) + 148
30 swift-frontend           0x0000000105d27d80 swift::TypeCheckSourceFileRequest::evaluate(swift::Evaluator&, swift::SourceFile*) const + 696
31 swift-frontend           0x0000000105d2f3c0 swift::TypeCheckSourceFileRequest::OutputType swift::Evaluator::getResultUncached<swift::TypeCheckSourceFileRequest, swift::TypeCheckSourceFileRequest::OutputType swift::evaluateOrDefault<swift::TypeCheckSourceFileRequest>(swift::Evaluator&, swift::TypeCheckSourceFileRequest, swift::TypeCheckSourceFileRequest::OutputType)::'lambda'()>(swift::TypeCheckSourceFileRequest const&, swift::TypeCheckSourceFileRequest::OutputType swift::evaluateOrDefault<swift::TypeCheckSourceFileRequest>(swift::Evaluator&, swift::TypeCheckSourceFileRequest, swift::TypeCheckSourceFileRequest::OutputType)::'lambda'()) + 620
32 swift-frontend           0x0000000105d27aac swift::performTypeChecking(swift::SourceFile&) + 328
33 swift-frontend           0x0000000104c46ce0 swift::CompilerInstance::performSema() + 260
34 swift-frontend           0x0000000104874190 performCompile(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 1528
35 swift-frontend           0x0000000104872f58 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 3572
36 swift-frontend           0x00000001047fa01c swift::mainEntry(int, char const**) + 3680
37 dyld                     0x000000018f2a8274 start + 2840
```

### Expected behavior

The Swift compiler should not crash.

### Environment

```terminal
$ swiftc -version
swift-driver version: 1.115 Apple Swift version 6.0 (swiftlang-6.0.0.9.10 clang-1600.0.26.2)
Target: arm64-apple-macosx15.0
```

**Comment by xiaogdgenuine** [comment] 2024-09-19 23:17
Is there any workaround for this?

**Comment by AnthonyLatsis** [comment] 2024-11-19 11:05
Reduced:

```swift
protocol EntityRow: AnyObject {
    associatedtype E
    var entity: E { get set }
}
func test(row: any EntityRow) {
    let _ = row.entity
}
```

**Comment by AnthonyLatsis** [comment] 2024-11-27 09:58
Duplicate of #62219

**Closed** 2024-11-27 09:58 UTC
Labels: bug, duplicate, compiler, type checker, crash, existentials, expressions, existential member accesses, types, assertion failure, swift 6.1
