### ISSUE TITLE
Incorrect compiler error message when using type inference for closure return type

### ISSUE THREAD

**Issue by MartinSandeCosta** [swiftlang/swift#64500] opened 2023-03-21 11:45 UTC
**Description**
The compiler is not able to infer the type of the closure's return value, resulting in an incorrect error message. The error message in this snippet does not match the actual bug. Instead of reporting `binary operator '+' cannot be applied to operands of type 'Int' and 'String'`, it reports `'nil' is incompatible with return type 'Int'`. The closure's return type can be explicitly set to `Int?` to resolve the type inference ambiguity. 

**Steps to reproduce**
```swift
class SomeClass {
    private let items: [String] = ["1", "2", "3"]

    var computedVar: [Int] {
        items.compactMap { _ in 
            guard true else {
                // error: 'nil' is incompatible with return type 'Int'
                return nil
            }
            let a = 2
            let b = "hello"
            a + b
            return 1
        }
    }
}
```

**Expected behavior**
The compiler should report the following error: `binary operator '+' cannot be applied to operands of type 'Int' and 'String'`.

**Environment**
- Swift compiler version info: >= 5.7

**Comment by AnthonyLatsis** [comment] 2023-03-22 00:54
Duplicate of #62051

**Closed by AnthonyLatsis** 2023-03-22 00:54 UTC
Labels: bug, compiler, diagnostics QoI, type checker, type inference, closures, swift 5.9, multi-statement closures
