### ISSUE TITLE
Runtime crash: `T` constraint ignored for `any Alias<T>` when `typealias Alias<T> = ProtoA & ProtoB<T>`

### ISSUE THREAD

**Issue by bubski** [swiftlang/swift#72390] opened 2024-03-18 13:18 UTC
### Reproduction

```swift
protocol ProtoA {}

protocol ProtoB<C> {
    associatedtype C
    var val: C { get }
}

typealias Alias<T> = ProtoA & ProtoB<T>

struct Foo: ProtoA, ProtoB {
    var val: String { "hello" }
}

// This should not compile.
// `Foo` matches `Alias<String>` but not `Alias<[String]>`.
var foo: any Alias<[String]> {
    Foo()
}

print(foo.val) // crash
```

https://godbolt.org/z/754fnc3qY

### Stack dump

```text
Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libswiftCore.dylib            	       0x1acf1a6c8 swift_retain + 44
1   libswiftCore.dylib            	       0x1acf1f714 swift::metadataimpl::BufferValueWitnesses<swift::metadataimpl::ValueWitnesses<swift::metadataimpl::BridgeObjectBox>, true, 8ul, 8ul, (swift::metadataimpl::FixedPacking)1>::initializeBufferWithCopyOfBuffer(swift::TargetValueBuffer<swift::InProcess>*, swift::TargetValueBuffer<swift::InProcess>*, swift::TargetMetadata<swift::InProcess> const*) + 28
2   libswiftCore.dylib            	       0x1aceb88f8 outlined init with copy of Any + 76
3   libswiftCore.dylib            	       0x1acd11d5c specialized _print<A>(_:separator:terminator:to:) + 232
4   libswiftCore.dylib            	       0x1acd10efc print(_:separator:terminator:) + 192
5   main                          	       0x10442bb20 main + 312
6   dyld                          	       0x19cb2e0e0 0x19cb28000 + 24800
```

### Expected behavior

The code should not compile.
There should be an error emitted for type mismatch in:
```swift
// This should not compile.
// `Foo` matches `Alias<String>` but not `Alias<[String]>`.
var foo: any Alias<[String]> {
    Foo()
}
```

### Environment

swift-driver version: 1.87.3 Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)
Target: arm64-apple-macosx14.0

### Additional information

For what its worth, this only happens when `typealias` is involved.
Otherwise, there's an **unrelated** compilation error:
```
main.swift:14:23: error: non-protocol, non-class type 'ProtoB<[String]>' cannot be used within a protocol-constrained type
var foo: any ProtoA & ProtoB<[String]> {
                      ^
```
https://github.com/apple/swift/issues/63877#issuecomment-1457542679 leads me to believe that this particular error should not actually exist,
and both `Alias<[String]>` and `ProtoA & ProtoB<[String]>` should be allowed and handled properly.

**Comment by zvonicek** [comment] 2024-06-05 11:57
update: still crashes on Swift 5.10, now with the following message

```
Failed to reconstruct type for $s6output6ProtoA_AA0B1BpSaySSG1CAaCPRts_XPD
Original type:
(existential_type
  (protocol_composition_type
    (protocol_type decl=output.(file).ProtoA@<source>:1:10)
    (parameterized_protocol_type
      (base=protocol_type decl=output.(file).ProtoB@<source>:3:10)
      (bound_generic_struct_type decl=Swift.(file).Array
        (struct_type decl=Swift.(file).String)))))
```

**Comment by slavapestov** [comment] 2024-08-03 19:17
Dupe of https://github.com/swiftlang/swift/issues/63877

**Closed by slavapestov** 2024-08-03 19:17 UTC
Labels: bug, duplicate, compiler, run-time crash, generics, crash, parameterized protocols, existentials, protocol compositions, types, swift 6.0
