### ISSUE TITLE
Crash when passing unconstrained protocol type to generic function

### ISSUE THREAD

**Issue by hydrixos** [swiftlang/swift#71644] opened 2024-02-15 09:35 UTC
### Description

The following code snippet contains a mistake that should be detected as error by the compiler, but leads to a crash.

 There is a protocol with an primary associated type:

```swift
protocol Something<Result> {
	associatedtype Result
}
```

If I pass this protocol in an unconstrained form to a generic method that matches on the primary associated type, the compiler crashes:

```swift
func doSomething<T>(_ something: some Something<T>) -> T {
	// ...
}

func makeSomething() -> any Something {
	// ...
}

// This line crashes the compiler, because makeSomething returns the protocol with an unconstrained associated type:
_ = doSomething(makeSomething())
```

### Reproduction

```swift
protocol Something<Result> {
	associatedtype Result
}

func makeSomething() -> any Something {
	// ...
}

func doSomething<T>(_ something: some Something<T>) -> T {
	// ...
}

// This line crashes the compiler, because makeSomething returns the protocol with an unconstrained associated type:
_ = doSomething(makeSomething())
```

### Stack dump

```text
error: compile command failed due to signal 6 (use -v to see invocation)
Unhandled coercion:
(existential_type
  (protocol_composition_type))
(opened_archetype_type address=0x13b9c9bc0
  (interface_type=dependent_member_type assoc_type=Untitled.(file).Something.Result@Untitled.swift:2:17
    (base=generic_type_param_type depth=0 index=0))
  (opened_existential=existential_type
    (protocol_type decl=Untitled.(file).Something@Untitled.swift:1:10)) opened_existential_id=09FCB836-CBE5-11EE-92EA-2A7F2AAB6BF0)
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the crash backtrace.
Stack dump:
0.	Program arguments: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-frontend -frontend -c -primary-file Untitled.swift -target arm64-apple-macosx14.0 -Xllvm -aarch64-use-tbi -enable-objc-interop -stack-check -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk -new-driver-path /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-driver -empty-abi-descriptor -resource-dir /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift -module-name Untitled -disable-clang-spi -target-sdk-version 14.2 -target-sdk-name macosx14.2 -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/lib/swift/host/plugins#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/local/lib/swift/host/plugins#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib/swift/host/plugins#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/local/lib/swift/host/plugins#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin/swift-plugin-server -plugin-path /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/host/plugins -plugin-path /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/local/lib/swift/host/plugins -o /var/folders/ks/pnyst7c54xq_6cftmn_95jyh0000gp/T/TemporaryDirectory.PH1zNE/Untitled-1.o
1.	Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)
2.	Compiling with the current language version
3.	While evaluating request TypeCheckSourceFileRequest(source_file "Untitled.swift")
4.	While type-checking statement at [Untitled.swift:13:1 - line:13:32] RangeText="_ = doSomething(makeSomething()"
5.	While type-checking expression at [Untitled.swift:13:1 - line:13:32] RangeText="_ = doSomething(makeSomething()"
6.	While type-checking-target starting at Untitled.swift:13:1
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  swift-frontend           0x0000000105661abc llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 56
1  swift-frontend           0x00000001082c7cb0 llvm::sys::RunSignalHandlers() + 112
2  swift-frontend           0x0000000108031054 SignalHandler(int) + 352
3  libsystem_platform.dylib 0x000000018d589a24 _sigtramp + 56
4  libsystem_pthread.dylib  0x000000018d559cc0 pthread_kill + 288
5  libsystem_c.dylib        0x000000018d465a40 abort + 180
6  swift-frontend           0x0000000106cf649c (anonymous namespace)::ExprRewriter::coerceToType(swift::Expr*, swift::Type, swift::constraints::ConstraintLocatorBuilder) + 9076
7  swift-frontend           0x0000000104c082f4 (anonymous namespace)::ExprRewriter::walkToExprPost(swift::Expr*) + 10664
8  swift-frontend           0x0000000104bf264c (anonymous namespace)::ExprWalker::walkToExprPost(swift::Expr*) + 24
9  swift-frontend           0x0000000106cee8a8 (anonymous namespace)::ExprWalker::rewriteTarget(swift::constraints::SyntacticElementTarget) + 2716
10 swift-frontend           0x0000000104be979c swift::constraints::ConstraintSystem::applySolution(swift::constraints::Solution&, swift::constraints::SyntacticElementTarget) + 6956
11 swift-frontend           0x000000010522db1c swift::TypeChecker::typeCheckTarget(swift::constraints::SyntacticElementTarget&, swift::OptionSet<swift::TypeCheckExprFlags, unsigned int>) + 756
12 swift-frontend           0x00000001079c6e4c swift::TypeChecker::typeCheckExpression(swift::constraints::SyntacticElementTarget&, swift::OptionSet<swift::TypeCheckExprFlags, unsigned int>) + 436
13 swift-frontend           0x0000000107fed460 (anonymous namespace)::StmtChecker::typeCheckASTNode(swift::ASTNode&) (.llvm.3900483966656927864) + 396
14 swift-frontend           0x00000001054e4840 swift::ASTVisitor<(anonymous namespace)::StmtChecker, void, swift::Stmt*, void, void, void, void>::visit(swift::Stmt*) (.llvm.3900483966656927864) + 296
15 swift-frontend           0x0000000107ff89d8 bool (anonymous namespace)::StmtChecker::typeCheckStmt<swift::BraceStmt>(swift::BraceStmt*&) (.llvm.3900483966656927864) + 316
16 swift-frontend           0x00000001054de750 swift::TypeChecker::typeCheckTopLevelCodeDecl(swift::TopLevelCodeDecl*) + 140
17 swift-frontend           0x000000010558e920 swift::TypeCheckSourceFileRequest::evaluate(swift::Evaluator&, swift::SourceFile*) const + 472
18 swift-frontend           0x0000000105594658 llvm::Expected<swift::TypeCheckSourceFileRequest::OutputType> swift::Evaluator::getResultUncached<swift::TypeCheckSourceFileRequest>(swift::TypeCheckSourceFileRequest const&) + 664
19 swift-frontend           0x0000000105572a4c swift::TypeCheckSourceFileRequest::OutputType swift::evaluateOrDefault<swift::TypeCheckSourceFileRequest>(swift::Evaluator&, swift::TypeCheckSourceFileRequest, swift::TypeCheckSourceFileRequest::OutputType) + 228
20 swift-frontend           0x0000000105c49a8c swift::CompilerInstance::performSema() + 160
21 swift-frontend           0x0000000107ba4504 performCompile(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 464
22 swift-frontend           0x0000000107ba8854 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 4568
23 swift-frontend           0x0000000107c0fd44 swift::mainEntry(int, char const**) + 4408
24 dyld                     0x000000018d1d90e0 start + 2360
error: fatalError
```

### Expected behavior

The compiler should not accept the call `_ = doSomething(makeSomething())` because the result of "makeSomething()" has an unconstrained type.

### Environment

swift-driver version: 1.87.3 Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)
Target: arm64-apple-macosx14.0

**Comment by AnthonyLatsis** [comment] 2024-12-01 17:30
Duplicate of #61934

**Closed by AnthonyLatsis** 2024-12-01 17:30 UTC
Labels: bug, duplicate, compiler, type checker, generics, crash, existentials, expressions, implicit existential opening, types, assertion failure, swift 6.1
