### ISSUE TITLE
swift-frontend crashes during appendConcreteProtocolConformance

### ISSUE THREAD

**Issue by john-flanagan** [swiftlang/swift#64472] opened 2023-03-18 22:58 UTC
**Description**

Creating a key path in tests to a protocol property that's defined in an extension can crash swift-frontend

**Steps to reproduce**

1. Create a new Swift library package
2. Add the following code to the target
```swift
protocol P {}

extension P {
  var i: Int { 0 }
}
```
3. Add the following code to the test target
```swift
@testable import compiler_crash

func crash() { _ = \P.i }
```
4. Run `swift test`
5. Observe a crash

```
$ swift test
Building for debugging...
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the project and the crash backtrace.
Stack dump:
0.	Program arguments: /Applications/Xcode-14.2.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-frontend -frontend -c -primary-file /Users/john/Desktop/compiler-crash/Tests/compiler-crashTests/compiler_crashTests.swift -emit-dependencies-path /Users/john/Desktop/compiler-crash/.build/arm64-apple-macosx/debug/compiler_crashTests.build/compiler_crashTests.d -emit-reference-dependencies-path /Users/john/Desktop/compiler-crash/.build/arm64-apple-macosx/debug/compiler_crashTests.build/compiler_crashTests.swiftdeps -target arm64-apple-macosx11.0 -Xllvm -aarch64-use-tbi -enable-objc-interop -stack-check -sdk /Applications/Xcode-14.2.0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -I /Users/john/Desktop/compiler-crash/.build/arm64-apple-macosx/debug -I /Applications/Xcode-14.2.0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib -F /Applications/Xcode-14.2.0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -color-diagnostics -enable-testing -g -module-cache-path /Users/john/Desktop/compiler-crash/.build/arm64-apple-macosx/debug/ModuleCache -swift-version 5 -Onone -D SWIFT_PACKAGE -D DEBUG -new-driver-path /Applications/Xcode-14.2.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-driver -empty-abi-descriptor -resource-dir /Applications/Xcode-14.2.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift -enable-anonymous-context-mangled-names -module-name compiler_crashTests -disable-clang-spi -target-sdk-version 13.1 -parse-as-library -o /Users/john/Desktop/compiler-crash/.build/arm64-apple-macosx/debug/compiler_crashTests.build/compiler_crashTests.swift.o -index-store-path /Users/john/Desktop/compiler-crash/.build/arm64-apple-macosx/debug/index/store -index-system-modules
1.	Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)
2.	Compiling with the current language version
3.	While evaluating request IRGenRequest(IR Generation for file "/Users/john/Desktop/compiler-crash/Tests/compiler-crashTests/compiler_crashTests.swift")
4.	While emitting IR SIL function "@$s19compiler_crashTests0B0yyF".
 for 'crash()' (at /Users/john/Desktop/compiler-crash/Tests/compiler-crashTests/compiler_crashTests.swift:3:1)
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  swift-frontend           0x0000000108d9f5b0 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 56
1  swift-frontend           0x0000000108d9e5b4 llvm::sys::RunSignalHandlers() + 112
2  swift-frontend           0x0000000108d9fc34 SignalHandler(int) + 344
3  libsystem_platform.dylib 0x000000019ad132a4 _sigtramp + 56
4  swift-frontend           0x00000001054d74a8 swift::Mangle::ASTMangler::appendConcreteProtocolConformance(swift::ProtocolConformance const*, swift::GenericSignature) + 52
5  swift-frontend           0x00000001054d74a8 swift::Mangle::ASTMangler::appendConcreteProtocolConformance(swift::ProtocolConformance const*, swift::GenericSignature) + 52
6  swift-frontend           0x00000001047e166c swift::irgen::IRGenMangler::mangleSymbolNameForMangledConformanceAccessorString(char const*, swift::CanGenericSignature, swift::CanType, swift::ProtocolConformanceRef) + 212
7  swift-frontend           0x000000010477e844 swift::irgen::IRGenModule::emitWitnessTableRefString(swift::CanType, swift::ProtocolConformanceRef, swift::GenericSignature, bool) + 424
8  swift-frontend           0x000000010473bad0 void llvm::function_ref<void (swift::irgen::GenericRequirement)>::callback_fn<emitKeyPathComponent(swift::irgen::IRGenModule&, swift::irgen::ConstantStructBuilder&, swift::KeyPathPatternComponent const&, bool, swift::GenericEnvironment*, llvm::ArrayRef<swift::irgen::GenericRequirement>, swift::CanType, llvm::ArrayRef<KeyPathIndexOperand>, bool)::$_5>(long, swift::irgen::GenericRequirement) + 264
9  swift-frontend           0x000000010476f904 swift::irgen::enumerateGenericSignatureRequirements(swift::CanGenericSignature, llvm::function_ref<void (swift::irgen::GenericRequirement)> const&) + 380
10 swift-frontend           0x00000001047366d0 emitKeyPathComponent(swift::irgen::IRGenModule&, swift::irgen::ConstantStructBuilder&, swift::KeyPathPatternComponent const&, bool, swift::GenericEnvironment*, llvm::ArrayRef<swift::irgen::GenericRequirement>, swift::CanType, llvm::ArrayRef<KeyPathIndexOperand>, bool) + 760
11 swift-frontend           0x0000000104735e40 swift::irgen::IRGenModule::getAddrOfKeyPathPattern(swift::KeyPathPattern*, swift::SILLocation) + 2016
12 swift-frontend           0x00000001047f5af4 swift::SILInstructionVisitor<(anonymous namespace)::IRGenSILFunction, void>::visit(swift::SILInstruction*) + 7948
13 swift-frontend           0x00000001047eec5c swift::irgen::IRGenModule::emitSILFunction(swift::SILFunction*) + 7860
14 swift-frontend           0x00000001046bb2ec swift::irgen::IRGenerator::emitGlobalTopLevel(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) + 1552
15 swift-frontend           0x00000001047bcac4 swift::IRGenRequest::evaluate(swift::Evaluator&, swift::IRGenDescriptor) const + 2556
16 swift-frontend           0x00000001047ecadc swift::SimpleRequest<swift::IRGenRequest, swift::GeneratedModule (swift::IRGenDescriptor), (swift::RequestFlags)9>::evaluateRequest(swift::IRGenRequest const&, swift::Evaluator&) + 188
17 swift-frontend           0x00000001047c8fb8 llvm::Expected<swift::IRGenRequest::OutputType> swift::Evaluator::getResultUncached<swift::IRGenRequest>(swift::IRGenRequest const&) + 744
18 swift-frontend           0x00000001047bfeac swift::performIRGeneration(swift::FileUnit*, swift::IRGenOptions const&, swift::TBDGenOptions const&, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule> >, llvm::StringRef, swift::PrimarySpecificPaths const&, llvm::StringRef, llvm::GlobalVariable**) + 236
19 swift-frontend           0x00000001043eaa14 performCompileStepsPostSILGen(swift::CompilerInstance&, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule> >, llvm::PointerUnion<swift::ModuleDecl*, swift::SourceFile*>, swift::PrimarySpecificPaths const&, int&, swift::FrontendObserver*) + 2160
20 swift-frontend           0x00000001043ec7a0 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 5932
21 swift-frontend           0x000000010438d294 swift::mainEntry(int, char const**) + 3940
22 dyld                     0x000000019a9bbe50 start + 2544

error: fatalError
```

**Expected behavior**

I believe this is valid code that should compile without error

**Environment**
- Swift compiler version info 
swift-driver version: 1.62.15 Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)
Target: arm64-apple-macosx13.0

- Xcode version info
Xcode 14.2
Build version 14C18

- Deployment target:
macOS 13.1 (22C65)

**Additional context**
Seems related to, but not identical to this issue: https://github.com/apple/swift/issues/62788

**Comment by AnthonyLatsis** [comment] 2023-03-20 16:39
Duplicate of #58289

**Closed by AnthonyLatsis** 2023-03-20 16:39 UTC
Labels: bug, compiler, SILGen, key paths, crash, existentials, swift 5.7, multiple modules
