### ISSUE TITLE
Compiler crash value pack of pairs

### ISSUE THREAD

**Issue by DmT021** [swiftlang/swift#69232] opened 2023-10-17 17:08 UTC
**Description**
```
[cleanup]   %48 = alloc_stack $(repeat (each T, each U))    // user: %49
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the crash backtrace.
Stack dump:
0.	Program arguments: /Applications/Xcode15.0rc.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-frontend -frontend -c /Users/dmt021/Desktop/ios17_playground/ios17_playground/ContentView.swift -primary-file /Users/dmt021/Desktop/ios17_playground/ios17_playground/ios17_playgroundApp.swift /Users/dmt021/Library/Developer/Xcode/DerivedData/ios17_playground-egdchieoskamufeszozcfvhvmceh/Build/Intermediates.noindex/ios17_playground.build/Debug-iphonesimulator/ios17_playground.build/DerivedSources/GeneratedAssetSymbols.swift -emit-dependencies-path /Users/dmt021/Library/Developer/Xcode/DerivedData/ios17_playground-egdchieoskamufeszozcfvhvmceh/Build/Intermediates.noindex/ios17_playground.build/Debug-iphonesimulator/ios17_playground.build/Objects-normal/arm64/ios17_playgroundApp.d -emit-const-values-path /Users/dmt021/Library/Developer/Xcode/DerivedData/ios17_playground-egdchieoskamufeszozcfvhvmceh/Build/Intermediates.noindex/ios17_playground.build/Debug-iphonesimulator/ios17_playground.build/Objects-normal/arm64/ios17_playgroundApp.swiftconstvalues -emit-reference-dependencies-path /Users/dmt021/Library/Developer/Xcode/DerivedData/ios17_playground-egdchieoskamufeszozcfvhvmceh/Build/Intermediates.noindex/ios17_playground.build/Debug-iphonesimulator/ios17_playground.build/Objects-normal/arm64/ios17_playgroundApp.swiftdeps -serialize-diagnostics-path /Users/dmt021/Library/Developer/Xcode/DerivedData/ios17_playground-egdchieoskamufeszozcfvhvmceh/Build/Intermediates.noindex/ios17_playground.build/Debug-iphonesimulator/ios17_playground.build/Objects-normal/arm64/ios17_playgroundApp.dia -emit-localized-strings -emit-localized-strings-path /Users/dmt021/Library/Developer/Xcode/DerivedData/ios17_playground-egdchieoskamufeszozcfvhvmceh/Build/Intermediates.noindex/ios17_playground.build/Debug-iphonesimulator/ios17_playground.build/Objects-normal/arm64 -target arm64-apple-ios17.0-simulator -Xllvm -aarch64-use-tbi -enable-objc-interop -sdk /Applications/Xcode15.0rc.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.0.sdk -I /Users/dmt021/Library/Developer/Xcode/DerivedData/ios17_playground-egdchieoskamufeszozcfvhvmceh/Build/Products/Debug-iphonesimulator -F /Users/dmt021/Library/Developer/Xcode/DerivedData/ios17_playground-egdchieoskamufeszozcfvhvmceh/Build/Products/Debug-iphonesimulator -no-color-diagnostics -enable-testing -g -module-cache-path /Users/dmt021/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -swift-version 5 -enforce-exclusivity=checked -Onone -D DEBUG -serialize-debugging-options -const-gather-protocols-file /Users/dmt021/Library/Developer/Xcode/DerivedData/ios17_playground-egdchieoskamufeszozcfvhvmceh/Build/Intermediates.noindex/ios17_playground.build/Debug-iphonesimulator/ios17_playground.build/Objects-normal/arm64/ios17_playground_const_extract_protocols.json -enable-bare-slash-regex -empty-abi-descriptor -validate-clang-modules-once -clang-build-session-file /Users/dmt021/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -Xcc -working-directory -Xcc /Users/dmt021/Desktop/ios17_playground -resource-dir /Applications/Xcode15.0rc.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift -enable-anonymous-context-mangled-names -Xcc -ivfsstatcache -Xcc /Users/dmt021/Library/Developer/Xcode/DerivedData/SDKStatCaches.noindex/iphonesimulator17.0-21A325-4096740255bf5c49693ae3b7415746ed.sdkstatcache -Xcc -I/Users/dmt021/Library/Developer/Xcode/DerivedData/ios17_playground-egdchieoskamufeszozcfvhvmceh/Build/Intermediates.noindex/ios17_playground.build/Debug-iphonesimulator/ios17_playground.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/dmt021/Library/Developer/Xcode/DerivedData/ios17_playground-egdchieoskamufeszozcfvhvmceh/Build/Intermediates.noindex/ios17_playground.build/Debug-iphonesimulator/ios17_playground.build/ios17_playground-generated-files.hmap -Xcc -I/Users/dmt021/Library/Developer/Xcode/DerivedData/ios17_playground-egdchieoskamufeszozcfvhvmceh/Build/Intermediates.noindex/ios17_playground.build/Debug-iphonesimulator/ios17_playground.build/ios17_playground-own-target-headers.hmap -Xcc -I/Users/dmt021/Library/Developer/Xcode/DerivedData/ios17_playground-egdchieoskamufeszozcfvhvmceh/Build/Intermediates.noindex/ios17_playground.build/Debug-iphonesimulator/ios17_playground.build/ios17_playground-all-target-headers.hmap -Xcc -iquote -Xcc /Users/dmt021/Library/Developer/Xcode/DerivedData/ios17_playground-egdchieoskamufeszozcfvhvmceh/Build/Intermediates.noindex/ios17_playground.build/Debug-iphonesimulator/ios17_playground.build/ios17_playground-project-headers.hmap -Xcc -I/Users/dmt021/Library/Developer/Xcode/DerivedData/ios17_playground-egdchieoskamufeszozcfvhvmceh/Build/Products/Debug-iphonesimulator/include -Xcc -I/Users/dmt021/Library/Developer/Xcode/DerivedData/ios17_playground-egdchieoskamufeszozcfvhvmceh/Build/Intermediates.noindex/ios17_playground.build/Debug-iphonesimulator/ios17_playground.build/DerivedSources-normal/arm64 -Xcc -I/Users/dmt021/Library/Developer/Xcode/DerivedData/ios17_playground-egdchieoskamufeszozcfvhvmceh/Build/Intermediates.noindex/ios17_playground.build/Debug-iphonesimulator/ios17_playground.build/DerivedSources/arm64 -Xcc -I/Users/dmt021/Library/Developer/Xcode/DerivedData/ios17_playground-egdchieoskamufeszozcfvhvmceh/Build/Intermediates.noindex/ios17_playground.build/Debug-iphonesimulator/ios17_playground.build/DerivedSources -Xcc -DDEBUG=1 -module-name ios17_playground -frontend-parseable-output -disable-clang-spi -target-sdk-version 17.0 -target-sdk-name iphonesimulator17.0 -external-plugin-path /Applications/Xcode15.0rc.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.0.sdk/usr/lib/swift/host/plugins#/Applications/Xcode15.0rc.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.0.sdk/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode15.0rc.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.0.sdk/usr/local/lib/swift/host/plugins#/Applications/Xcode15.0rc.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.0.sdk/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode15.0rc.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/lib/swift/host/plugins#/Applications/Xcode15.0rc.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode15.0rc.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/local/lib/swift/host/plugins#/Applications/Xcode15.0rc.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/swift-plugin-server -plugin-path /Applications/Xcode15.0rc.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/host/plugins -plugin-path /Applications/Xcode15.0rc.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/local/lib/swift/host/plugins -o /Users/dmt021/Library/Developer/Xcode/DerivedData/ios17_playground-egdchieoskamufeszozcfvhvmceh/Build/Intermediates.noindex/ios17_playground.build/Debug-iphonesimulator/ios17_playground.build/Objects-normal/arm64/ios17_playgroundApp.o -index-unit-output-path /ios17_playground.build/Debug-iphonesimulator/ios17_playground.build/Objects-normal/arm64/ios17_playgroundApp.o -index-store-path /Users/dmt021/Library/Developer/Xcode/DerivedData/ios17_playground-egdchieoskamufeszozcfvhvmceh/Index.noindex/DataStore -index-system-modules
1.	Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)
2.	Compiling with the current language version
3.	While evaluating request ASTLoweringRequest(Lowering AST to SIL for file "/Users/dmt021/Desktop/ios17_playground/ios17_playground/ios17_playgroundApp.swift")
4.	While silgen emitFunction SIL function "@$s16ios17_playground4test5pairsxxQp_t_q_xQp_ttx_q_txQp_t_tRvzRv_q_Rhzr0_lF".
 for 'test(pairs:)' (at /Users/dmt021/Desktop/ios17_playground/ios17_playground/ios17_playgroundApp.swift:53:1)
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  swift-frontend           0x0000000102f9f14c llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 56
1  swift-frontend           0x0000000105b1df2c llvm::sys::RunSignalHandlers() + 112
2  swift-frontend           0x000000010185f10c SignalHandler(int) + 352
3  libsystem_platform.dylib 0x00000001a9eb6a24 _sigtramp + 56
4  swift-frontend           0x00000001038e95fc (anonymous namespace)::Transform::transform(swift::Lowering::ManagedValue, swift::Lowering::AbstractionPattern, swift::CanType, swift::Lowering::AbstractionPattern, swift::CanType, swift::SILType, swift::Lowering::SGFContext) (.llvm.8895637422209681515) + 6988
5  swift-frontend           0x0000000101afc6e4 swift::Lowering::Conversion::emit(swift::Lowering::SILGenFunction&, swift::SILLocation, swift::Lowering::ManagedValue, swift::Lowering::SGFContext) const + 508
6  swift-frontend           0x0000000103464f58 swift::Lowering::ConvertingInitialization::copyOrInitValueInto(swift::Lowering::SILGenFunction&, swift::SILLocation, swift::Lowering::ManagedValue, bool) + 108
7  swift-frontend           0x000000010320b1f4 void copyOrInitValuesInto<((anonymous namespace)::ImplodeKind)1>(swift::Lowering::Initialization*, llvm::ArrayRef<swift::Lowering::ManagedValue>&, swift::CanType, swift::SILLocation, swift::Lowering::SILGenFunction&) (.llvm.3914283275591932852) + 680
8  swift-frontend           0x0000000103115ce8 swift::Lowering::ArgumentSource::getAsSingleValue(swift::Lowering::SILGenFunction&, swift::Lowering::SGFContext) && + 236
9  swift-frontend           0x0000000100f48258 swift::Lowering::SILGenFunction::emitConvertedRValue(swift::SILLocation, swift::Lowering::Conversion const&, swift::Lowering::SGFContext, llvm::function_ref<swift::Lowering::ManagedValue (swift::Lowering::SILGenFunction&, swift::SILLocation, swift::Lowering::SGFContext)>) + 256
10 swift-frontend           0x0000000103116830 swift::Lowering::ArgumentSource::getAsSingleValue(swift::Lowering::SILGenFunction&, swift::Lowering::AbstractionPattern, swift::SILType, swift::Lowering::SGFContext) && + 360
11 swift-frontend           0x0000000103121a40 swift::Lowering::ArgumentSource::forwardInto(swift::Lowering::SILGenFunction&, swift::Lowering::AbstractionPattern, swift::Lowering::Initialization*, swift::Lowering::TypeLowering const&) && + 628
12 swift-frontend           0x000000010312057c swift::Lowering::ArgumentSource::materialize(swift::Lowering::SILGenFunction&, swift::Lowering::AbstractionPattern, swift::SILType) && + 860
13 swift-frontend           0x0000000103354438 (anonymous namespace)::ArgEmitter::emit(swift::Lowering::ArgumentSource&&, swift::Lowering::AbstractionPattern, llvm::Optional<swift::AnyFunctionType::Param>) + 2876
14 swift-frontend           0x0000000101a4eff8 (anonymous namespace)::ArgEmitter::emitExpanded(swift::Lowering::ArgumentSource&&, swift::Lowering::AbstractionPattern) + 1088
15 swift-frontend           0x0000000101a4f100 (anonymous namespace)::ArgEmitter::emitExpanded(swift::Lowering::ArgumentSource&&, swift::Lowering::AbstractionPattern) + 1352
16 swift-frontend           0x0000000103353b88 (anonymous namespace)::ArgEmitter::emit(swift::Lowering::ArgumentSource&&, swift::Lowering::AbstractionPattern, llvm::Optional<swift::AnyFunctionType::Param>) + 652
17 swift-frontend           0x00000001032f9d78 (anonymous namespace)::ArgEmitter::emitSingleArg(swift::Lowering::ArgumentSource&&, swift::Lowering::AbstractionPattern, llvm::Optional<swift::AnyFunctionType::Param>) + 224
18 swift-frontend           0x000000010334e55c (anonymous namespace)::ArgEmitter::emitPreparedArgs(swift::Lowering::PreparedArguments&&, swift::Lowering::AbstractionPattern) + 260
19 swift-frontend           0x00000001033c9ea0 (anonymous namespace)::CallSite::emit(swift::Lowering::SILGenFunction&, swift::Lowering::AbstractionPattern, swift::CanTypeWrapper<swift::SILFunctionType>, (anonymous namespace)::ParamLowering&, llvm::SmallVectorImpl<swift::Lowering::ManagedValue>&, llvm::SmallVectorImpl<(anonymous namespace)::DelayedArgument>&, swift::ForeignInfo const&) && + 672
20 swift-frontend           0x00000001033c8ab4 (anonymous namespace)::CallEmission::emitArgumentsForNormalApply(swift::Lowering::AbstractionPattern, swift::CanTypeWrapper<swift::SILFunctionType>, swift::ForeignInfo const&, llvm::SmallVectorImpl<swift::Lowering::ManagedValue>&, llvm::Optional<swift::SILLocation>&) + 1000
21 swift-frontend           0x000000010098734c (anonymous namespace)::CallEmission::apply(swift::Lowering::SGFContext) + 4044
22 swift-frontend           0x000000010330174c swift::Lowering::SILGenFunction::emitApplyExpr(swift::ApplyExpr*, swift::Lowering::SGFContext) + 3072
23 swift-frontend           0x0000000103559174 swift::Lowering::SILGenFunction::emitExprInto(swift::Expr*, swift::Lowering::Initialization*, llvm::Optional<swift::SILLocation>) + 128
24 swift-frontend           0x00000001039e96a4 swift::Lowering::SILGenFunction::emitReturnExpr(swift::SILLocation, swift::Expr*) + 1312
25 swift-frontend           0x000000010113c130 swift::ASTVisitor<(anonymous namespace)::StmtEmitter, void, void, void, void, void, void>::visit(swift::Stmt*) (.llvm.5384354941888427540) + 8520
26 swift-frontend           0x000000010113b374 swift::ASTVisitor<(anonymous namespace)::StmtEmitter, void, void, void, void, void, void>::visit(swift::Stmt*) (.llvm.5384354941888427540) + 5004
27 swift-frontend           0x0000000103691864 swift::Lowering::SILGenFunction::emitFunction(swift::FuncDecl*) + 632
28 swift-frontend           0x0000000100974a4c swift::Lowering::SILGenModule::emitFunctionDefinition(swift::SILDeclRef, swift::SILFunction*) + 8004
29 swift-frontend           0x000000010328163c emitOrDelayFunction(swift::Lowering::SILGenModule&, swift::SILDeclRef) (.llvm.12369091251732681984) + 168
30 swift-frontend           0x0000000103268be8 swift::Lowering::SILGenModule::emitFunction(swift::FuncDecl*) + 292
31 swift-frontend           0x0000000103290608 swift::ASTLoweringRequest::evaluate(swift::Evaluator&, swift::ASTLoweringDescriptor) const + 2908
32 swift-frontend           0x0000000101eb84fc swift::SimpleRequest<swift::ASTLoweringRequest, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule>> (swift::ASTLoweringDescriptor), (swift::RequestFlags)9>::evaluateRequest(swift::ASTLoweringRequest const&, swift::Evaluator&) + 200
33 swift-frontend           0x00000001032ae948 llvm::Expected<swift::ASTLoweringRequest::OutputType> swift::Evaluator::getResultUncached<swift::ASTLoweringRequest>(swift::ASTLoweringRequest const&) + 584
34 swift-frontend           0x0000000105ad58d8 performCompile(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 1680
35 swift-frontend           0x0000000105ad9474 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 4568
36 swift-frontend           0x000000010541f4e0 swift::mainEntry(int, char const**) + 4116
37 dyld                     0x00000001a9b2ff28 start + 2236
```

**Steps to reproduce**
```swift
func depair<each T, each U>(pairs: (repeat (each T, each U))) -> ((repeat each T), (repeat each U)) {
  return (
    (repeat (each pairs).0),
    (repeat (each pairs).1)
  )
}

func test<each T, each U>(pairs: (repeat (each T, each U))) -> ((repeat each T), (repeat each U)) {
  let r = pairs
  return depair(pairs: r)
}
```

**Expected behavior**
Compiles.

**Environment**
- Swift compiler version info swift-driver version: 1.87.1 Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)
- Xcode version info 15.0
- Deployment target: iOS 17

**Comment by AnthonyLatsis** [comment] 2023-10-18 11:22
With a trunk compiler, the following reduced example produces the same stack dump as the original one:
```swift
func test1<each T>(ts: (repeat each T)) {}
func test2<each T>(ts: (repeat each T)) {
  test1(ts: ts)
}
```

```
Assertion failed: (!tupleTy.containsPackExpansionType() && "can't extract elements from tuples containing pack expansions " "right now"), function extractElements, file RValue.cpp, line 705.
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the crash backtrace.
Stack dump:
0.	Program arguments: bin/swift-frontend /Users/mac/Desktop/test.swift -debug-diagnostic-names -emit-silgen
1.	Swift version 5.11-dev (LLVM 5601e23279f85d8, Swift 140caf63be3f0fe)
2.	Compiling with the current language version
3.	While evaluating request ASTLoweringRequest(Lowering AST to SIL for module test)
4.	While silgen emitFunction SIL function "@$s4testAA5pairsxxQp_t_q_xQp_ttx_q_txQp_t_tRvzRv_q_Rhzr0_lF".
 for 'test(pairs:)' (at /Users/mac/Desktop/test.swift:60:1)
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  swift-frontend           0x00000001164ab51b llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 43
1  swift-frontend           0x00000001164aa755 llvm::sys::RunSignalHandlers() + 85
2  swift-frontend           0x00000001164abb4e SignalHandler(int) + 270
3  libsystem_platform.dylib 0x00007ff81913037d _sigtramp + 29
4  libsystem_platform.dylib 000000000000000000 _sigtramp + 18446603370160258208
5  libsystem_c.dylib        0x00007ff819021a4d abort + 126
6  libsystem_c.dylib        0x00007ff819020d60 err + 0
7  swift-frontend           0x000000010f2df4ed swift::Lowering::RValue::extractElements(llvm::SmallVectorImpl<swift::Lowering::RValue>&) && + 525
8  swift-frontend           0x000000010f340763 (anonymous namespace)::ArgEmitter::emitExpanded(swift::Lowering::ArgumentSource&&, swift::Lowering::AbstractionPattern) + 531
9  swift-frontend           0x000000010f340c92 (anonymous namespace)::ArgEmitter::emitExpanded(swift::Lowering::ArgumentSource&&, swift::Lowering::AbstractionPattern) + 1858
10 swift-frontend           0x000000010f33deab (anonymous namespace)::ArgEmitter::emit(swift::Lowering::ArgumentSource&&, swift::Lowering::AbstractionPattern, llvm::Optional<swift::AnyFunctionType::Param>) + 171
11 swift-frontend           0x000000010f32c755 (anonymous namespace)::ArgEmitter::emitSingleArg(swift::Lowering::ArgumentSource&&, swift::Lowering::AbstractionPattern, llvm::Optional<swift::AnyFunctionType::Param>) + 549
12 swift-frontend           0x000000010f33aa0f (anonymous namespace)::ArgEmitter::emitPreparedArgs(swift::Lowering::PreparedArguments&&, swift::Lowering::AbstractionPattern) + 447
13 swift-frontend           0x000000010f3615a1 (anonymous namespace)::CallSite::emit(swift::Lowering::SILGenFunction&, swift::Lowering::AbstractionPattern, swift::CanTypeWrapper<swift::SILFunctionType>, (anonymous namespace)::ParamLowering&, llvm::SmallVectorImpl<swift::Lowering::ManagedValue>&, llvm::SmallVectorImpl<(anonymous namespace)::DelayedArgument>&, swift::ForeignInfo const&) && + 481
14 swift-frontend           0x000000010f36054e (anonymous namespace)::CallEmission::emitArgumentsForNormalApply(swift::Lowering::AbstractionPattern, swift::CanTypeWrapper<swift::SILFunctionType>, swift::ForeignInfo const&, llvm::SmallVectorImpl<swift::Lowering::ManagedValue>&, llvm::Optional<swift::SILLocation>&) + 1630
15 swift-frontend           0x000000010f35f890 (anonymous namespace)::CallEmission::applyNormalCall(swift::Lowering::SGFContext) + 1120
16 swift-frontend           0x000000010f35ddcd (anonymous namespace)::CallEmission::applyFirstLevelCallee(swift::Lowering::SGFContext) + 205
17 swift-frontend           0x000000010f32e740 (anonymous namespace)::CallEmission::apply(swift::Lowering::SGFContext) + 80
18 swift-frontend           0x000000010f32e0c8 swift::Lowering::SILGenFunction::emitApplyExpr(swift::ApplyExpr*, swift::Lowering::SGFContext) + 136
19 swift-frontend           0x000000010f4309ab (anonymous namespace)::RValueEmitter::visitApplyExpr(swift::ApplyExpr*, swift::Lowering::SGFContext) + 59
20 swift-frontend           0x000000010f41e0e8 swift::ASTVisitor<(anonymous namespace)::RValueEmitter, swift::Lowering::RValue, void, void, void, void, void, swift::Lowering::SGFContext>::visitCallExpr(swift::CallExpr*, swift::Lowering::SGFContext) + 56
21 swift-frontend           0x000000010f4078bc swift::ASTVisitor<(anonymous namespace)::RValueEmitter, swift::Lowering::RValue, void, void, void, void, void, swift::Lowering::SGFContext>::visit(swift::Expr*, swift::Lowering::SGFContext) + 2956
22 swift-frontend           0x000000010f3f8d23 swift::Lowering::SILGenFunction::emitRValue(swift::Expr*, swift::Lowering::SGFContext) + 195
23 swift-frontend           0x000000010f3f8b5b swift::Lowering::SILGenFunction::emitExprInto(swift::Expr*, swift::Lowering::Initialization*, llvm::Optional<swift::SILLocation>) + 283
24 swift-frontend           0x000000010f5345e7 swift::Lowering::SILGenFunction::emitReturnExpr(swift::SILLocation, swift::Expr*) + 631
25 swift-frontend           0x000000010f53796a (anonymous namespace)::StmtEmitter::visitReturnStmt(swift::ReturnStmt*) + 522
26 swift-frontend           0x000000010f533193 swift::ASTVisitor<(anonymous namespace)::StmtEmitter, void, void, void, void, void, void>::visit(swift::Stmt*) + 99
27 swift-frontend           0x000000010f53761d (anonymous namespace)::StmtEmitter::visitBraceStmt(swift::BraceStmt*) + 2045
28 swift-frontend           0x000000010f533181 swift::ASTVisitor<(anonymous namespace)::StmtEmitter, void, void, void, void, void, void>::visit(swift::Stmt*) + 81
29 swift-frontend           0x000000010f5330fa swift::Lowering::SILGenFunction::emitStmt(swift::Stmt*) + 42
30 swift-frontend           0x000000010f44f55a swift::Lowering::SILGenFunction::emitFunction(swift::FuncDecl*) + 842
31 swift-frontend           0x000000010f30452b swift::Lowering::SILGenModule::emitFunctionDefinition(swift::SILDeclRef, swift::SILFunction*) + 4411
32 swift-frontend           0x000000010f307a75 swift::Lowering::SILGenModule::emitOrDelayFunction(swift::SILDeclRef) + 501
33 swift-frontend           0x000000010f3033e5 swift::Lowering::SILGenModule::emitFunction(swift::FuncDecl*) + 309
34 swift-frontend           0x000000010f30329d swift::Lowering::SILGenModule::visitFuncDecl(swift::FuncDecl*) + 29
35 swift-frontend           0x000000010f302f64 swift::ASTVisitor<swift::Lowering::SILGenModule, void, void, void, void, void, void>::visit(swift::Decl*) + 996
36 swift-frontend           0x000000010f302b6b swift::Lowering::SILGenModule::visit(swift::Decl*) + 59
37 swift-frontend           0x000000010f30c72a (anonymous namespace)::SILGenModuleRAII::emitSourceFile(swift::SourceFile*) + 314
38 swift-frontend           0x000000010f30c2e4 swift::ASTLoweringRequest::evaluate(swift::Evaluator&, swift::ASTLoweringDescriptor) const + 916
39 swift-frontend           0x000000010f5322de std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule>> swift::SimpleRequest<swift::ASTLoweringRequest, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule>> (swift::ASTLoweringDescriptor), (swift::RequestFlags)9>::callDerived<0ul>(swift::Evaluator&, std::__1::integer_sequence<unsigned long, 0ul>) const + 142
40 swift-frontend           0x000000010f5321f8 swift::SimpleRequest<swift::ASTLoweringRequest, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule>> (swift::ASTLoweringDescriptor), (swift::RequestFlags)9>::evaluateRequest(swift::ASTLoweringRequest const&, swift::Evaluator&) + 40
41 swift-frontend           0x000000010f31eddc llvm::Expected<swift::ASTLoweringRequest::OutputType> swift::Evaluator::getResultUncached<swift::ASTLoweringRequest>(swift::ASTLoweringRequest const&) + 316
42 swift-frontend           0x000000010f30cee8 llvm::Expected<swift::ASTLoweringRequest::OutputType> swift::Evaluator::operator()<swift::ASTLoweringRequest, (void*)0>(swift::ASTLoweringRequest const&) + 40
43 swift-frontend           0x000000010f30cde0 swift::performASTLowering(swift::ModuleDecl*, swift::Lowering::TypeConverter&, swift::SILOptions const&, swift::IRGenOptions const*) + 256
44 swift-frontend           0x000000010e650cfb swift::performCompileStepsPostSema(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 283
45 swift-frontend           0x000000010e680103 performAction(swift::CompilerInstance&, int&, swift::FrontendObserver*)::$_29::operator()(swift::CompilerInstance&) const + 147
46 swift-frontend           0x000000010e68005d bool llvm::function_ref<bool (swift::CompilerInstance&)>::callback_fn<performAction(swift::CompilerInstance&, int&, swift::FrontendObserver*)::$_29>(long, swift::CompilerInstance&) + 29
47 swift-frontend           0x000000010e67f421 llvm::function_ref<bool (swift::CompilerInstance&)>::operator()(swift::CompilerInstance&) const + 33
48 swift-frontend           0x000000010e67e438 withSemanticAnalysis(swift::CompilerInstance&, swift::FrontendObserver*, llvm::function_ref<bool (swift::CompilerInstance&)>, bool) + 392
49 swift-frontend           0x000000010e676fa5 performAction(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 1349
50 swift-frontend           0x000000010e654186 performCompile(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 262
51 swift-frontend           0x000000010e652b60 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 2816
52 swift-frontend           0x000000010e5253df run_driver(llvm::StringRef, llvm::ArrayRef<char const*>, llvm::ArrayRef<char const*>) + 2431
53 swift-frontend           0x000000010e524057 swift::mainEntry(int, char const**) + 1543
54 swift-frontend           0x000000010e5236a2 main + 34
55 dyld                     0x00007ff818d7a3a6 start + 1942
Abort trap: 6
```

**Comment by vanvoorden** [comment] 2024-01-26 08:32
https://github.com/apple/swift/issues/67916#issuecomment-1911662421

@AnthonyLatsis I saw something similar… any ideas?

**Comment by AnthonyLatsis** [comment] 2024-02-24 16:35
Duplicate of #66392

**Closed by AnthonyLatsis** 2024-02-24 16:35 UTC
Labels: bug, duplicate, compiler, SILGen, generics, crash, tuples, expressions, parameter packs, assertion failure, swift 6.0
