### ISSUE TITLE
Accessing a property of an uninitialized instance results in a Runtime error

### ISSUE THREAD

**Issue by Alc-Alc** [swiftlang/swift#70908] opened 2024-01-13 17:01 UTC
### Description

The code produces a runtime error instead of a compile-time error. I would anticipate this to be an error that could be identified during compile-time.

It's worth mentioning that removing the `print` and having just `instance.x` allows the compiled binary to execute without any runtime errors (exit code 0).

### Reproduction

```swift
class SomeClass {
    let x: Int = 0
}

print(instance.x)
var instance = SomeClass()
```

### Expected behavior

I expect this to be a compile-time error

### Environment

swift-driver version: 1.87.1 Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)
Target: arm64-apple-macosx14.0

**Comment by jamieQ** [comment] 2024-01-15 16:20
same issue as https://github.com/apple/swift/issues/70380 i believe

**Comment by AnthonyLatsis** [comment] 2024-02-29 18:01
Duplicate of #70323

**Closed by AnthonyLatsis** 2024-02-29 18:01 UTC
Labels: bug, duplicate, compiler, definite initialization, accepts invalid, crash, SIL, memory safety, swift 6.0, script mode
