### ISSUE TITLE
Parameter pack fails to see type without explicit type info

### ISSUE THREAD

**Issue by MacAndor** [swiftlang/swift#74179] opened 2024-06-06 15:09 UTC
### Description

Shape recognition of parameter pack has a bug.
Errors:
```
Cannot convert return expression of type 'S<repeat each T>' to return type 'S<repeat each T, U>'
Pack expansion requires that 'each T' and 'repeat each T, U' have the same shape
```

### Reproduction

```swift
struct S<each T> {

    let t: (repeat each T)

    func build<U>(_ u: U) -> S<repeat each T, U> {
        S(t: (repeat each t, u))

        // NOTE: the following works
        // S<repeat each T, U>(t: (repeat each t, u))
    }
}
```

### Expected behavior

Return type should not require explicit type spec.

```swift
let x = S(t: ("Hello", 1))
let y = x.build(2.0)
// Expected type of y is S<String, Int, Double>
```

### Environment

Apple Swift version 6.0-dev (LLVM 5f87d6ee2f8c800, Swift 5c01ca13866debd)
Target: arm64-apple-macosx14.0

**Comment by MacAndor** [comment] 2024-07-07 15:48
This might be expected behavior, S without explicit generic type info may inherit the generic type of the instance of self. Can someone confirm that this is the case?

**Comment by AnthonyLatsis** [comment] 2024-07-07 16:11
Expected if only in that this is known to have always been the case. Otherwise, there appears to be a wide agreement that the behavior is undesirable. Not an easy problem to solve, though.

**Comment by AnthonyLatsis** [comment] 2024-07-07 16:11
Duplicate of #44398

**Closed by AnthonyLatsis** 2024-07-07 16:11 UTC
Labels: bug, duplicate, compiler, type checker, swift evolution proposal needed, generics, TypeResolver, type inference, expressions, unexpected error, parameter packs, swift 6.0
