### ISSUE TITLE
 “Switch must be exhaustive” for tuple enums

### ISSUE THREAD

**Issue by biajoeknee** [swiftlang/swift#62380] opened 2022-12-03 03:51 UTC
**Motivation**
When switching on an enumeration, if you write the switch without putting any cases, Xcode will complain that the "Switch must be exhaustive". If you click the error, it gives you the option of fixing it, and in doing so autocompleting the cases for you.

However, this doesn't work when switching on a tuple of enumerations. The same error will be displayed, but when clicking `fix it`, this is what will result:
```swift
enum Color {
    case red, blue
}
enum Number {
    case one, two
}
let tuple=(Color.red, Number.one)
switch tuple {
case (_, _):
}
```

**Solution**
What I'm proposing is that when clicking `fix it` for tuple enumerations this results:
```swift
switch tuple {
case (.red, .one):
case (.red, .two):
case (.blue, .one):
case (.blue, .two):
}
```

**Alternatives considered**
None.

**Additional context**
https://forums.swift.org/t/switch-must-be-exhaustive-for-tuple-enums/61791

**Comment by CodaFi** [comment] 2022-12-10 21:04
Dupe of https://github.com/apple/swift/issues/49205

**Closed by CodaFi** 2022-12-10 21:04 UTC
Labels: compiler, feature, diagnostics QoI, type checker, fix-its, switch exhaustivity, enum
