### ISSUE TITLE
Visibility Issue with ExtensionMacro in Different Files When Attached to Protocol

### ISSUE THREAD

**Issue by hainayanda** [swiftlang/swift#74644] opened 2024-06-22 12:45 UTC
### Description

It appears that extension methods generated by ExtensionMacro attached to protocols are not visible across different files. This issue persists even though it was previously reported and marked as closed.

### Reproduction

```swift
// Inside my MacroCompilerPlugin Module

public struct FooExtensionMacro: ExtensionMacro {
    public static func expansion(of node: AttributeSyntax, attachedTo declaration: some DeclGroupSyntax, providingExtensionsOf type: some TypeSyntaxProtocol, conformingTo protocols: [TypeSyntax], in context: some MacroExpansionContext) throws -> [ExtensionDeclSyntax] {
        let decl: DeclSyntax =
        """
        extension Foo {
          var foo: String { "foo" }
          func printFoo() {
            print(foo)
          }
        }
        """
        guard let extensionDecl = decl.as(ExtensionDeclSyntax.self) else {
            return []
        }
        
        return [extensionDecl]
    }
}

// Inside my MacroLibrary module

@attached(extension, names: named(foo), named(printFoo))
public macro FooExtension() = #externalMacro(module: "MacroCompilerPlugin", type: "FooExtensionMacro")

// Inside the client project / final target

import MacroLibrary

@FooExtension    // <--- apply the macro to generate default property and method
protocol Foo {
    var foo: String { get }
}

/// The above correctly expands to:
///
/// protocol Foo {
///   var foo: String { get }
/// }
///
/// extension Foo {
///   var foo: String { "foo" }
///   func printFoo() {
///     print(foo)
///   }
/// }

extension String: Foo { }   // <--- This compiles! Hooray, that means the default implementation of the property foo from the extension macro worked!

"Test".printFoo()   // <--- This doesn't compile ("Value of type ''String" has no member 'printFoo'"). This seems to indicate that the compiler can't "see" the printFoo() extension method from the ExtensionMacro, even though it can see the default implementation of the protocol's foo property from the same macro.
```

### Expected behavior

"Test".printFoo()   // <-- Should compile and print "foo" based on the extension method synthesized by the ExtensionMacro 

### Environment

swift-driver version: 1.90.11.1 Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
Xcode: Version 15.4 (15F31d)
Target: arm64-apple-macosx14.0

### Additional information

It was noted in the previous issue (reference: [#69073](https://github.com/swiftlang/swift/issues/69073)) that the visibility problem occurs only in different files. When all the related code is in the same file, the generated extension methods are visible and work as expected.

```swift
// Same file
import MacroLibrary

@FooExtension
protocol Foo {
    var foo: String { get }
}

extension String: Foo { }

"Test".printFoo()   // prints "foo"
```

However, the method is not visible if the call to printFoo() is made in a different file.

```swift
// Different file
"Test".printFoo()  // <---- Error: "Value of type ''String" has no member 'printFoo'"
```

This behavior suggests that the ExtensionMacro added members might be scoped as `fileprivate` even when generated with an `internal` or even `public` modifier.

**Comment by xedin** [comment] 2024-08-02 17:51
Looks like this has been fixed on main and Doug added a test-case in 8e4484660ae3daebcd68787417156f2746d03bbe.

Please use the latest main branch toolchain from swift.org to verify and if it's still reproducible please feel free to re-open.

**Closed by xedin** 2024-08-02 17:51 UTC
Labels: bug, swift macro
