### ISSUE TITLE
Assertion failed: (origPackType.matchesPack(substPackType)), function PackElementGenerator, file AbstractionPattern.cpp, line 804.

### ISSUE THREAD

**Issue by dnadoba** [swiftlang/swift#67917] opened 2023-08-14 18:01 UTC
```swift
protocol BarProtocol {}

struct Foo<each Bar: BarProtocol> {
    var bar: (repeat each Bar)
    init(bar: (repeat each Bar)) {
        self.bar = bar
    }
    
    init(@FooBuilder builder: () -> Self) {
        self = builder()
    }
}

@resultBuilder
struct FooBuilder {
    @inlinable
    public static func buildPartialBlock<Bar: BarProtocol>(first: Bar) -> Foo<Bar> {
        Foo(bar: first)
    }
    
    @inlinable
    public static func buildPartialBlock<each Bar: BarProtocol, NextBar: BarProtocol>(
        accumulated: Foo<repeat each Bar>,
        next: NextBar
    ) -> (Foo<repeat each Bar, NextBar>) {
        Foo(bar: (repeat each accumulated.bar, next))
    }
}

extension Int: BarProtocol {}

@main
struct Main {
    static func main() async throws {
        // crashes the compiler:
        // Assertion failed: (origPackType.matchesPack(substPackType)), function PackElementGenerator, file AbstractionPattern.cpp, line 804.
        let result = Foo.init(builder: {
            1
            2
        })
    }
}
```
```
Assertion failed: (origPackType.matchesPack(substPackType)), function PackElementGenerator, file AbstractionPattern.cpp, line 804.
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the crash backtrace.
Stack dump:
0.	Program arguments: /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2023-08-12-a.xctoolchain/usr/bin/swift-frontend -frontend -c -primary-file /Users/davidnadoba/Repositories/PlaygroundExecutbale/Sources/PlaygroundExecutbale/Executable.swift -emit-dependencies-path /Users/davidnadoba/Library/Developer/Xcode/DerivedData/PlaygroundExecutbale-dnjdfgihtwpodwcvmuotcusgvyuw/Build/Intermediates.noindex/PlaygroundExecutbale.build/Debug/PlaygroundExecutbale.build/Objects-normal/arm64/Executable.d -emit-const-values-path /Users/davidnadoba/Library/Developer/Xcode/DerivedData/PlaygroundExecutbale-dnjdfgihtwpodwcvmuotcusgvyuw/Build/Intermediates.noindex/PlaygroundExecutbale.build/Debug/PlaygroundExecutbale.build/Objects-normal/arm64/Executable.swiftconstvalues -emit-reference-dependencies-path /Users/davidnadoba/Library/Developer/Xcode/DerivedData/PlaygroundExecutbale-dnjdfgihtwpodwcvmuotcusgvyuw/Build/Intermediates.noindex/PlaygroundExecutbale.build/Debug/PlaygroundExecutbale.build/Objects-normal/arm64/Executable.swiftdeps -serialize-diagnostics-path /Users/davidnadoba/Library/Developer/Xcode/DerivedData/PlaygroundExecutbale-dnjdfgihtwpodwcvmuotcusgvyuw/Build/Intermediates.noindex/PlaygroundExecutbale.build/Debug/PlaygroundExecutbale.build/Objects-normal/arm64/Executable.dia -target arm64-apple-macos14.0 -Xllvm -aarch64-use-tbi -enable-objc-interop -sdk "/Applications/Xcode 15.0 Beta6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk" -I /Users/davidnadoba/Library/Developer/Xcode/DerivedData/PlaygroundExecutbale-dnjdfgihtwpodwcvmuotcusgvyuw/Build/Products/Debug -I "/Applications/Xcode 15.0 Beta6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib" -F /Users/davidnadoba/Library/Developer/Xcode/DerivedData/PlaygroundExecutbale-dnjdfgihtwpodwcvmuotcusgvyuw/Build/Products/Debug/PackageFrameworks -F /Users/davidnadoba/Library/Developer/Xcode/DerivedData/PlaygroundExecutbale-dnjdfgihtwpodwcvmuotcusgvyuw/Build/Products/Debug/PackageFrameworks -F /Users/davidnadoba/Library/Developer/Xcode/DerivedData/PlaygroundExecutbale-dnjdfgihtwpodwcvmuotcusgvyuw/Build/Products/Debug/PackageFrameworks -F /Users/davidnadoba/Library/Developer/Xcode/DerivedData/PlaygroundExecutbale-dnjdfgihtwpodwcvmuotcusgvyuw/Build/Products/Debug/PackageFrameworks -F /Users/davidnadoba/Library/Developer/Xcode/DerivedData/PlaygroundExecutbale-dnjdfgihtwpodwcvmuotcusgvyuw/Build/Products/Debug/PackageFrameworks -F /Users/davidnadoba/Library/Developer/Xcode/DerivedData/PlaygroundExecutbale-dnjdfgihtwpodwcvmuotcusgvyuw/Build/Products/Debug/PackageFrameworks -F /Users/davidnadoba/Library/Developer/Xcode/DerivedData/PlaygroundExecutbale-dnjdfgihtwpodwcvmuotcusgvyuw/Build/Products/Debug/PackageFrameworks -F /Users/davidnadoba/Library/Developer/Xcode/DerivedData/PlaygroundExecutbale-dnjdfgihtwpodwcvmuotcusgvyuw/Build/Products/Debug/PackageFrameworks -F /Users/davidnadoba/Library/Developer/Xcode/DerivedData/PlaygroundExecutbale-dnjdfgihtwpodwcvmuotcusgvyuw/Build/Products/Debug -F "/Applications/Xcode 15.0 Beta6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks" -no-color-diagnostics -enable-testing -g -module-cache-path /Users/davidnadoba/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -swift-version 5 -enforce-exclusivity=checked -Onone -D SWIFT_PACKAGE -D DEBUG -D Xcode -warn-concurrency -external-plugin-path "/Applications/Xcode 15.0 Beta6.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/host/plugins#/Applications/Xcode 15.0 Beta6.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-plugin-server" -external-plugin-path "/Applications/Xcode 15.0 Beta6.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/local/lib/swift/host/plugins#/Applications/Xcode 15.0 Beta6.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-plugin-server" -serialize-debugging-options -package-name playgroundexecutbale -const-gather-protocols-file /Users/davidnadoba/Library/Developer/Xcode/DerivedData/PlaygroundExecutbale-dnjdfgihtwpodwcvmuotcusgvyuw/Build/Intermediates.noindex/PlaygroundExecutbale.build/Debug/PlaygroundExecutbale.build/Objects-normal/arm64/PlaygroundExecutbale_const_extract_protocols.json -empty-abi-descriptor -validate-clang-modules-once -clang-build-session-file /Users/davidnadoba/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -Xcc -working-directory -Xcc /Users/davidnadoba/Repositories/PlaygroundExecutbale -resource-dir /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2023-08-12-a.xctoolchain/usr/lib/swift -enable-anonymous-context-mangled-names -Xcc -fmodule-map-file=/Users/davidnadoba/Library/Developer/Xcode/DerivedData/PlaygroundExecutbale-dnjdfgihtwpodwcvmuotcusgvyuw/Build/Intermediates.noindex/GeneratedModuleMaps/CNIOLinux.modulemap -Xcc -fmodule-map-file=/Users/davidnadoba/Library/Developer/Xcode/DerivedData/PlaygroundExecutbale-dnjdfgihtwpodwcvmuotcusgvyuw/Build/Intermediates.noindex/GeneratedModuleMaps/CNIOAtomics.modulemap -Xcc -I/Users/davidnadoba/Library/Developer/Xcode/DerivedData/PlaygroundExecutbale-dnjdfgihtwpodwcvmuotcusgvyuw/SourcePackages/checkouts/swift-atomics/Sources/_AtomicsShims/include -Xcc -I/Users/davidnadoba/Library/Developer/Xcode/DerivedData/PlaygroundExecutbale-dnjdfgihtwpodwcvmuotcusgvyuw/SourcePackages/checkouts/swift-nio/Sources/CNIOWindows/include -Xcc -I/Users/davidnadoba/Library/Developer/Xcode/DerivedData/PlaygroundExecutbale-dnjdfgihtwpodwcvmuotcusgvyuw/SourcePackages/checkouts/swift-nio/Sources/CNIOLinux/include -Xcc -I/Users/davidnadoba/Library/Developer/Xcode/DerivedData/PlaygroundExecutbale-dnjdfgihtwpodwcvmuotcusgvyuw/SourcePackages/checkouts/swift-nio/Sources/CNIOAtomics/include -Xcc -I/Users/davidnadoba/Library/Developer/Xcode/DerivedData/PlaygroundExecutbale-dnjdfgihtwpodwcvmuotcusgvyuw/Build/Products/Debug/include -Xcc -I/Users/davidnadoba/Library/Developer/Xcode/DerivedData/PlaygroundExecutbale-dnjdfgihtwpodwcvmuotcusgvyuw/Build/Intermediates.noindex/PlaygroundExecutbale.build/Debug/PlaygroundExecutbale.build/DerivedSources-normal/arm64 -Xcc -I/Users/davidnadoba/Library/Developer/Xcode/DerivedData/PlaygroundExecutbale-dnjdfgihtwpodwcvmuotcusgvyuw/Build/Intermediates.noindex/PlaygroundExecutbale.build/Debug/PlaygroundExecutbale.build/DerivedSources/arm64 -Xcc -I/Users/davidnadoba/Library/Developer/Xcode/DerivedData/PlaygroundExecutbale-dnjdfgihtwpodwcvmuotcusgvyuw/Build/Intermediates.noindex/PlaygroundExecutbale.build/Debug/PlaygroundExecutbale.build/DerivedSources -Xcc -DSWIFT_PACKAGE -Xcc -DDEBUG=1 -module-name PlaygroundExecutbale -frontend-parseable-output -disable-clang-spi -target-sdk-version 14.0 -target-sdk-name macosx14.0 -external-plugin-path "/Applications/Xcode 15.0 Beta6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/lib/swift/host/plugins#/Applications/Xcode 15.0 Beta6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/bin/swift-plugin-server" -external-plugin-path "/Applications/Xcode 15.0 Beta6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/local/lib/swift/host/plugins#/Applications/Xcode 15.0 Beta6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/bin/swift-plugin-server" -external-plugin-path "/Applications/Xcode 15.0 Beta6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib/swift/host/plugins#/Applications/Xcode 15.0 Beta6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin/swift-plugin-server" -external-plugin-path "/Applications/Xcode 15.0 Beta6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/local/lib/swift/host/plugins#/Applications/Xcode 15.0 Beta6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin/swift-plugin-server" -plugin-path /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2023-08-12-a.xctoolchain/usr/lib/swift/host/plugins -plugin-path /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2023-08-12-a.xctoolchain/usr/local/lib/swift/host/plugins -parse-as-library -o /Users/davidnadoba/Library/Developer/Xcode/DerivedData/PlaygroundExecutbale-dnjdfgihtwpodwcvmuotcusgvyuw/Build/Intermediates.noindex/PlaygroundExecutbale.build/Debug/PlaygroundExecutbale.build/Objects-normal/arm64/Executable.o -index-unit-output-path /PlaygroundExecutbale.build/Debug/PlaygroundExecutbale.build/Objects-normal/arm64/Executable.o -index-store-path /Users/davidnadoba/Library/Developer/Xcode/DerivedData/PlaygroundExecutbale-dnjdfgihtwpodwcvmuotcusgvyuw/Index.noindex/DataStore -index-system-modules
1.	Apple Swift version 5.9-dev (LLVM fd38736063c15cd, Swift a533c63d783f5b8)
2.	Compiling with the current language version
3.	While evaluating request ASTLoweringRequest(Lowering AST to SIL for file "/Users/davidnadoba/Repositories/PlaygroundExecutbale/Sources/PlaygroundExecutbale/Executable.swift")
4.	While silgen emitFunction SIL function "@$s20PlaygroundExecutbale4MainV4mainyyYaKFZ".
 for 'main()' (at /Users/davidnadoba/Repositories/PlaygroundExecutbale/Sources/PlaygroundExecutbale/Executable.swift:34:5)
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  swift-frontend           0x0000000109208d80 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 56
1  swift-frontend           0x0000000109208124 llvm::sys::RunSignalHandlers() + 112
2  swift-frontend           0x00000001092093c0 SignalHandler(int) + 304
3  libsystem_platform.dylib 0x0000000185845a24 _sigtramp + 56
4  libsystem_pthread.dylib  0x0000000185816cc0 pthread_kill + 288
5  libsystem_c.dylib        0x0000000185726a80 abort + 180
6  libsystem_c.dylib        0x0000000185725d9c err + 0
7  swift-frontend           0x00000001094ec7c4 swift::Lowering::PackElementGenerator::loadElement() (.cold.1) + 0
8  swift-frontend           0x00000001050840d0 swift::Lowering::PackElementGenerator::PackElementGenerator(swift::Lowering::AbstractionPattern, swift::CanTypeWrapper<swift::PackType>) + 208
9  swift-frontend           0x0000000105083bf0 swift::Lowering::AbstractionPattern::forEachPackElement(swift::CanTypeWrapper<swift::PackType>, llvm::function_ref<void (swift::Lowering::PackElementGenerator&)>) const + 56
10 swift-frontend           0x000000010508a4bc swift::CanTypeVisitor<(anonymous namespace)::SubstFunctionTypePatternVisitor, swift::CanType, swift::Lowering::AbstractionPattern>::visit(swift::CanType, swift::Lowering::AbstractionPattern) + 2420
11 swift-frontend           0x0000000105089390 (anonymous namespace)::SubstFunctionTypePatternVisitor::visit(swift::CanType, swift::Lowering::AbstractionPattern) + 940
12 swift-frontend           0x000000010508ad8c (anonymous namespace)::SubstFunctionTypePatternVisitor::handleGenericNominalType(swift::Lowering::AbstractionPattern, swift::CanType) + 860
13 swift-frontend           0x0000000105089ee4 swift::CanTypeVisitor<(anonymous namespace)::SubstFunctionTypePatternVisitor, swift::CanType, swift::Lowering::AbstractionPattern>::visit(swift::CanType, swift::Lowering::AbstractionPattern) + 924
14 swift-frontend           0x0000000105089390 (anonymous namespace)::SubstFunctionTypePatternVisitor::visit(swift::CanType, swift::Lowering::AbstractionPattern) + 940
15 swift-frontend           0x0000000105088df0 (anonymous namespace)::SubstFunctionTypePatternVisitor::handleUnabstractedFunctionType(swift::CanTypeWrapper<swift::AnyFunctionType>, swift::Lowering::AbstractionPattern, swift::CanType, swift::Lowering::AbstractionPattern) + 264
16 swift-frontend           0x0000000105088a50 swift::Lowering::AbstractionPattern::getSubstFunctionTypePattern(swift::CanTypeWrapper<swift::AnyFunctionType>, swift::Lowering::TypeConverter&, swift::Lowering::AbstractionPattern, swift::CanType, bool&) const + 392
17 swift-frontend           0x00000001050cea2c getSILFunctionType(swift::Lowering::TypeConverter&, swift::TypeExpansionContext, swift::Lowering::AbstractionPattern, swift::CanTypeWrapper<swift::AnyFunctionType>, swift::SILExtInfoBuilder, (anonymous namespace)::Conventions const&, swift::ForeignInfo const&, llvm::Optional<swift::SILDeclRef>, llvm::Optional<swift::SILDeclRef>, llvm::Optional<swift::SubstitutionMap>, swift::ProtocolConformanceRef) + 1708
18 swift-frontend           0x00000001050c6774 getNativeSILFunctionType(swift::Lowering::TypeConverter&, swift::TypeExpansionContext, swift::Lowering::AbstractionPattern, swift::CanTypeWrapper<swift::AnyFunctionType>, swift::SILExtInfoBuilder, llvm::Optional<swift::SILDeclRef>, llvm::Optional<swift::SILDeclRef>, llvm::Optional<swift::SubstitutionMap>, swift::ProtocolConformanceRef) + 1376
19 swift-frontend           0x00000001050c98f8 getUncachedSILFunctionTypeForConstant(swift::Lowering::TypeConverter&, swift::TypeExpansionContext, swift::SILDeclRef, swift::Lowering::TypeConverter::LoweredFormalTypes) + 1268
20 swift-frontend           0x00000001050ca27c swift::Lowering::TypeConverter::getConstantInfo(swift::TypeExpansionContext, swift::SILDeclRef) + 220
21 swift-frontend           0x00000001050c07e8 swift::SILFunctionBuilder::getOrCreateFunction(swift::SILLocation, swift::SILDeclRef, swift::ForDefinition_t, llvm::function_ref<swift::SILFunction* (swift::SILLocation, swift::SILDeclRef)>, swift::ProfileCounter) + 128
22 swift-frontend           0x0000000104960b0c swift::Lowering::SILGenModule::getFunction(swift::SILDeclRef, swift::ForDefinition_t) + 344
23 swift-frontend           0x0000000104964e24 swift::Lowering::SILGenModule::emitClosure(swift::AbstractClosureExpr*) + 100
24 swift-frontend           0x00000001049d6d90 (anonymous namespace)::RValueEmitter::visitAbstractClosureExpr(swift::AbstractClosureExpr*, swift::Lowering::SGFContext) + 364
25 swift-frontend           0x00000001049c1ddc swift::Lowering::SILGenFunction::emitRValueAsSingleValue(swift::Expr*, swift::Lowering::SGFContext) + 72
26 swift-frontend           0x00000001049a9f28 swift::Lowering::SILGenFunction::emitConvertedRValue(swift::SILLocation, swift::Lowering::Conversion const&, swift::Lowering::SGFContext, llvm::function_ref<swift::Lowering::ManagedValue (swift::Lowering::SILGenFunction&, swift::SILLocation, swift::Lowering::SGFContext)>) + 268
27 swift-frontend           0x000000010494ce4c swift::Lowering::ArgumentSource::getConverted(swift::Lowering::SILGenFunction&, swift::Lowering::Conversion const&, swift::Lowering::SGFContext) && + 200
28 swift-frontend           0x000000010497dd70 (anonymous namespace)::ArgEmitter::emit(swift::Lowering::ArgumentSource&&, swift::Lowering::AbstractionPattern, llvm::Optional<swift::AnyFunctionType::Param>) + 3492
29 swift-frontend           0x000000010496fa90 (anonymous namespace)::ArgEmitter::emitSingleArg(swift::Lowering::ArgumentSource&&, swift::Lowering::AbstractionPattern, llvm::Optional<swift::AnyFunctionType::Param>) + 424
30 swift-frontend           0x000000010497c91c (anonymous namespace)::ArgEmitter::emitPreparedArgs(swift::Lowering::PreparedArguments&&, swift::Lowering::AbstractionPattern) + 192
31 swift-frontend           0x0000000104986e28 (anonymous namespace)::CallSite::emit(swift::Lowering::SILGenFunction&, swift::Lowering::AbstractionPattern, swift::CanTypeWrapper<swift::SILFunctionType>, (anonymous namespace)::ParamLowering&, llvm::SmallVectorImpl<swift::Lowering::ManagedValue>&, llvm::SmallVectorImpl<(anonymous namespace)::DelayedArgument>&, swift::ForeignInfo const&) && + 536
32 swift-frontend           0x00000001049867a8 (anonymous namespace)::CallEmission::emitArgumentsForNormalApply(swift::Lowering::AbstractionPattern, swift::CanTypeWrapper<swift::SILFunctionType>, swift::ForeignInfo const&, llvm::SmallVectorImpl<swift::Lowering::ManagedValue>&, llvm::Optional<swift::SILLocation>&) + 1112
33 swift-frontend           0x0000000104973230 (anonymous namespace)::CallEmission::apply(swift::Lowering::SGFContext) + 2288
34 swift-frontend           0x0000000104971660 swift::Lowering::SILGenFunction::emitApplyExpr(swift::ApplyExpr*, swift::Lowering::SGFContext) + 1996
35 swift-frontend           0x00000001049bfa88 swift::Lowering::SILGenFunction::emitExprInto(swift::Expr*, swift::Lowering::Initialization*, llvm::Optional<swift::SILLocation>) + 248
36 swift-frontend           0x00000001049aea98 swift::Lowering::SILGenFunction::emitPatternBinding(swift::PatternBindingDecl*, unsigned int, bool) + 1412
37 swift-frontend           0x00000001049aecb8 swift::Lowering::SILGenFunction::visitPatternBindingDecl(swift::PatternBindingDecl*, bool) + 64
38 swift-frontend           0x0000000104a36578 swift::ASTVisitor<(anonymous namespace)::StmtEmitter, void, void, void, void, void, void>::visit(swift::Stmt*) + 3964
39 swift-frontend           0x0000000104a355f0 swift::Lowering::SILGenFunction::emitStmt(swift::Stmt*) + 24
40 swift-frontend           0x00000001049e14dc swift::Lowering::SILGenFunction::emitFunction(swift::FuncDecl*) + 408
41 swift-frontend           0x00000001049636f4 swift::Lowering::SILGenModule::emitFunctionDefinition(swift::SILDeclRef, swift::SILFunction*) + 9180
42 swift-frontend           0x0000000104963f88 swift::Lowering::SILGenModule::emitOrDelayFunction(swift::SILDeclRef) + 204
43 swift-frontend           0x0000000104961300 swift::Lowering::SILGenModule::emitFunction(swift::FuncDecl*) + 164
44 swift-frontend           0x0000000104a4553c (anonymous namespace)::SILGenType::visitFuncDecl(swift::FuncDecl*) + 28
45 swift-frontend           0x0000000104a42484 (anonymous namespace)::SILGenType::emitType() + 252
46 swift-frontend           0x0000000104a4237c swift::Lowering::SILGenModule::visitNominalTypeDecl(swift::NominalTypeDecl*) + 24
47 swift-frontend           0x0000000104966738 swift::ASTLoweringRequest::evaluate(swift::Evaluator&, swift::ASTLoweringDescriptor) const + 976
48 swift-frontend           0x0000000104a3508c swift::SimpleRequest<swift::ASTLoweringRequest, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule>> (swift::ASTLoweringDescriptor), (swift::RequestFlags)9>::evaluateRequest(swift::ASTLoweringRequest const&, swift::Evaluator&) + 148
49 swift-frontend           0x000000010496953c llvm::Expected<swift::ASTLoweringRequest::OutputType> swift::Evaluator::getResultUncached<swift::ASTLoweringRequest>(swift::ASTLoweringRequest const&) + 396
50 swift-frontend           0x0000000104966f20 swift::performASTLowering(swift::FileUnit&, swift::Lowering::TypeConverter&, swift::SILOptions const&, swift::IRGenOptions const*) + 100
51 swift-frontend           0x00000001043fc9fc swift::performCompileStepsPostSema(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 556
52 swift-frontend           0x000000010440bdd4 withSemanticAnalysis(swift::CompilerInstance&, swift::FrontendObserver*, llvm::function_ref<bool (swift::CompilerInstance&)>, bool) + 160
53 swift-frontend           0x00000001043ff584 performCompile(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 740
54 swift-frontend           0x00000001043fe508 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 2496
55 swift-frontend           0x0000000104237f04 swift::mainEntry(int, char const**) + 2144
56 dyld                     0x000000018549d058 start + 2224
```

with latest nightly toolchain `swift-DEVELOPMENT-SNAPSHOT-2023-08-12-a`

**Comment by dnadoba** [comment] 2023-08-14 18:02
rdar://113862929

**Comment by xAlien95** [comment] 2023-08-14 19:37
#67766 may be a reduced example.

**Comment by AnthonyLatsis** [comment] 2024-07-15 21:43
Duplicate of #67766

**Closed by AnthonyLatsis** 2024-07-15 21:43 UTC
Labels: bug, duplicate, compiler, SILGen, generics, crash, closures, expressions, parameter packs, swift 6.0
