### ISSUE TITLE
Swift frontend crashes when there's no setter in Property Wrapper subscript. (silgen)

### ISSUE THREAD

**Issue by MaximBazarov** [swiftlang/swift#67561] opened 2023-07-27 08:02 UTC
**Description**

When using property wrapper subscript:
```swift
static subscript<EnclosingObject: AnyObject>(
        _enclosingInstance instance: EnclosingObject,
        wrapped wrappedKeyPath: KeyPath<EnclosingObject, String>,
        storage storageKeyPath: KeyPath<EnclosingObject, Self>
    ) -> String {
        get {
            return ""
        }
//        set {} // add setter to fix the crash
    }
```
then using it as
```swift
@DefaultObserve(\.name) var s
```
compiler crashes: 

```
While evaluating request ASTLoweringRequest(Lowering AST to SIL for module PropertyWrapperNoSetterCrashTests)
4.	While silgen emitFunction SIL function "@$s33PropertyWrapperNoSetterCrashTestsAAC1sSSvs".
 for setter for s
```

adding 
```swift
...
set {}
```
fixes the crash.

**Steps to reproduce**
Run `swift test` on the following project:

[PropertyWrapperNoSetterCrash.zip](https://github.com/apple/swift/files/12180769/PropertyWrapperNoSetterCrash.zip)

**Expected behavior**

Compiles with no crash, to allow property wrapper to be read only.

**Environment**
- Swift compiler version info swift-driver version: 1.75.2 Apple Swift version 5.8.1 (swiftlang-5.8.0.124.5 clang-1403.0.22.11.100)
- Xcode version info Xcode 14.3.1 Build version 14E300c
- Deployment target: arm64-apple-macosx13.0

Stack trace:
```
Building for debugging...
error: emit-module command failed due to signal 5 (use -v to see invocation)
error: compile command failed due to signal 5 (use -v to see invocation)
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the crash backtrace.
Stack dump:
<redacted>
1.	Apple Swift version 5.8.1 (swiftlang-5.8.0.124.5 clang-1403.0.22.11.100)
2.	Compiling with the current language version
3.	While evaluating request ASTLoweringRequest(Lowering AST to SIL for module PropertyWrapperNoSetterCrashTests)
4.	While silgen emitFunction SIL function "@$s33PropertyWrapperNoSetterCrashTestsAAC1sSSvs".
 for setter for s (at Developer/PropertyWrapperNoSetterCrash/Tests/PropertyWrapperNoSetterCrashTests/PropertyWrapperNoSetterCrashTests.swift:7:33)
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  swift-frontend           0x0000000107a5b2a8 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 56
1  swift-frontend           0x0000000107a5a28c llvm::sys::RunSignalHandlers() + 112
2  swift-frontend           0x0000000107a5b8b8 SignalHandler(int) + 344
3  libsystem_platform.dylib 0x00000001a5486a24 _sigtramp + 56
4  swift-frontend           0x00000001030186c0 swift::Lowering::LValue::addMemberSubscriptComponent(swift::Lowering::SILGenFunction&, swift::SILLocation, swift::SubscriptDecl*, swift::SubstitutionMap, swift::Lowering::LValueOptions, bool, swift::Lowering::SGFAccessKind, swift::AccessStrategy, swift::CanType, swift::Lowering::PreparedArguments&&, swift::ArgumentList*, bool, llvm::Optional<swift::ActorIsolation>) + 1240
5  swift-frontend           0x000000010301a94c swift::ASTVisitor<SILGenLValue, swift::Lowering::LValue, void, void, void, void, void, swift::Lowering::SGFAccessKind, swift::Lowering::LValueOptions>::visit(swift::Expr*, swift::Lowering::SGFAccessKind, swift::Lowering::LValueOptions) + 7248
6  swift-frontend           0x0000000103018c1c swift::Lowering::SILGenFunction::emitLValue(swift::Expr*, swift::Lowering::SGFAccessKind, swift::Lowering::LValueOptions) + 48
7  swift-frontend           0x0000000102ffea08 (anonymous namespace)::RValueEmitter::visitAssignExpr(swift::AssignExpr*, swift::Lowering::SGFContext) + 976
8  swift-frontend           0x0000000102fe3394 swift::Lowering::SILGenFunction::emitIgnoredExpr(swift::Expr*) + 624
9  swift-frontend           0x000000010305a7cc swift::ASTVisitor<(anonymous namespace)::StmtEmitter, void, void, void, void, void, void>::visit(swift::Stmt*) + 3056
10 swift-frontend           0x000000010300b034 swift::Lowering::SILGenFunction::emitFunction(swift::FuncDecl*) + 728
11 swift-frontend           0x0000000102f65eac swift::Lowering::SILGenModule::emitFunctionDefinition(swift::SILDeclRef, swift::SILFunction*) + 7208
12 swift-frontend           0x0000000102f677d8 emitOrDelayFunction(swift::Lowering::SILGenModule&, swift::SILDeclRef) + 164
13 swift-frontend           0x0000000102f64270 swift::Lowering::SILGenModule::emitFunction(swift::FuncDecl*) + 320
14 swift-frontend           0x000000010306a624 void llvm::function_ref<void (swift::AccessorDecl*)>::callback_fn<(anonymous namespace)::SILGenType::visitAccessors(swift::AbstractStorageDecl*)::'lambda'(swift::AccessorDecl*)>(long, swift::AccessorDecl*) + 36
15 swift-frontend           0x0000000103f8769c swift::AbstractStorageDecl::visitExpectedOpaqueAccessors(llvm::function_ref<void (swift::AccessorKind)>) const + 240
16 swift-frontend           0x000000010306a5ec (anonymous namespace)::SILGenType::visitAbstractStorageDecl(swift::AbstractStorageDecl*) + 276
17 swift-frontend           0x000000010306a3ec (anonymous namespace)::SILGenType::visitVarDecl(swift::VarDecl*) + 332
18 swift-frontend           0x0000000103066b70 (anonymous namespace)::SILGenType::emitType() + 300
19 swift-frontend           0x0000000102f69000 swift::ASTVisitor<swift::Lowering::SILGenModule, void, void, void, void, void, void>::visit(swift::Decl*) + 88
20 swift-frontend           0x0000000102f6a3d0 swift::ASTLoweringRequest::evaluate(swift::Evaluator&, swift::ASTLoweringDescriptor) const + 2664
21 swift-frontend           0x0000000103059828 swift::SimpleRequest<swift::ASTLoweringRequest, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule> > (swift::ASTLoweringDescriptor), (swift::RequestFlags)9>::evaluateRequest(swift::ASTLoweringRequest const&, swift::Evaluator&) + 204
22 swift-frontend           0x0000000102f6e1bc llvm::Expected<swift::ASTLoweringRequest::OutputType> swift::Evaluator::getResultUncached<swift::ASTLoweringRequest>(swift::ASTLoweringRequest const&) + 604
23 swift-frontend           0x000000010294c9a0 performCompile(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 3216
24 swift-frontend           0x000000010294a874 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 4308
25 swift-frontend           0x000000010290f5bc swift::mainEntry(int, char const**) + 4116
26 dyld                     0x00000001a50fff28 start + 2236

error: fatalError

```

**Comment by AnthonyLatsis** [comment] 2023-07-27 23:15
Duplicate of #57441

**Closed by AnthonyLatsis** 2023-07-27 23:15 UTC
Labels: bug, duplicate, compiler, type checker, SILGen, verifier, crash, property wrappers, swift 5.9
