### ISSUE TITLE
Isolated init crashes the compiler

### ISSUE THREAD

**Issue by tgoyne** [swiftlang/swift#74359] opened 2024-06-12 20:08 UTC
### Description

All of the forms I could think of to write an async init which is isolated to a parameter simply crash.

### Reproduction

```swift
struct Foo {
    init(actor: isolated MainActor) async {}
    // All of the following forms also produce the same crash:
    // init<A: Actor>(actor: isolated A) async {}
    // init(actor: isolated some Actor) async {}
    // init(actor: isolated any Actor) async {}
    // init(actor: isolated (any Actor)? = #isolation) async {}
}
Task { @MainActor in
    await Foo(actor: MainActor.shared)
}
```

### Stack dump

```text
0.	Program arguments: /Applications/Xcode-16.0.0-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-frontend -frontend -interpret foo.swift -Xllvm -aarch64-use-tbi -enable-objc-interop -stack-check -sdk /Applications/Xcode-16.0.0-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.0.sdk -color-diagnostics -new-driver-path /Applications/Xcode-16.0.0-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-driver -empty-abi-descriptor -resource-dir /Applications/Xcode-16.0.0-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift -module-name foo -disable-clang-spi -target-sdk-version 15.0 -target-sdk-name macosx15.0 -external-plugin-path /Applications/Xcode-16.0.0-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib/swift/host/plugins#/Applications/Xcode-16.0.0-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode-16.0.0-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/local/lib/swift/host/plugins#/Applications/Xcode-16.0.0-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin/swift-plugin-server -plugin-path /Applications/Xcode-16.0.0-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/host/plugins -plugin-path /Applications/Xcode-16.0.0-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/local/lib/swift/host/plugins
1.	Apple Swift version 6.0 (swiftlang-6.0.0.3.300 clang-1600.0.20.10)
2.	Compiling with effective version 5.10
3.	While evaluating request ASTLoweringRequest(Lowering AST to SIL for module foo)
4.	While silgen emitValueConstructor SIL function "@$s3foo3FooV5actorACScMYi_tYacfC".
 for 'init(actor:)' (at foo.swift:2:5)
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  swift-frontend           0x0000000105d22cd0 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 56
1  swift-frontend           0x0000000105d20f44 llvm::sys::RunSignalHandlers() + 112
2  swift-frontend           0x0000000105d232d8 SignalHandler(int) + 352
3  libsystem_platform.dylib 0x00000001806af584 _sigtramp + 56
4  libsystem_pthread.dylib  0x000000018067ec20 pthread_kill + 288
5  libsystem_c.dylib        0x000000018058ba30 abort + 180
6  swift-frontend           0x000000010067841c swift::Diagnostic::operator=(swift::Diagnostic const&) + 0
7  swift-frontend           0x0000000101153f90 swift::Lowering::SILGenFunction::emitMainExecutor(swift::SILLocation) + 0
8  swift-frontend           0x0000000101153ca0 swift::Lowering::SILGenFunction::emitConstructorPrologActorHop(swift::SILLocation, std::__1::optional<swift::ActorIsolation>) + 84
9  swift-frontend           0x000000010115648c swift::Lowering::SILGenFunction::emitValueConstructor(swift::ConstructorDecl*) + 2204
10 swift-frontend           0x0000000101103098 swift::Lowering::SILGenModule::emitFunctionDefinition(swift::SILDeclRef, swift::SILFunction*) + 7428
11 swift-frontend           0x0000000101103c2c swift::Lowering::SILGenModule::emitOrDelayFunction(swift::SILDeclRef) + 212
12 swift-frontend           0x0000000101104c64 swift::Lowering::SILGenModule::emitConstructor(swift::ConstructorDecl*) + 380
13 swift-frontend           0x00000001012349d4 (anonymous namespace)::SILGenType::emitType() + 564
14 swift-frontend           0x0000000101101078 swift::ASTVisitor<swift::Lowering::SILGenModule, void, void, void, void, void, void>::visit(swift::Decl*) + 104
15 swift-frontend           0x0000000101107200 swift::ASTLoweringRequest::evaluate(swift::Evaluator&, swift::ASTLoweringDescriptor) const + 1804
16 swift-frontend           0x000000010121ee68 swift::SimpleRequest<swift::ASTLoweringRequest, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule>> (swift::ASTLoweringDescriptor), (swift::RequestFlags)9>::evaluateRequest(swift::ASTLoweringRequest const&, swift::Evaluator&) + 196
17 swift-frontend           0x000000010110c0f4 swift::ASTLoweringRequest::OutputType swift::Evaluator::getResultUncached<swift::ASTLoweringRequest, swift::ASTLoweringRequest::OutputType swift::evaluateOrFatal<swift::ASTLoweringRequest>(swift::Evaluator&, swift::ASTLoweringRequest)::'lambda'()>(swift::ASTLoweringRequest const&, swift::ASTLoweringRequest::OutputType swift::evaluateOrFatal<swift::ASTLoweringRequest>(swift::Evaluator&, swift::ASTLoweringRequest)::'lambda'()) + 524
18 swift-frontend           0x00000001006ed6a8 swift::performCompileStepsPostSema(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 2484
19 swift-frontend           0x00000001006f1938 performCompile(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 2904
20 swift-frontend           0x00000001006ef438 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 4752
21 swift-frontend           0x00000001006752d8 swift::mainEntry(int, char const**) + 2812
22 dyld                     0x00000001802f60e0 start + 2360
[1]    7875 abort      DEVELOPER_DIR=/Applications/Xcode-16.0.0-beta.app swift foo.swift
```

### Expected behavior

It should compile correctly and run the init on the actor's executor.

### Environment

swift-driver version: 1.109.2 Apple Swift version 6.0 (swiftlang-6.0.0.3.300 clang-1600.0.20.10)
Target: arm64-apple-macosx14.0

**Comment by hborla** [comment] 2024-07-14 03:57
I'm pretty sure this is a dupe of an issue you've already filed

**Comment by hborla** [comment] 2024-07-14 03:58
Duplicate of https://github.com/swiftlang/swift/issues/71174

**Closed by hborla** 2024-07-14 03:58 UTC
Labels: bug, concurrency, crash

**Comment by tgoyne** [comment] 2024-07-15 20:07
Huh, I totally forgot that I'd tried it previously.
